Dialogue
{
	Id = "d.act.Denounce";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line ="$d.act.Denounce.fullLine1";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.Denounce.fullLine2";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.Denounce.fullLine3";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.Denounce.fullLine4";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.Denounce.fullLine5";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.Denounce.fullLine6";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsMale";		
			Line ="$d.act.Denounce.fullLine7";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsFemale";		
			Line ="$d.act.Denounce.fullLine7.aboutFemale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.Denounce.fullLine8";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsMale";
			Line ="$d.act.Denounce.fullLine9";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsFemale";
			Line ="$d.act.Denounce.fullLine9.aboutFemale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.Denounce.fullLine10";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.Denounce.fullLine11";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.Denounce.fullLine12";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.Denounce.fullLine13";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsMale";
			Line ="$d.act.denounce.fullLine14.toMale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsFemale";
			Line ="$d.act.denounce.fullLine14.toFemale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.denounce.fullLine15";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.denounce.fullLine16";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.denounce.fullLine17";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.denounce.fullLine18";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.denounce.fullLine19";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
		Topic
		{
			Line ="$d.act.denounce.fullLine20";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourceDenouncing
				};
			};
		},
	};
};

Dialogue
{
	Id = "d.act.Praise";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line ="$d.act.Praise.fullLine1";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.Praise.fullLine2";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.Praise.fullLine3";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.Praise.fullLine4";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.Praise.fullLine5";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.Praise.fullLine6";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.Praise.fullLine7";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.Praise.fullLine8";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.Praise.fullLine9";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.Praise.fullLine10";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.Praise.fullLine11";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.Praise.fullLine12";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.Praise.fullLine13";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsMale";
			Line ="$d.act.praise.fullLine14.toMale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsFemale";
			Line ="$d.act.praise.fullLine14.toFemale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsMale";
			Line ="$d.act.praise.fullLine15.toMale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsFemale";
			Line ="$d.act.praise.fullLine15.toFemale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsMale";
			Line ="$d.act.praise.fullLine16.toMale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsFemale";
			Line ="$d.act.praise.fullLine16.toFemale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsMale";
			Line ="$d.act.praise.fullLine17.toMale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsFemale";
			Line ="$d.act.praise.fullLine17.toFemale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.praise.fullLine18";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsMale";
			Line ="$d.act.praise.fullLine19.toMale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Enabled = "subject.IsFemale";
			Line ="$d.act.praise.fullLine19.toFemale";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
		Topic
		{
			Line ="$d.act.praise.fullLine20";
			TopicResult = ResultObject
			{
				Results = array
				{
					@base/SourcePraising
				};
			};
		},
	};
};

Dialogue
{
	Id = "d.act.PromoteOwnBusiness";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Enabled = "Target.hasTag.IsLowTier && !Target.hasTag.NoFrontStore";
			Line = "$d.act.PromoteOwnBusiness.LowTier.FrontStore.0";
		},
		Topic
		{
			Enabled = "Target.hasTag.IsLowTier && !Target.hasTag.NoFrontStore";
			Line = "$d.act.PromoteOwnBusiness.LowTier.FrontStore.1";
		},
		Topic
		{
			Enabled = "Target.hasTag.IsLowTier && !Target.hasTag.NoFrontStore";
			Line = "$d.act.PromoteOwnBusiness.LowTier.FrontStore.2";
		},
		Topic
		{
			Enabled = "Target.hasTag.IsLowTier && Target.hasTag.NoFrontStore";
			Line = "$d.act.PromoteOwnBusiness.LowTier.NoFrontStore.1";
		},
		Topic
		{
			Enabled = "Target.hasTag.IsLowTier && Target.hasTag.NoFrontStore";
			Line = "$d.act.PromoteOwnBusiness.LowTier.NoFrontStore.2";
		},
		Topic
		{
			Enabled = "Target.hasTag.IsLowTier && Target.hasTag.NoFrontStore";
			Line = "$d.act.PromoteOwnBusiness.LowTier.NoFrontStore.3";
		},

		Topic
		{
			Enabled = "Target.hasTag.IsHighTier && !Target.hasTag.NoFrontStore";
			Line = "$d.act.PromoteOwnBusiness.HighTier.FrontStore.0";
		},
		Topic
		{
			Enabled = "Target.hasTag.IsHighTier && !Target.hasTag.NoFrontStore";
			Line = "$d.act.PromoteOwnBusiness.HighTier.FrontStore.1";
		},
		Topic
		{
			Enabled = "Target.hasTag.IsHighTier && !Target.hasTag.NoFrontStore";
			Line = "$d.act.PromoteOwnBusiness.HighTier.FrontStore.2";
		},
		Topic
		{
			Enabled = "Target.hasTag.IsHighTier && Target.hasTag.NoFrontStore";
			Line = "$d.act.PromoteOwnBusiness.HighTier.NoFrontStore.1";
		},
		Topic
		{
			Enabled = "Target.hasTag.IsHighTier && Target.hasTag.NoFrontStore";
			Line = "$d.act.PromoteOwnBusiness.HighTier.NoFrontStore.2";
		},
		Topic
		{
			Enabled = "Target.hasTag.IsHighTier && Target.hasTag.NoFrontStore";
			Line = "$d.act.PromoteOwnBusiness.HighTier.NoFrontStore.3";
		},
	};
};

Dialogue
{
	Id = "d.act.UseStatelyDispatch";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$avr.bribe.opening.both";
			BranchType = "Pick";

			Replacements = map
			{    
				"SourceScoreFormula" = "Source.Charisma * 2.5 + Source.SocialLevel";
				"TargetScoreFormula" = "Target.Intelligence + Target.SocialLevel/2 + Target.Office.Stage";
				"CritFactor" = "1.0"; // (1 - CriticalFactor)
			};	
			DisplayChance = "EvaluateActionScore.SourceScoreFormula.TargetScoreFormula";
			OptionSubtext = array { "$gui.Char.Charisma" };

			TopicResult = ResultObject
			{
				Results = array
				{
					FunctionPlayRandomReaction
					{
						ApplyTo = "Source";
						Animations = array { "town_crier1" };
						VoiceOvers = array {512};
					},
					@base/TargetListen
				};
			};
			Next = array
			{
				//Success reply
				Topic
				{
					Line = "$avr.PublicPraise.opening.both";
					Speaker = "Switch";
					Probability = "SourceScoreFormula * CritFactor";
					TopicResult = ResultObject
					{
						Results = array
						{
							FunctionPlayRandomReaction
							{
								ApplyTo = "Target";
								Animations = array { "accept1" };
								VoiceOvers = array {451};
							},
							@base/SourceListen
						};
					};	
					ConversationResult = ResultObject
					{
						Results = array
						{
							DialogueSuccessType
							{
								  Type = "Success";
							},
							FunctionTrackObjectiveProgress
							{
								Amount = 5;
								ObjectiveTypename = "IncreaseSecurity";
							},
							FunctionSendMessage
							{
								ApplyTo = "Target";
								Description = "StatelyDispatchSuccessTarget";
							},
							FunctionUpdateRelationship
							{
								AffectTarget = "5";
							}
						};
					};
				},
				//Failure reply
				Topic
				{
					Line = "$cf.NPC.ToCitizen.Hatred.3";
					Speaker = "Switch";							
					Probability = "TargetScoreFormula * CritFactor";
					TopicResult = ResultObject
					{
						Results = array
						{
							FunctionPlayRandomReaction
							{
								ApplyTo = "Target";
								Animations = array { "rire1" };
								VoiceOvers = array {513};
							},
							@base/SourceShamed
						};
					};
					ConversationResult = ResultObject
					{
						Results = array
						{
							DialogueSuccessType
							{
								  Type = "Failure";
							},
							FunctionSendMessage
							{
								ApplyTo = "Target";
								Description = "StatelyDispatchFailureTarget";
							},
							FunctionUpdateRelationship
							{
								AffectTarget = "-5";
							}
						};
					};
				},
			};
		},
	};
};

Dialogue
{
	Id = "d.act.BribeWithWine";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$avr.bribe.opening.both";
			BranchType = "Pick";

			Replacements = map
			{    
				"SourceScoreFormula" = "Source.Charisma * 3 + Source.SocialLevel";
				"TargetScoreFormula" = "Target.Intelligence + Target.SocialLevel/2";
				"CritFactor" = "1.0"; // (1 - CriticalFactor)
			};	
			DisplayChance = "EvaluateActionScore.SourceScoreFormula.TargetScoreFormula";
			OptionSubtext = array { "$gui.Char.Charisma" };

			TopicResult = ResultObject
			{
				Results = array
				{
					FunctionPlayRandomReaction
					{
						ApplyTo = "Source";
						Animations = array { "town_crier1" };
						VoiceOvers = array {512};
					},
					@base/TargetListen
				};
			};
			Next = array
			{
				//Success reply
				Topic
				{
					//Drink the wine
					Probability = "SourceScoreFormula * CritFactor";
					Duration = "4.3";
					TopicResult = ResultObject
					{
						Results = array
						{
							FunctionPlayRandomReaction
							{
								ApplyTo = "Target";
								Animations = array { "drinkBanquet" };
								VoiceOvers = array {};
							},
							@base/SourceListen
						};
					};	
					Next = array
					{
						Topic
						{
							Line = "$avr.PublicPraise.opening.both";
							Speaker = "Switch";

							TopicResult = ResultObject
							{
								Results = array
								{
									FunctionPlayRandomReaction
									{
										ApplyTo = "Target";
										Animations = array { "accept1" };
										VoiceOvers = array {451};
									},
									@base/SourceListen
								};
							};	
							ConversationResult = ResultObject
							{
								Results = array
								{
									DialogueSuccessType
									{
										  Type = "Success";
									},
									FunctionTrackObjectiveProgress
									{
										Amount = 5;
										ObjectiveTypename = "IncreaseSecurity";
									},
									FunctionSendMessage
									{
										ApplyTo = "Target";
										Description = "ReceivedWine";
									},
									FunctionUpdateRelationship
									{
										AffectTarget = "7";
									}
								};
							};
						},
					};
				},
				//Failure reply
				Topic
				{
					//Drink the wine
					Probability = "TargetScoreFormula * CritFactor";
					Duration = "4.3";
					TopicResult = ResultObject
					{
						Results = array
						{
							FunctionPlayRandomReaction
							{
								ApplyTo = "Target";
								Animations = array { "drinkBanquet" };
								VoiceOvers = array {};
							},
							@base/SourceListen
						};
					};	
					Next = array
					{
						Topic
						{
							Line = "$cf.NPC.ToCitizen.Hatred.3";
							Speaker = "Switch";
							
							TopicResult = ResultObject
							{
								Results = array
								{
									FunctionPlayRandomReaction
									{
										ApplyTo = "Target";
										Animations = array { "rire1" };
										VoiceOvers = array {513};
									},
									@base/SourceShamed
								};
							};
							ConversationResult = ResultObject
							{
								Results = array
								{
									DialogueSuccessType
									{
										  Type = "Failure";
									},
									FunctionSendMessage
									{
										ApplyTo = "Target";
										Description = "ReceivedWine";
									},
									FunctionUpdateRelationship
									{
										AffectTarget = "-5";
									},
								};
							};
						},
					};
				},
			};
		},
	};
};

@base/DialogueStartRomance
@base/DialogueStartLiaison
@base/DialogueProposeMarriage
@base/DialogueStartWedding
@base/DialogueInstantWedding
@base/DialogueChurchWedding
@base/DialogueCourtingSomeone
@base/DialogueManipulateLiaison
@base/DialogueMarkAsOutlaw
@base/DialogueAwardKeyToCity
@base/DialogueBribeOfficeHolder
@base/DialogueGoCampaigning
@base/DialoguePublicShaming
@base/DialoguePublicPraise
@base/DialogueDuelInsult
@base/DialogueMakeCatholic
@base/DialogueMakeProtestant
@base/DialogueMakeSecular
@base/DialogueLureIntoRumDen
@base/DialogueTalkToMoA
@base/DialogueTalkToJailor
@base/DialogueTalkToPriest
@base/DialogueTalkToReceptionist
@base/DialogueTrial
@base/DialogueOffice
