
Dialogue
{
	Id = "$d.npcTowncrier.nonews";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$d.towncrier.nonews";
		}
	};
},

Dialogue
{
	Id = "$d.npcTowncrier.wrongtime";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$d.towncrier.wrongtime";
		}
	};
},

Dialogue
{
	Id = "d.npcTowncrier.1400";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1400.0";
		},
		Topic
		{
			Line = "$towncrier.1400.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1401";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1401.0";
		},
		Topic
		{
			Line = "$towncrier.1401.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1402";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1402.0";
		},
		Topic
		{
			Line = "$towncrier.1402.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1403";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1403.0";
		},
		Topic
		{
			Line = "$towncrier.1403.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1404";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1404.0";
		},
		Topic
		{
			Line = "$towncrier.1404.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1405";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1405.0";
		},
		Topic
		{
			Line = "$towncrier.1405.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1406";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1406.0";
		},
		Topic
		{
			Line = "$towncrier.1406.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1407";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1407.0";
		},
		Topic
		{
			Line = "$towncrier.1407.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1408";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1408.0";
		},
		Topic
		{
			Line = "$towncrier.1408.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1409";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1409.0";
		},
		Topic
		{
			Line = "$towncrier.1409.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1410";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1410.0";
		},
		Topic
		{
			Line = "$towncrier.1410.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1411";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1411.0";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1412";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1412.0";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1413";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1413.0";
		},
		Topic
		{
			Line = "$towncrier.1413.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1414";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1414.0";
		},
		Topic
		{
			Line = "$towncrier.1414.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1415";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1415.0";
		},
		Topic
		{
			Line = "$towncrier.1415.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1416";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1416.0";
		},
		Topic
		{
			Line = "$towncrier.1416.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1417";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1417.0";
		},
		Topic
		{
			Line = "$towncrier.1417.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1418";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1418.0";
		},
		Topic
		{
			Line = "$towncrier.1418.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1419";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1419.0";
		},
		Topic
		{
			Line = "$towncrier.1419.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1420";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1420.0";
		},
		Topic
		{
			Line = "$towncrier.1420.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1421";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1421.0";
		},
		Topic
		{
			Line = "$towncrier.1421.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1422";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1422.0";
		},
		Topic
		{
			Line = "$towncrier.1422.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1423";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1423.0";
		},
		Topic
		{
			Line = "$towncrier.1423.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1424";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1424.0";
		},
		Topic
		{
			Line = "$towncrier.1424.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1425";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1425.0";
		},
		Topic
		{
			Line = "$towncrier.1425.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1426";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1426.0";
		},
		Topic
		{
			Line = "$towncrier.1426.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1427";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1427.0";
		},
		Topic
		{
			Line = "$towncrier.1427.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1428";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1428.0";
		},
		Topic
		{
			Line = "$towncrier.1428.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1429";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1429.0";
		},
		Topic
		{
			Line = "$towncrier.1429.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1430";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1430.0";
		},
		Topic
		{
			Line = "$towncrier.1430.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1431";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1431.0";
		},
		Topic
		{
			Line = "$towncrier.1431.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1432";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1432.0";
		},
		Topic
		{
			Line = "$towncrier.1432.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1433";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1433.0";
		},
		Topic
		{
			Line = "$towncrier.1433.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1434";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1434.0";
		},
		Topic
		{
			Line = "$towncrier.1434.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1435";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1435.0";
		},
		Topic
		{
			Line = "$towncrier.1435.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1436";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1436.0";
		},
		Topic
		{
			Line = "$towncrier.1436.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1437";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1437.0";
		},
		Topic
		{
			Line = "$towncrier.1437.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1438";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1438.0";
		},
		Topic
		{
			Line = "$towncrier.1438.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1439";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1439.0";
		},
		Topic
		{
			Line = "$towncrier.1439.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1440";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1440.0";
		},
		Topic
		{
			Line = "$towncrier.1440.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1441";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1441.0";
		},
		Topic
		{
			Line = "$towncrier.1441.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1442";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1442.0";
		},
		Topic
		{
			Line = "$towncrier.1442.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1443";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1443.0";
		},
		Topic
		{
			Line = "$towncrier.1443.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1444";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1444.0";
		},
		Topic
		{
			Line = "$towncrier.1444.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1445";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1445.0";
		},
		Topic
		{
			Line = "$towncrier.1445.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1446";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1446.0";
		},
		Topic
		{
			Line = "$towncrier.1446.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1447";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1447.0";
		},
		Topic
		{
			Line = "$towncrier.1447.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1448";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1448.0";
		},
		Topic
		{
			Line = "$towncrier.1448.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1449";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1449.0";
		},
		Topic
		{
			Line = "$towncrier.1449.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1450";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1450.0";
		},
		Topic
		{
			Line = "$towncrier.1450.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1451";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1451.0";
		},
		Topic
		{
			Line = "$towncrier.1451.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1452";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1452.0";
		},
		Topic
		{
			Line = "$towncrier.1452.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1453";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1453.0";
		},
		Topic
		{
			Line = "$towncrier.1453.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1454";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1454.0";
		},
		Topic
		{
			Line = "$towncrier.1454.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1455";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1455.0";
		},
		Topic
		{
			Line = "$towncrier.1455.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1456";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1456.0";
		},
		Topic
		{
			Line = "$towncrier.1456.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1457";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1457.0";
		},
		Topic
		{
			Line = "$towncrier.1457.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1458";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1458.0";
		},
		Topic
		{
			Line = "$towncrier.1458.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1459";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1459.0";
		},
		Topic
		{
			Line = "$towncrier.1459.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1460";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1460.0";
		},
		Topic
		{
			Line = "$towncrier.1460.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1461";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1461.0";
		},
		Topic
		{
			Line = "$towncrier.1461.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1462";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1462.0";
		},
		Topic
		{
			Line = "$towncrier.1462.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1463";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1463.0";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1464";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1464.0";
		},
		Topic
		{
			Line = "$towncrier.1464.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1465";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1465.0";
		},
		Topic
		{
			Line = "$towncrier.1465.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1466";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1466.0";
		},
		Topic
		{
			Line = "$towncrier.1466.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1467";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1467.0";
		},
		Topic
		{
			Line = "$towncrier.1467.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1468";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1468.0";
		},
		Topic
		{
			Line = "$towncrier.1468.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1469";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1469.0";
		},
		Topic
		{
			Line = "$towncrier.1469.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1470";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1470.0";
		},
		Topic
		{
			Line = "$towncrier.1470.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1471";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1471.0";
		},
		Topic
		{
			Line = "$towncrier.1471.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1472";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1472.0";
		},
		Topic
		{
			Line = "$towncrier.1472.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1473";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1473.0";
		},
		Topic
		{
			Line = "$towncrier.1473.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1474";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1474.0";
		},
		Topic
		{
			Line = "$towncrier.1474.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1475";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1475.0";
		},
		Topic
		{
			Line = "$towncrier.1475.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1476";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1476.0";
		},
		Topic
		{
			Line = "$towncrier.1476.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1477";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1477.0";
		},
		Topic
		{
			Line = "$towncrier.1477.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1478";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1478.0";
		},
		Topic
		{
			Line = "$towncrier.1478.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1479";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1479.0";
		},
		Topic
		{
			Line = "$towncrier.1479.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1480";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1480.0";
		},
		Topic
		{
			Line = "$towncrier.1480.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1481";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1481.0";
		},
		Topic
		{
			Line = "$towncrier.1481.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1482";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1482.0";
		},
		Topic
		{
			Line = "$towncrier.1482.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1483";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1483.0";
		},
		Topic
		{
			Line = "$towncrier.1483.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1484";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1484.0";
		},
		Topic
		{
			Line = "$towncrier.1484.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1485";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1485.0";
		},
		Topic
		{
			Line = "$towncrier.1485.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1486";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1486.0";
		},
		Topic
		{
			Line = "$towncrier.1486.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1487";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1487.0";
		},
		Topic
		{
			Line = "$towncrier.1487.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1488";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1488.0";
		},
		Topic
		{
			Line = "$towncrier.1488.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1489";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1489.0";
		},
		Topic
		{
			Line = "$towncrier.1489.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1490";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1490.0";
		},
		Topic
		{
			Line = "$towncrier.1490.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1491";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1491.0";
		},
		Topic
		{
			Line = "$towncrier.1491.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1492";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1492.0";
		},
		Topic
		{
			Line = "$towncrier.1492.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1493";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1493.0";
		},
		Topic
		{
			Line = "$towncrier.1493.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1494";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1494.0";
		},
		Topic
		{
			Line = "$towncrier.1494.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1495";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1495.0";
		},
		Topic
		{
			Line = "$towncrier.1495.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1496";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1496.0";
		},
		Topic
		{
			Line = "$towncrier.1496.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1497";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1497.0";
		},
		Topic
		{
			Line = "$towncrier.1497.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1498";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1498.0";
		},
		Topic
		{
			Line = "$towncrier.1498.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1499";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1499.0";
		},
		Topic
		{
			Line = "$towncrier.1499.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1500";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1500.0";
		},
		Topic
		{
			Line = "$towncrier.1500.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1501";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1501.0";
		},
		Topic
		{
			Line = "$towncrier.1501.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1502";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1502.0";
		},
		Topic
		{
			Line = "$towncrier.1502.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1503";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1503.0";
		},
		Topic
		{
			Line = "$towncrier.1503.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1504";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1504.0";
		},
		Topic
		{
			Line = "$towncrier.1504.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1505";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1505.0";
		},
		Topic
		{
			Line = "$towncrier.1505.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1506";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1506.0";
		},
		Topic
		{
			Line = "$towncrier.1506.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1507";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1507.0";
		},
		Topic
		{
			Line = "$towncrier.1507.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1508";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1508.0";
		},
		Topic
		{
			Line = "$towncrier.1508.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1509";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1509.0";
		},
		Topic
		{
			Line = "$towncrier.1509.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1510";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1510.0";
		},
		Topic
		{
			Line = "$towncrier.1510.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1511";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1511.0";
		},
		Topic
		{
			Line = "$towncrier.1511.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1512";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1512.0";
		},
		Topic
		{
			Line = "$towncrier.1512.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1513";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1513.0";
		},
		Topic
		{
			Line = "$towncrier.1513.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1514";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1514.0";
		},
		Topic
		{
			Line = "$towncrier.1514.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1515";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1515.0";
		},
		Topic
		{
			Line = "$towncrier.1515.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1516";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1516.0";
		},
		Topic
		{
			Line = "$towncrier.1516.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1517";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1517.0";
		},
		Topic
		{
			Line = "$towncrier.1517.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1518";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1518.0";
		},
		Topic
		{
			Line = "$towncrier.1518.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1519";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1519.0";
		},
		Topic
		{
			Line = "$towncrier.1519.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1520";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1520.0";
		},
		Topic
		{
			Line = "$towncrier.1520.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1521";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1521.0";
		},
		Topic
		{
			Line = "$towncrier.1521.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1522";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1522.0";
		},
		Topic
		{
			Line = "$towncrier.1522.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1523";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1523.0";
		},
		Topic
		{
			Line = "$towncrier.1523.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1524";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1524.0";
		},
		Topic
		{
			Line = "$towncrier.1524.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1525";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1525.0";
		},
		Topic
		{
			Line = "$towncrier.1525.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1526";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1526.0";
		},
		Topic
		{
			Line = "$towncrier.1526.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1527";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1527.0";
		},
		Topic
		{
			Line = "$towncrier.1527.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1528";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1528.0";
		},
		Topic
		{
			Line = "$towncrier.1528.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1529";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1529.0";
		},
		Topic
		{
			Line = "$towncrier.1529.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1530";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1530.0";
		},
		Topic
		{
			Line = "$towncrier.1530.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1531";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1531.0";
		},
		Topic
		{
			Line = "$towncrier.1531.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1532";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1532.0";
		},
		Topic
		{
			Line = "$towncrier.1532.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1533";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1533.0";
		},
		Topic
		{
			Line = "$towncrier.1533.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1534";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1534.0";
		},
		Topic
		{
			Line = "$towncrier.1534.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1535";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1535.0";
		},
		Topic
		{
			Line = "$towncrier.1535.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1536";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1536.0";
		},
		Topic
		{
			Line = "$towncrier.1536.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1537";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1537.0";
		},
		Topic
		{
			Line = "$towncrier.1537.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1538";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1538.0";
		},
		Topic
		{
			Line = "$towncrier.1538.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1539";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1539.0";
		},
		Topic
		{
			Line = "$towncrier.1539.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1540";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1540.0";
		},
		Topic
		{
			Line = "$towncrier.1540.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1541";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1541.0";
		},
		Topic
		{
			Line = "$towncrier.1541.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1542";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1542.0";
		},
		Topic
		{
			Line = "$towncrier.1542.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1543";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1543.0";
		},
		Topic
		{
			Line = "$towncrier.1543.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1544";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1544.0";
		},
		Topic
		{
			Line = "$towncrier.1544.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1545";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1545.0";
		},
		Topic
		{
			Line = "$towncrier.1545.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1546";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1546.0";
		},
		Topic
		{
			Line = "$towncrier.1546.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1547";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1547.0";
		},
		Topic
		{
			Line = "$towncrier.1547.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1548";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1548.0";
		},
		Topic
		{
			Line = "$towncrier.1548.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1549";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1549.0";
		},
		Topic
		{
			Line = "$towncrier.1549.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1550";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1550.0";
		},
		Topic
		{
			Line = "$towncrier.1550.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1551";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1551.0";
		},
		Topic
		{
			Line = "$towncrier.1551.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1552";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1552.0";
		},
		Topic
		{
			Line = "$towncrier.1552.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1553";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1553.0";
		},
		Topic
		{
			Line = "$towncrier.1553.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1554";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1554.0";
		},
		Topic
		{
			Line = "$towncrier.1554.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1555";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1555.0";
		},
		Topic
		{
			Line = "$towncrier.1555.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1556";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1556.0";
		},
		Topic
		{
			Line = "$towncrier.1556.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1557";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1557.0";
		},
		Topic
		{
			Line = "$towncrier.1557.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1558";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1558.0";
		},
		Topic
		{
			Line = "$towncrier.1558.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1559";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1559.0";
		},
		Topic
		{
			Line = "$towncrier.1559.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1560";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1560.0";
		},
		Topic
		{
			Line = "$towncrier.1560.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1561";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1561.0";
		},
		Topic
		{
			Line = "$towncrier.1561.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1562";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1562.0";
		},
		Topic
		{
			Line = "$towncrier.1562.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1563";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1563.0";
		},
		Topic
		{
			Line = "$towncrier.1563.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1564";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1564.0";
		},
		Topic
		{
			Line = "$towncrier.1564.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1565";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1565.0";
		},
		Topic
		{
			Line = "$towncrier.1565.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1566";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1566.0";
		},
		Topic
		{
			Line = "$towncrier.1566.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1567";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1567.0";
		},
		Topic
		{
			Line = "$towncrier.1567.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1568";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1568.0";
		},
		Topic
		{
			Line = "$towncrier.1568.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1569";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1569.0";
		},
		Topic
		{
			Line = "$towncrier.1569.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1570";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1570.0";
		},
		Topic
		{
			Line = "$towncrier.1570.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1571";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1571.0";
		},
		Topic
		{
			Line = "$towncrier.1571.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1572";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1572.0";
		},
		Topic
		{
			Line = "$towncrier.1572.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1573";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1573.0";
		},
		Topic
		{
			Line = "$towncrier.1573.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1574";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1574.0";
		},
		Topic
		{
			Line = "$towncrier.1574.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1575";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1575.0";
		},
		Topic
		{
			Line = "$towncrier.1575.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1576";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1576.0";
		},
		Topic
		{
			Line = "$towncrier.1576.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1577";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1577.0";
		},
		Topic
		{
			Line = "$towncrier.1577.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1578";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1578.0";
		},
		Topic
		{
			Line = "$towncrier.1578.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1579";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1579.0";
		},
		Topic
		{
			Line = "$towncrier.1579.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1580";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1580.0";
		},
		Topic
		{
			Line = "$towncrier.1580.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1581";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1581.0";
		},
		Topic
		{
			Line = "$towncrier.1581.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1582";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1582.0";
		},
		Topic
		{
			Line = "$towncrier.1582.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1583";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1583.0";
		},
		Topic
		{
			Line = "$towncrier.1583.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1584";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1584.0";
		},
		Topic
		{
			Line = "$towncrier.1584.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1585";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1585.0";
		},
		Topic
		{
			Line = "$towncrier.1585.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1586";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1586.0";
		},
		Topic
		{
			Line = "$towncrier.1586.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1587";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1587.0";
		},
		Topic
		{
			Line = "$towncrier.1587.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1588";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1588.0";
		},
		Topic
		{
			Line = "$towncrier.1588.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1589";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1589.0";
		},
		Topic
		{
			Line = "$towncrier.1589.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1590";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1590.0";
		},
		Topic
		{
			Line = "$towncrier.1590.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1591";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1591.0";
		},
		Topic
		{
			Line = "$towncrier.1591.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1592";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1592.0";
		},
		Topic
		{
			Line = "$towncrier.1592.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1593";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1593.0";
		},
		Topic
		{
			Line = "$towncrier.1593.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1594";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1594.0";
		},
		Topic
		{
			Line = "$towncrier.1594.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1595";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1595.0";
		},
		Topic
		{
			Line = "$towncrier.1595.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1596";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1596.0";
		},
		Topic
		{
			Line = "$towncrier.1596.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1597";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1597.0";
		},
		Topic
		{
			Line = "$towncrier.1597.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1598";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1598.0";
		},
		Topic
		{
			Line = "$towncrier.1598.1";
		}
	};
},
Dialogue
{
	Id = "d.npcTowncrier.1599";
	BranchType = "Pick";
	Topics = array
	{
		Topic
		{
			Line = "$towncrier.1599.0";
		},
		Topic
		{
			Line = "$towncrier.1599.1";
		}
	};
},
