TutorialChapter
{
	ID = "GameplayConceptTutorialReputation";
	Title = "$ui.GameplayConceptTutorial.Reputation1";
	Elements = array
	{
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Reputation2"; // the localization key
		},		
		//column header
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Reputation5"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Reputation3"; // the localization key
		},
		//column content
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Reputation6"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Reputation4"; // the localization key
		},
		//column end
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Reputation\ReputationDynastiesandDistrics.png"; // the localization key
		},
		/*
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\DynastyRelationOverview.png"; // the localization key
		},
		*/
		TutorialElement //Family Feud
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Reputation7"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Reputation8"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Reputation\ReputationDeclareFeud.png"; // the localization key
		},
		TutorialElement //Alliance
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Reputation9"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Reputation10"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Reputation\ReputationAllience.png"; // the localization key
		},
				TutorialElement //Judges
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Reputation11"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Reputation12"; // the localization key
		}
	};
},