TutorialChapter
{
	ID = "GameplayConceptTutorialTime";
	Title = "$ui.GameplayConceptTutorial.Time1";
	Elements = array
	{
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Time2"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Time3"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Time4"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\$ui.GameplayConceptTutorial.Time4.png"; // the localization key
		},
	};
},