TutorialChapter
{
	ID = "GameplayConceptTutorialCameraControls";
	Title = "$ui.GameplayConceptTutorial.CameraControls1";
	Elements = array
	{
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.CameraControls1"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.CameraControls2"; // the localization key
		},
		//header camera modes
		TutorialElement //horizontalMovement
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.CameraControls3"; // the localization key
		},
		TutorialElement //Zoom
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.CameraControls5"; // the localization key
		},
		TutorialElement //rotate
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.CameraControls7"; // the localization key
		},
		TutorialElement //tilt
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.CameraControls9"; // the localization key
		},
		//content camera modes
		TutorialElement //HorizontalMovement
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.CameraControls4"; // the localization key
		},
		TutorialElement //zoom
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.CameraControls6"; // the localization key
		},
		TutorialElement//rotate
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.CameraControls8"; // the localization key
		},
		TutorialElement //tilt
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.CameraControls10"; // the localization key
		},
		//end partition section
		TutorialElement //interior camera
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.InteriorCamera_title"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.InteriorCamera_text"; // the localization key
		},
		
		TutorialElement //camera modes
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.CameraControls11"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.CameraControls12"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95 ; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\CameraControl_Main.png"; // the localization key
		},
	};
},