TutorialChapter
{
	ID = "GameplayConceptTutorialRomancing";
	Title = "$ui.GameplayConceptTutorial.Romancing1";
	Elements = array
	{
		TutorialElement //general
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Romancing2"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\RomanceWiki\Marriage.png"; // the localization key
		},
		TutorialElement //embark on romance
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Romancing3"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Romancing4"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\RomanceWiki\RomanceActions.png"; // the localization key
		},
		TutorialElement //find partner
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Romancing5"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Romancing6"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\RomanceWiki\$ui.GameplayConceptTutorial.Romancing6.png"; // the localization key
		},
		TutorialElement //courtship
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Romancing9"; // the localization key
		},
	    TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Romancing10"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\RomanceWiki\$ui.GameplayConceptTutorial.Romancing10.png"; // the localization key
		},
		TutorialElement //marriage proposal
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Romancing11"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Romancing12"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\RomanceWiki\RomanceMarriage.png"; // the localization key
		},
		TutorialElement //rejection
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Romancing13"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Romancing14"; // the localization key
		},
		
	};
},