TutorialChapter
{
	ID = "GameplayConceptTutorialResources";
	Title = "$ui.GameplayConceptTutorial.Resources1";
	Elements = array
	{
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Resources1"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Resources2"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\MoneyAndInfluenceWiki\$ui.GameplayConceptTutorial.Resources2.png";
		},
		//column header
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Resources3"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.GameplayConceptTutorial.Resources5"; // the localization key
		},
		//column content
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Resources4"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "$ui.GameplayConceptTutorial.Resources6"; // the localization key
		},
		//end column
	};
},