TutorialChapter
{
	ID = "GuidedTutorialConstructBuilding";
	Title = "$ui.GuidedTutorial.ConstructBuilding1";
	ShowInKnowledgeHub = false;
	Elements = array
	{
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.75; // relative width, [0.0 -> 1.0]
			Content = "$ui.GuidedTutorial.ConstructBuilding2"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.22; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Erect building\ErectBuildingMain.png"; // the localization key
		},	
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.49; // relative width, [0.0 -> 1.0]
			Content = "$ui.GuidedTutorial.ConstructBuilding3"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.49; // relative width, [0.0 -> 1.0]
			Content = "$ui.GuidedTutorial.ConstructBuilding4"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.49; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\SelectBuilding.png"; // the localization key
		},	
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.49; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\NameBuilding.png"; // the localization key
		},	
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 1.0; // relative width, [0.0 -> 1.0]
			Content = "$ui.GuidedTutorial.ConstructBuilding5"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.32; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\BuildingPlacementInvalid.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.32; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\BuildingPlacementValid.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.32; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\BuildingPlacementPlaced.png"; // the localization key
		},		
	};
},