TutorialChapter
{
	ID = "GuidedTutorialProduce";
	Title = "$ui.GuidedTutorial.Produce1";
	ShowInKnowledgeHub = false;
	Elements = array
	{
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.3; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\OpenBuildingMenu.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.68; // relative width, [0.0 -> 1.0]
			Content = "$ui.GuidedTutorial.Produce2"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.49; // relative width, [0.0 -> 1.0]
			Content = "$ui.GuidedTutorial.Produce3"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.49; // relative width, [0.0 -> 1.0]
			Content = "$ui.GuidedTutorial.Produce5"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.49; // relative width, [0.0 -> 1.0]
			Content = "$ui.GuidedTutorial.Produce4"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.49; // relative width, [0.0 -> 1.0]
			Content = "$ui.GuidedTutorial.Produce6"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\HireButtons.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 1.0; // relative width, [0.0 -> 1.0]
			Content = "$ui.GuidedTutorial.Produce7"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\AssignWorkManually.png"; // the localization key
		},
	};
},