TutorialChapter
{
	ID = "HelpTutorialCalendarAppointment";
	Title = "$ui.HelpTutorial.Calendar1";
	Elements = array
	{
		
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.CalendarAppointment1"; // the localization key
		},
		
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.CalendarAppointment2"; // the localization key
		},
		
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Calendar\CalendarMain.png"; // the localization key
		},
		
	};
},
