TutorialChapter
{
	ID = "HelpTutorialGuilds";
	Title = "$ui.HelpTutorial.Guilds1";
	Elements = array
	{
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Guilds1a"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\GuildsWiki\GuildButton.png"; // the image source path
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\GuildsWiki\$ui.HelpTutorial.Guilds1a.png"; // the image source path
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Guilds2"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\GuildsWiki\$ui.HelpTutorial.Guilds2-2.png"; // the image source path
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Guilds_Header2"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Guilds_Text2"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\GuildsWiki\Guilds_Attitude.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Guilds3"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Guilds4"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Guilds7"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Guilds8"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\GuildsWiki\$ui.HelpTutorial.Guilds8.png"; // the image source path
		},
		/*
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\GuildsWiki\Guilds.png"; // the image source path
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.15; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\LeaveGuildButton.png"; // the image source path
		},
		*/
	};
},