TutorialChapter
{
	ID = "HelpTutorialPublicBuildings";
	Title = "$gui.sys.PublicBuildings";
	Elements = array
	{
		
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.PublicBuildings_title"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.PublicBuildings_text"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.ChurchOverview_header"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.ChurchOverview_text"; // the localization key
		},
		
		//Wedding&Adoption&Monastery header
		
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.30; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.ChurchAdoption_header"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.31; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.ChurchMonastery_header"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.31; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.ChurchWedding_header"; // the localization key
		},
				
		//Wedding&Adoption&Monastery header
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.30; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.ChurchAdoption_text"; // the localization key
		},	
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.31; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.ChurchMonastery_text"; // the localization key
		},	
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.31; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.ChurchWedding_text"; // the localization key
		},
		
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\PublicBuildingsWiki\publicBuilding_churchDialog.png";
		},
		
		//Religion&Donation
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.ChurchReligion_header"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.ChurchDonation_header"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.ChurchReligion_text"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.ChurchDonation_text"; // the localization key
		},
		
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\PublicBuildingsWiki\publicBuilding_baptismalFont.png";
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\PublicBuildingsWiki\publicBuilding_donationBox.png";
		},
		
		//Arsenal
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Arsenal_header";
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Arsenal_text2";
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\PublicBuildingsWiki\publicBuilding_ArsenalSpeech.png";
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Arsenal_header2";
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Arsenal_text3";
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\PublicBuildingsWiki\publicBuilding_QuestBook.png";
		},

		
		//Town Hall
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.TownHall_header"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.TownHall_text"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\PublicBuildingsWiki\TownClerkDialogue.png";
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.School_header"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.School_text"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\PublicBuildingsWiki\publicBuilding_school.png";
		},
	};
},
