TutorialChapter
{
	ID = "HelpTutorialMarket";
	Title = "$ui.HelpTutorial.Market1";
	Elements = array
	{
		
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Market2"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Market\$ui.HelpTutorial.Market2.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Market2a"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Market\$ui.HelpTutorial.Market2a.png"; // the localization key
		},
		//column header
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.31; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Market3"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.30; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Market5"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.31; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Market7"; // the localization key
		},
		//column content
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.31; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Market4"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.30; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Market6"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.31; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Market8"; // the localization key
		},
		//end column
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Market\$ui.HelpTutorial.Market8.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Market9"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Market10"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Market\$ui.HelpTutorial.Market10.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Market14"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Market15"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Market\$ui.HelpTutorial.Market15.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$gui.tab.priceTrends"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Market12"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Market\market2.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$gui.tab.needs"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Market13"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Market\Needs.png"; // the localization key
		},
	};
},