TutorialChapter
{
	ID = "HelpTutorialDynastyTree";
	Title = "$ui.HelpTutorial.DynastyTree5";
	Elements = array
	{
		// Image type content
		// 30% width, automatically centered
		// reached end of line, row break afte
		// Text type content
		// 68% width, automatically centered
		// reached end of line, row break after
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.DynastyTree5"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyTree1"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyTree9"; // the localization key
		},	
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\FamilyTreeWiki\$ui.HelpTutorial.DynastyTree9.png"; // the image source path
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyTree10"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\FamilyTreeWiki\$ui.HelpTutorial.DynastyTree10.png"; // the image source path
		},	
	};
},