TutorialChapter
{
	ID = "HelpTutorialHUD";
	Title = "$ui.HelpTutorial.HUD1";
	Elements = array
	{
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.HUD2"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\HUDwiki\$ui.HelpTutorial.HUD2.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.HUD3"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.HUD4"; // the localization key
		},	
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\HUDwiki\$ui.HelpTutorial.HUD4.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.HUD5"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.HUD6"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\HUDwiki\$ui.HelpTutorial.HUD6.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.HUD7"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.HUD8"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\HUDwiki\$ui.HelpTutorial.HUD8.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.HUD9"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.70; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.HUD10"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.24; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\HUDwiki\$ui.HelpTutorial.HUD10.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.HUD13"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.70; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.HUD14"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.24; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\HUDwiki\$ui.HelpTutorial.HUD14.png"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.HUD11"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.HUD12"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\HUDwiki\$ui.HelpTutorial.HUD12.png"; // the localization key
		},
		
		//Interior
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.HUD.InteriorButtons_title"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.HUD.InteriorLeave_content"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\HUDwiki\$ui.HelpTutorial.HUD.InteriorLeave_content.png"; // the localization key
		},
		
		//Gameplay Options through ESC/Options
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.HUD-GameplayOptions1"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.HUD-GameplayOptions2"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\HUDwiki\$ui.HelpTutorial.HUD-GameplayOptions2.png"; // the localization key
		},
		/*TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.93; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.HUD-GameplayOptions3"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.93; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.HUD-GameplayOptions4"; // the localization key
		},
		*/

	};
},