TutorialChapter
{
	ID = "HelpTutorialTitlesAndSkillTree";
	Title = "$ui.HelpTutorial.TitlesAndSkillTree1";
	Elements = array
	{
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.TitlesAndSkillTree2"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\TitlesSkillsWiki\$ui.HelpTutorial.TitlesAndSkillTree2.png"; // the image source path
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.TitlesAndSkillTree4"; // the localization key
		},	
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\TitlesSkillsWiki\$ui.HelpTutorial.TitlesAndSkillTree4.png"; // the image source path
		},
		//column header
		TutorialElement //titles
		{
			Type = "Text"; // content type
			Size = 0.31; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.TitlesAndSkillTree4a"; // the localization key
		},
		TutorialElement //skills
		{
			Type = "Text"; // content type
			Size = 0.30; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.TitlesAndSkillTree5"; // the localization key
		},
		TutorialElement //skill paths
		{
			Type = "Text"; // content type
			Size = 0.31; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.TitlesAndSkillTree7"; // the localization key
		},
		//column content
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.31; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.TitlesAndSkillTree4b"; // the localization key
		},	
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.30; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.TitlesAndSkillTree6"; // the localization key
		},	
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.31; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.TitlesAndSkillTree8"; // the localization key
		},
		//column end
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\TitlesSkillsWiki\$ui.HelpTutorial.TitlesAndSkillTree4b.png"; // the image source path
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.TitlesAndSkillTree9"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.TitlesAndSkillTree10"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\TitlesSkillsWiki\$ui.HelpTutorial.TitlesAndSkillTree10.png"; // the image source path
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.TitlesAndSkillTree11"; // the localization key
		},
	};
},