TutorialChapter
{
	ID = "HelpTutorialDynastyTrade";
	Title = "$ui.HelpTutorial.DynastyTrade1";
	Elements = array
	{
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyTrade2"; // the localization key
		},
		TutorialElement //make an offer
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.DynastyTrade3"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyTrade4a"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\DynasticTradeWiki\DynastyTradeActionbar.png"; // the localization key
		},
		TutorialElement //respond to an offer
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.DynastyTrade5"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyTrade6"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.47; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\DynasticTradeWiki\$ui.HelpTutorial.DynastyTrade6.png"; // the localization key
		},
		TutorialElement //good&bad offers
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.DynastyTrade7"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyTrade8"; // the localization key
		},
	
	};
},