TutorialChapter
{
	ID = "HelpTutorialStatistics";
	Title = "$ui.HelpTutorial.Statistics1";
	Elements = array
	{
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Statistics1"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Statistics2"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Statistics\$ui.HelpTutorial.Statistics2.png"; // the image source path
		},	

		//header budget tabs
		TutorialElement //businesses
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Statistics3"; // the localization key
		},
		TutorialElement //resource provider
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Statistics5-1"; // the localization key
		},
		TutorialElement //family
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Statistics5"; // the localization key
		},
		TutorialElement //score
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Statistics7"; // the localization key
		},
		
		//content budget tabs
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Statistics4"; // the localization key
		},	
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Statistics5-2"; // the localization key
		},	
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Statistics6"; // the localization key
		},		
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.23; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Statistics8"; // the localization key
		},
		
		//Winning points entry
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Statistics\$ui.HelpTutorial.Statistics8.png"; // the image source path
		},
		TutorialElement //Timeline
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.Statistics9"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Statistics10"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\timeline.png"; // the image source path
		},
	};
},