TutorialChapter
{
	ID = "HelpTutorialPolitics";
	Title = "$ui.HelpTutorial.Politics1";
	Elements = array
	{
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Politics2"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\PoliticsWiki\PoliticsMain.png"; // the localization key
		},

	};
},