TutorialChapter
{
	ID = "HelpTutorialCalendar";
	Title = "$ui.HelpTutorial.Calendar1";
	Elements = array
	{
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.Calendar2"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\Calendar\CalendarMain.png"; // the localization key
		},
	};
},