TutorialChapter //Book of Dynasties
{
	ID = "HelpTutorialDynastyOverview";
	Title = "$ui.HelpTutorial.DynastyOverview1";
	Elements = array
	{
		
		TutorialElement //general
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyOverview2"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyOverview2a"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\BookOfDynastiesWiki\$ui.HelpTutorial.DynastyOverview2a.png"; // the localization key
		},
		TutorialElement //select dynasty
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.DynastyOverview4a"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyOverview4b"; // the localization key
		},
		TutorialElement 
		{
			Type = "Image"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\BookOfDynastiesWiki\$ui.HelpTutorial.DynastyOverview4b.png"; // the localization key
		},
		TutorialElement //Attitude
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.DynastyOverview5"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyOverview6"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\BookOfDynastiesWiki\$ui.HelpTutorial.DynastyOverview6.png"; // the localization key
		},
		TutorialElement //Romances&Liaisons
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.DynastyOverview7"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyOverview8"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\BookOfDynastiesWiki\BookOfDynasties_RomancesLiaisons.png"; // the localization key
		},
		TutorialElement //Hostages
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.DynastyOverview9"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyOverview10"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\BookOfDynastiesWiki\$ui.HelpTutorial.DynastyOverview10.png"; // the localization key
		},
		TutorialElement //Popularity
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.DynastyOverview11"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyOverview12"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\BookOfDynastiesWiki\$ui.HelpTutorial.DynastyOverview12.png"; // the localization key
		},
		TutorialElement //evidences
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.DynastyOverview13"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyOverview14"; // the localization key
		},	
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\BookOfDynastiesWiki\$ui.HelpTutorial.DynastyOverview14.png"; // the localization key
		},
		TutorialElement //relationships between dynasties
		{
			Type = "Text"; // content type
			Size = 0.95; // relative width, [0.0 -> 1.0]
			FontSize = 15.0;
			FontName = bold;
			Content = "$ui.HelpTutorial.DynastyOverview15"; // the localization key
		},
		TutorialElement
		{
			Type = "Text"; // content type
			Size = 0.57; // relative width, [0.0 -> 1.0]
			Content = "$ui.HelpTutorial.DynastyOverview16"; // the localization key
		},
		TutorialElement
		{
			Type = "Image"; // content type
			Size = 0.37; // relative width, [0.0 -> 1.0]
			Content = "media\UserInterface\Tutorial\BookOfDynastiesWiki\$ui.HelpTutorial.DynastyOverview16.png"; // the image source path
		},
	};
},