G3SoundObject
{
	SoundID = 1;	// EInterfaceSoundsID - checkbox
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Checkbox.ogg";
		};
	};
};
G3SoundObject
{
	SoundID = 2;	// error
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Error.ogg";
		};
	};
};
G3SoundObject
{
	SoundID = 3;	// Money
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Money.ogg";
		};
	};
};
G3SoundObject
{
	SoundID = 4;	// NewMessage
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/NewMessage.ogg";
		};
	};
};
G3SoundObject
{
	SoundID = 5;	// window close
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/CloseMenu.ogg";
		};
	};
};
G3SoundObject
{
	SoundID = 6;	// window open
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/OpenMenu.ogg";
		};
	};
};
G3SoundObject
{
	SoundID = 7;	// click
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/SelectClick.wav";
		};
	};
};
G3SoundObject
{
	SoundID = 8;	// ObjectiveMet
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/ObjectiveMet.wav";
		};
	};
};
G3SoundObject
{
	SoundID = 9;	// level up
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/levelup.ogg";
		};
	};
};
G3SoundObject
{
	SoundID = 10;	// you're dead Jim
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_GameLost.ogg";
		};
	};
};
G3SoundObject
{
	SoundID = 11;	// elected
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_NewOffice.ogg";
		};
	};
};
G3SoundObject
{
	SoundID = 12;	// something fucked
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_ProblemsInSupplyChain.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 13;	// EInterfaceFormOpen0 (attention, le son Form_open0.ogg est une copie de ParchmentOpen.ogg)
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Form_open0.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 14;	// EInterfaceFormOpen1 (attention, le son Form_open1.ogg est une copie de ParchmentOpen.ogg)
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Form_open1.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 15;	// EInterfaceFormOpen2 (attention, le son Form_open2.ogg est une copie de ParchmentOpen.ogg)
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Form_open2.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 16;	// EInterfaceFormOpen3 (attention, le son Form_open3.ogg est une copie de ParchmentOpen.ogg)
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Form_open3.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 17;	// EInterfaceFormOpen4 (attention, le son Form_open4.ogg est une copie de ParchmentOpen.ogg)
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Form_open4.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 18;	// EInterfaceFormOpen5 (attention, le son Form_open5.ogg est une copie de ParchmentOpen.ogg)
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Form_open5.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 19;	// EInterfaceFormOpen6 (attention, le son Form_open6.ogg est une copie de ParchmentOpen.ogg)
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Form_open6.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 20;	// EInterfaceFormOpen7 (attention, le son Form_open7.ogg est une copie de ParchmentOpen.ogg)
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Form_open7.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 21;	// EInterfaceLoadingGoods (attention, le son LoadingGoods_I_01.ogg est une copie de levelup.ogg)
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/LoadingGoods_I_01.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 22;	// EInterfaceJingleNewTitle (attention, le son Jingle_NewTitle.ogg est une copie de Jingle_NewOffice.ogg)
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_NewTitle.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 23;	// EInterfaceJingleNewBuilding (attention, le son Jingle_NewBuilding.ogg est une copie de Jingle_NewOffice.ogg)
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_NewBuilding.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 24;	// EInterfaceJingleNewHighOffice (attention, le son Jingle_NewHighOffice.ogg est une copie de Jingle_NewOffice.ogg)
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_NewHighOffice.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 25;	// EInterfaceJingleSubquestFulfilled (attention, le son Jingle_SubquestFulfilled.ogg est une copie de Jingle_NewOffice.ogg)
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_SubquestFulfilled.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 26;	// EInterfaceJingleMainQuestFulfilled (attention, le son Jingle_MainquestFulfilled.ogg est une copie de Jingle_NewOffice.ogg)
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_MainquestFulfilled.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 27;	// EInterfaceJingleOfficeLost (attention, le son Jingle_OfficeLost.ogg est une copie de Jingle_GameLost.ogg)
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_OfficeLost.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 28;	// EInterfaceJingleUnderAttackAvatar (attention, le son Jingle_UnderAttackAvatar.ogg est une copie de Jingle_GameLost.ogg)
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_UnderAttackAvatar.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 29;	// EInterfaceJingleUnderAttack (attention, le son Jingle_UnderAttack.ogg est une copie de Jingle_GameLost.ogg)
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_UnderAttack.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 30;	// EInterfaceJingleBirth (attention, le son Jingle_Birth.ogg est une copie de Jingle_NewOffice.ogg)
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_Birth.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 31;	// EInterfaceJingleDeathOfAnOpponent(attention, le son Jingle_DeathOfAnOpponent.ogg est une copie de Jingle_GameLost.ogg)
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_DeathOfAnOpponent.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 32;	// EInterfaceJinglePositiveMessage(attention, le son Jingle_PositiveMessage.ogg est une copie de Jingle_NewOffice.ogg)
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_PositiveMessage.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 33;	// EInterfaceJingleNeutralMessage(attention, le son Jingle_NeutralMessage.ogg est une copie de Jingle_NewOffice.ogg)
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/NewMessage.ogg";
//			Path = "media/SFX/Interface/Jingle_NeutralMessage.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 34;	// EInterfaceJingleNegativeMessage(attention, le son Jingle_NegativeMessage.ogg est une copie de Jingle_NewOffice.ogg)
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_NegativeMessage.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 35;	// EInterfaceJingleNegativeMessage(attention, le son Jingle_NegativeMessage.ogg est une copie de Jingle_NewOffice.ogg)
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/ParchmentOpen.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 36;	// EInterfaceMapOpen
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/ParchmentOpen.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 37;	// Valid target selection
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef { Path = "media/SFX/Interface/SelectClick.wav"; };
	};
};

G3SoundObject
{
	SoundID = 38;	// Invalid target selection
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef { Path = "media/SFX/Interface/Error.ogg"; };
	};
};

G3SoundObject
{
	SoundID = 39;	// Cancel current action
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef { Path = "media/SFX/Interface/Error.ogg"; };
	};
};

G3SoundObject
{
	SoundID = 40;	// Deselect actor
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef { Path = "media/SFX/Interface/Error.ogg"; };
	};
};

G3SoundObject
{
	SoundID = 41;	// you're dead Jim
	Category = 2; // ESoundInterface
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_Religion.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 42; // jingle when a War event starts
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_WarEvent.ogg";
		};
	};
};

G3SoundObject
{
	SoundID = 43; // jingle when a Guild event starts
	Category = 2; // ESoundInterface
	Volume = 0.8;
	Sounds = array
	{
		1 extends G3SoundDef
		{
			Path = "media/SFX/Interface/Jingle_GuildEvent.ogg";
		};
	};
};
