// Place all voice over sound definitions in here please.
// 1 - x

// CLICK
	
		G3SoundObject
		{
			SoundID = 1;	// Children
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.Child.0.ogg"; Subtitle = "$cf.Child.0"; Weight = 6;}; // sum all weights divided by Weight
				2 extends G3SoundDef { Path = "cf.Child.1.ogg"; Subtitle = "$cf.Child.1"; Weight = 6;};
				3 extends G3SoundDef { Path = "cf.Child.2.ogg"; Subtitle = "$cf.Child.2"; Weight = 6;};
				4 extends G3SoundDef { Path = "cf.Child.3.ogg"; Subtitle = "$cf.Child.3"; Weight = 6;};
				5 extends G3SoundDef { Path = "cf.Child.4.ogg"; Subtitle = "$cf.Child.4"; Weight = 6;};
				6 extends G3SoundDef { Path = "cf.Child.5.ogg"; Subtitle = "$cf.Child.5"; Weight = 6;};
				7 extends G3SoundDef { Path = "cf.Child.EE.0.ogg"; Subtitle = "$cf.Child.EE.0"; Weight = 1;}; // 1.58%
				8 extends G3SoundDef { Path = "cf.Child.EE.1.ogg"; Subtitle = "$cf.Child.EE.1"; Weight = 1;};
				9 extends G3SoundDef { Path = "cf.Child.Confirm.EE.0.ogg"; Subtitle = "$cf.Child.Confirm.EE.0"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 2;	// Liaison Low
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.Liaison.Low.0.ogg"; Subtitle = "$cf.Liaison.Low.0";};
				2 extends G3SoundDef { Path = "cf.Liaison.Low.1.ogg"; Subtitle = "$cf.Liaison.Low.1";};
				3 extends G3SoundDef { Path = "cf.Liaison.Low.2.ogg"; Subtitle = "$cf.Liaison.Low.2";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 3;	// Liaison Med
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.Liaison.Med.0.ogg"; Subtitle = "$cf.Liaison.Med.0";};
				2 extends G3SoundDef { Path = "cf.Liaison.Med.1.ogg"; Subtitle = "$cf.Liaison.Med.1";};
				3 extends G3SoundDef { Path = "cf.Liaison.Med.2.ogg"; Subtitle = "$cf.Liaison.Med.2";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 4;	// Liaison Love
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.Liaison.Love.0.ogg"; Subtitle = "$cf.Liaison.Love.0";};
				2 extends G3SoundDef { Path = "cf.Liaison.Love.1.ogg"; Subtitle = "$cf.Liaison.Love.1";};
				3 extends G3SoundDef { Path = "cf.Liaison.Love.2.ogg"; Subtitle = "$cf.Liaison.Love.2";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 5;	// Foreign Adult Ally
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.FAvatar.Allied.0.ogg"; Subtitle = "$cf.FAvatar.Allied.0";};
				2 extends G3SoundDef { Path = "cf.FAvatar.Allied.1.ogg"; Subtitle = "$cf.FAvatar.Allied.1";};
				3 extends G3SoundDef { Path = "cf.FAvatar.Allied.2.ogg"; Subtitle = "$cf.FAvatar.Allied.2";};
				4 extends G3SoundDef { Path = "cf.FAvatar.Allied.3.ogg"; Subtitle = "$cf.FAvatar.Allied.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 6;	// Foreign Adult Neutral
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.FAvatar.Normal.0.ogg"; Subtitle = "$cf.FAvatar.Normal.0";};
				2 extends G3SoundDef { Path = "cf.FAvatar.Normal.1.ogg"; Subtitle = "$cf.FAvatar.Normal.1";};
				3 extends G3SoundDef { Path = "cf.FAvatar.Normal.2.ogg"; Subtitle = "$cf.FAvatar.Normal.2";};
				4 extends G3SoundDef { Path = "cf.FAvatar.Normal.3.ogg"; Subtitle = "$cf.FAvatar.Normal.3";};
				5 extends G3SoundDef { Path = "cf.FAvatar.Normal.4.ogg"; Subtitle = "$cf.FAvatar.Normal.4";};
				6 extends G3SoundDef { Path = "cf.FAvatar.Normal.5.ogg"; Subtitle = "$cf.FAvatar.Normal.5";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 7;	// Foreign Adult Enemy
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.FAvatar.Enemy.0.ogg"; Subtitle = "$cf.FAvatar.Enemy.0";};
				2 extends G3SoundDef { Path = "cf.FAvatar.Enemy.1.ogg"; Subtitle = "$cf.FAvatar.Enemy.1";};
				3 extends G3SoundDef { Path = "cf.FAvatar.Enemy.2.ogg"; Subtitle = "$cf.FAvatar.Enemy.2";};
				4 extends G3SoundDef { Path = "cf.FAvatar.Enemy.3.ogg"; Subtitle = "$cf.FAvatar.Enemy.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 8;	// Foreign Employee Ally
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.FEmpl.Allied.0.ogg"; Subtitle = "$cf.FEmpl.Allied.0";};
				2 extends G3SoundDef { Path = "cf.FEmpl.Allied.1.ogg"; Subtitle = "$cf.FEmpl.Allied.1";};
				3 extends G3SoundDef { Path = "cf.FEmpl.Allied.2.ogg"; Subtitle = "$cf.FEmpl.Allied.2";};
				4 extends G3SoundDef { Path = "cf.FEmpl.Allied.3.ogg"; Subtitle = "$cf.FEmpl.Allied.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 9;	// Foreign Employee Neutral
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.FEmpl.Normal.0.ogg"; Subtitle = "$cf.FEmpl.Normal.0";};
				2 extends G3SoundDef { Path = "cf.FEmpl.Normal.1.ogg"; Subtitle = "$cf.FEmpl.Normal.1";};
				3 extends G3SoundDef { Path = "cf.FEmpl.Normal.2.ogg"; Subtitle = "$cf.FEmpl.Normal.2";};
				4 extends G3SoundDef { Path = "cf.FEmpl.Normal.3.ogg"; Subtitle = "$cf.FEmpl.Normal.3";};
				5 extends G3SoundDef { Path = "cf.FEmpl.Normal.4.ogg"; Subtitle = "$cf.FEmpl.Normal.4";};
				6 extends G3SoundDef { Path = "cf.FEmpl.Normal.5.ogg"; Subtitle = "$cf.FEmpl.Normal.5";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 10;	// Foreign Employee Enemy
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.FEmpl.Enemy.0.ogg"; Subtitle = "$cf.FEmpl.Enemy.0";};
				2 extends G3SoundDef { Path = "cf.FEmpl.Enemy.1.ogg"; Subtitle = "$cf.FEmpl.Enemy.1";};
				3 extends G3SoundDef { Path = "cf.FEmpl.Enemy.2.ogg"; Subtitle = "$cf.FEmpl.Enemy.2";};
				4 extends G3SoundDef { Path = "cf.FEmpl.Enemy.3.ogg"; Subtitle = "$cf.FEmpl.Enemy.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 11;	// Foreign Employee Ship
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.FTrans.Ship.2.ogg"; Subtitle = "$cf.FTrans.Ship.0";};
				2 extends G3SoundDef { Path = "cf.FTrans.Ship.3.ogg"; Subtitle = "$cf.FTrans.Ship.1";};
				3 extends G3SoundDef { Path = "cf.FTrans.Ship.2.ogg"; Subtitle = "$cf.FTrans.Ship.2";};
				4 extends G3SoundDef { Path = "cf.FTrans.Ship.3.ogg"; Subtitle = "$cf.FTrans.Ship.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 12;	// Own Adult Normal
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.Avatar.Normal.0.ogg"; Subtitle = "$cf.Avatar.Normal.0"; Weight = 10;};
				2 extends G3SoundDef { Path = "cf.Avatar.Normal.1.ogg"; Subtitle = "$cf.Avatar.Normal.1"; Weight = 10;};
				3 extends G3SoundDef { Path = "cf.Avatar.Normal.2.ogg"; Subtitle = "$cf.Avatar.Normal.2"; Weight = 10;};
				4 extends G3SoundDef { Path = "cf.Avatar.Normal.3.ogg"; Subtitle = "$cf.Avatar.Normal.3"; Weight = 10;};
				5 extends G3SoundDef { Path = "cf.Avatar.Normal.4.ogg"; Subtitle = "$cf.Avatar.Normal.4"; Weight = 10;};
				6 extends G3SoundDef { Path = "cf.Avatar.Normal.5.ogg"; Subtitle = "$cf.Avatar.Normal.5"; Weight = 10;};
				7 extends G3SoundDef { Path = "cf.Avatar.Normal.6.ogg"; Subtitle = "$cf.Avatar.Normal.6"; Weight = 10;};
				8 extends G3SoundDef { Path = "cf.Avatar.Normal.7.ogg"; Subtitle = "$cf.Avatar.Normal.7"; Weight = 10;};
				9 extends G3SoundDef { Path = "cf.Avatar.Normal.8.ogg"; Subtitle = "$cf.Avatar.Normal.8"; Weight = 10;};
				10 extends G3SoundDef { Path = "cf.Avatar.Normal.9.ogg"; Subtitle = "$cf.Avatar.Normal.9"; Weight = 10;};
				11 extends G3SoundDef { Path = "cf.OAdult.0.ogg"; Subtitle = "$cf.OAdult.0"; Weight = 10;};
				12 extends G3SoundDef { Path = "cf.OAdult.1.ogg"; Subtitle = "$cf.OAdult.1"; Weight = 10;};
				13 extends G3SoundDef { Path = "cf.OAdult.2.ogg"; Subtitle = "$cf.OAdult.2"; Weight = 10;};
				14 extends G3SoundDef { Path = "cf.OAdult.3.ogg"; Subtitle = "$cf.OAdult.3"; Weight = 10;};
				15 extends G3SoundDef { Path = "cf.OAdult.EE.0.ogg"; Subtitle = "$cf.OAdult.EE.0"; Weight = 1;};
				16 extends G3SoundDef { Path = "cf.OAdult.EE.1.ogg"; Subtitle = "$cf.OAdult.EE.1"; Weight = 1;};
				17 extends G3SoundDef { Path = "cf.Avatar.Normal.EE.0.ogg"; Subtitle = "$cf.Avatar.Normal.EE.0"; Weight = 1;};
				18 extends G3SoundDef { Path = "cf.Avatar.Normal.EE.1.ogg"; Subtitle = "$cf.Avatar.Normal.EE.1"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 13;	// Own Adult Busy
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.Avatar.Blocked.0.ogg"; Subtitle = "$cf.Avatar.Blocked.0"; Weight = 6;};
				2 extends G3SoundDef { Path = "cf.Avatar.Blocked.1.ogg"; Subtitle = "$cf.Avatar.Blocked.1"; Weight = 6;};
				3 extends G3SoundDef { Path = "cf.Avatar.Busy.0.ogg"; Subtitle = "$cf.Avatar.Busy.0"; Weight = 6;};
				4 extends G3SoundDef { Path = "cf.Avatar.Busy.1.ogg"; Subtitle = "$cf.Avatar.Busy.1"; Weight = 6;};
				5 extends G3SoundDef { Path = "cf.Avatar.Busy.2.ogg"; Subtitle = "$cf.Avatar.Busy.2"; Weight = 6;};
				6 extends G3SoundDef { Path = "cf.Avatar.Busy.3.ogg"; Subtitle = "$cf.Avatar.Busy.3"; Weight = 6;};
				7 extends G3SoundDef { Path = "cf.Avatar.Busy.EE.0.ogg"; Subtitle = "$cf.Avatar.Busy.EE.0"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 14;	// Own Adult Groggy
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.Avatar.Groggy.0.ogg"; Subtitle = "$cf.Avatar.Groggy.0";};
				2 extends G3SoundDef { Path = "cf.Avatar.Groggy.1.ogg"; Subtitle = "$cf.Avatar.Groggy.1";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 15;	// Own Employee Transport
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OTrans.0.ogg"; Subtitle = "$cf.OTrans.0"; Weight = 12;};
				2 extends G3SoundDef { Path = "cf.OTrans.1.ogg"; Subtitle = "$cf.OTrans.1"; Weight = 12;};
				3 extends G3SoundDef { Path = "cf.OTrans.2.ogg"; Subtitle = "$cf.OTrans.2"; Weight = 12;};
				4 extends G3SoundDef { Path = "cf.OTrans.3.ogg"; Subtitle = "$cf.OTrans.3"; Weight = 12;};
				5 extends G3SoundDef { Path = "cf.OTrans.4.ogg"; Subtitle = "$cf.OTrans.4"; Weight = 12;};
				6 extends G3SoundDef { Path = "cf.OTrans.5.ogg"; Subtitle = "$cf.OTrans.5"; Weight = 12;};
				7 extends G3SoundDef { Path = "cf.OTrans.6.ogg"; Subtitle = "$cf.OTrans.6"; Weight = 12;};
				8 extends G3SoundDef { Path = "cf.OTrans.7.ogg"; Subtitle = "$cf.OTrans.7"; Weight = 12;};
				9 extends G3SoundDef { Path = "cf.OTrans.EE.0.ogg"; Subtitle = "$cf.OTrans.EE.0"; Weight = 1;};
				10 extends G3SoundDef { Path = "cf.OTrans.EE.1.ogg"; Subtitle = "$cf.OTrans.EE.1"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 16;	// Own Employee Cart
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OTrans.Cart.0.ogg"; Subtitle = "$cf.OTrans.Cart.0";};
				2 extends G3SoundDef { Path = "cf.OTrans.Cart.1.ogg"; Subtitle = "$cf.OTrans.Cart.1";};
				3 extends G3SoundDef { Path = "cf.OTrans.Cart.2.ogg"; Subtitle = "$cf.OTrans.Cart.2";};
				4 extends G3SoundDef { Path = "cf.OTrans.Cart.3.ogg"; Subtitle = "$cf.OTrans.Cart.3";};
				5 extends G3SoundDef { Path = "cf.OTrans.Cart.4.ogg"; Subtitle = "$cf.OTrans.Cart.4";};
				6 extends G3SoundDef { Path = "cf.OTrans.Cart.5.ogg"; Subtitle = "$cf.OTrans.Cart.5";};
				7 extends G3SoundDef { Path = "cf.OTrans.Cart.6.ogg"; Subtitle = "$cf.OTrans.Cart.6";};
				8 extends G3SoundDef { Path = "cf.OTrans.Cart.7.ogg"; Subtitle = "$cf.OTrans.Cart.7";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 17;	// Own Employee Ship
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OTrans.Ship.2.ogg"; Subtitle = "$cf.OTrans.Ship.0";};
				2 extends G3SoundDef { Path = "cf.OTrans.Ship.3.ogg"; Subtitle = "$cf.OTrans.Ship.1";};
				3 extends G3SoundDef { Path = "cf.OTrans.Ship.2.ogg"; Subtitle = "$cf.OTrans.Ship.2";};
				4 extends G3SoundDef { Path = "cf.OTrans.Ship.3.ogg"; Subtitle = "$cf.OTrans.Ship.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 18;	// Own Employee Normal
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OEmpl.0.ogg"; Subtitle = "$cf.OEmpl.0"; Weight = 16;};
				2 extends G3SoundDef { Path = "cf.OEmpl.1.ogg"; Subtitle = "$cf.OEmpl.1"; Weight = 16;};
				3 extends G3SoundDef { Path = "cf.OEmpl.2.ogg"; Subtitle = "$cf.OEmpl.2"; Weight = 16;};
				4 extends G3SoundDef { Path = "cf.OEmpl.3.ogg"; Subtitle = "$cf.OEmpl.3"; Weight = 16;};
				5 extends G3SoundDef { Path = "cf.OEmpl.4.ogg"; Subtitle = "$cf.OEmpl.4"; Weight = 16;};
				6 extends G3SoundDef { Path = "cf.OEmpl.5.ogg"; Subtitle = "$cf.OEmpl.5"; Weight = 16;};
				7 extends G3SoundDef { Path = "cf.OEmpl.EE.0.ogg"; Subtitle = "$cf.OEmpl.EE.0"; Weight = 1;};
				8 extends G3SoundDef { Path = "cf.OEmpl.EE.1.ogg"; Subtitle = "$cf.OEmpl.EE.1"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 19;	// Own Employee Culinary
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OEmpl.Culi.0.ogg"; Subtitle = "$cf.OEmpl.Culi.0"; Weight = 16;};
				2 extends G3SoundDef { Path = "cf.OEmpl.Culi.1.ogg"; Subtitle = "$cf.OEmpl.Culi.1"; Weight = 16;};
				3 extends G3SoundDef { Path = "cf.OEmpl.Culi.2.ogg"; Subtitle = "$cf.OEmpl.Culi.2"; Weight = 16;};
				4 extends G3SoundDef { Path = "cf.OEmpl.Culi.3.ogg"; Subtitle = "$cf.OEmpl.Culi.3"; Weight = 16;};
				5 extends G3SoundDef { Path = "cf.OEmpl.Culi.4.ogg"; Subtitle = "$cf.OEmpl.Culi.4"; Weight = 16;};
				6 extends G3SoundDef { Path = "cf.OEmpl.Culi.5.ogg"; Subtitle = "$cf.OEmpl.Culi.5"; Weight = 16;};
				7 extends G3SoundDef { Path = "cf.OEmpl.Culi.EE.0.ogg"; Subtitle = "$cf.OEmpl.Culi.EE.0"; Weight = 1;};
				8 extends G3SoundDef { Path = "cf.OEmpl.Culi.EE.1.ogg"; Subtitle = "$cf.OEmpl.Culi.EE.1"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 20;	// Own Employee Handcraft
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OEmpl.Hand.0.ogg"; Subtitle = "$cf.OEmpl.Hand.0"; Weight = 16;};
				2 extends G3SoundDef { Path = "cf.OEmpl.Hand.1.ogg"; Subtitle = "$cf.OEmpl.Hand.1"; Weight = 16;};
				3 extends G3SoundDef { Path = "cf.OEmpl.Hand.2.ogg"; Subtitle = "$cf.OEmpl.Hand.2"; Weight = 16;};
				4 extends G3SoundDef { Path = "cf.OEmpl.Hand.3.ogg"; Subtitle = "$cf.OEmpl.Hand.3"; Weight = 16;};
				5 extends G3SoundDef { Path = "cf.OEmpl.Hand.4.ogg"; Subtitle = "$cf.OEmpl.Hand.4"; Weight = 16;};
				6 extends G3SoundDef { Path = "cf.OEmpl.Hand.5.ogg"; Subtitle = "$cf.OEmpl.Hand.5"; Weight = 16;};
				7 extends G3SoundDef { Path = "cf.OEmpl.Hand.EE.0.ogg"; Subtitle = "$cf.OEmpl.Hand.EE.0"; Weight = 1;};
				8 extends G3SoundDef { Path = "cf.OEmpl.Hand.EE.1.ogg"; Subtitle = "$cf.OEmpl.Hand.EE.1"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 21;	// Own Employee Herbalism
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OEmpl.Herb.0.ogg"; Subtitle = "$cf.OEmpl.Herb.0"; Weight = 16;};
				2 extends G3SoundDef { Path = "cf.OEmpl.Herb.1.ogg"; Subtitle = "$cf.OEmpl.Herb.1"; Weight = 16;};
				3 extends G3SoundDef { Path = "cf.OEmpl.Herb.2.ogg"; Subtitle = "$cf.OEmpl.Herb.2"; Weight = 16;};
				4 extends G3SoundDef { Path = "cf.OEmpl.Herb.3.ogg"; Subtitle = "$cf.OEmpl.Herb.3"; Weight = 16;};
				5 extends G3SoundDef { Path = "cf.OEmpl.Herb.4.ogg"; Subtitle = "$cf.OEmpl.Herb.4"; Weight = 16;};
				6 extends G3SoundDef { Path = "cf.OEmpl.Herb.5.ogg"; Subtitle = "$cf.OEmpl.Herb.5"; Weight = 16;};
				7 extends G3SoundDef { Path = "cf.OEmpl.Herb.EE.0.ogg"; Subtitle = "$cf.OEmpl.Herb.EE.0"; Weight = 1;};
				8 extends G3SoundDef { Path = "cf.OEmpl.Herb.EE.1.ogg"; Subtitle = "$cf.OEmpl.Herb.EE.1"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 22;	// Own Employee Henchmen
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OEmpl.HM.0.ogg"; Subtitle = "$cf.OEmpl.HM.0"; Weight = 16;};
				2 extends G3SoundDef { Path = "cf.OEmpl.HM.1.ogg"; Subtitle = "$cf.OEmpl.HM.1"; Weight = 16;};
				3 extends G3SoundDef { Path = "cf.OEmpl.HM.2.ogg"; Subtitle = "$cf.OEmpl.HM.2"; Weight = 16;};
				4 extends G3SoundDef { Path = "cf.OEmpl.HM.3.ogg"; Subtitle = "$cf.OEmpl.HM.3"; Weight = 16;};
				5 extends G3SoundDef { Path = "cf.OEmpl.HM.4.ogg"; Subtitle = "$cf.OEmpl.HM.4"; Weight = 16;};
				6 extends G3SoundDef { Path = "cf.OEmpl.HM.5.ogg"; Subtitle = "$cf.OEmpl.HM.5"; Weight = 16;};
				7 extends G3SoundDef { Path = "cf.OEmpl.HM.EE.0.ogg"; Subtitle = "$cf.OEmpl.HM.EE.0"; Weight = 1;};
				8 extends G3SoundDef { Path = "cf.OEmpl.HM.EE.1.ogg"; Subtitle = "$cf.OEmpl.HM.EE.1"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 23;	// Own Employee Rogue
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OEmpl.Rogue.0.ogg"; Subtitle = "$cf.OEmpl.Rogue.0"; Weight = 16;};
				2 extends G3SoundDef { Path = "cf.OEmpl.Rogue.1.ogg"; Subtitle = "$cf.OEmpl.Rogue.1"; Weight = 16;};
				3 extends G3SoundDef { Path = "cf.OEmpl.Rogue.2.ogg"; Subtitle = "$cf.OEmpl.Rogue.2"; Weight = 16;};
				4 extends G3SoundDef { Path = "cf.OEmpl.Rogue.3.ogg"; Subtitle = "$cf.OEmpl.Rogue.3"; Weight = 16;};
				5 extends G3SoundDef { Path = "cf.OEmpl.Rogue.4.ogg"; Subtitle = "$cf.OEmpl.Rogue.4"; Weight = 16;};
				6 extends G3SoundDef { Path = "cf.OEmpl.Rogue.5.ogg"; Subtitle = "$cf.OEmpl.Rogue.5"; Weight = 16;};
				7 extends G3SoundDef { Path = "cf.OEmpl.Rogue.EE.0.ogg"; Subtitle = "$cf.OEmpl.Rogue.EE.0"; Weight = 1;};
				8 extends G3SoundDef { Path = "cf.OEmpl.Rogue.EE.1.ogg"; Subtitle = "$cf.OEmpl.Rogue.EE.1"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 24;	// NPC ToCommoner Guard
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.NPC.ToCommoner.CityGuard.0.ogg"; Subtitle = "$cf.NPC.ToCommoner.CityGuard.0";};
				2 extends G3SoundDef { Path = "cf.NPC.ToCommoner.CityGuard.1.ogg"; Subtitle = "$cf.NPC.ToCommoner.CityGuard.1";};
				3 extends G3SoundDef { Path = "cf.NPC.ToCommoner.CityGuard.2.ogg"; Subtitle = "$cf.NPC.ToCommoner.CityGuard.2";};
				4 extends G3SoundDef { Path = "cf.NPC.ToCommoner.CityGuard.3.ogg"; Subtitle = "$cf.NPC.ToCommoner.CityGuard.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 25;	// NPC ToCommoner Friendly
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Friendly.0.ogg"; Subtitle = "$cf.NPC.ToCommoner.Friendly.0";};
				2 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Friendly.1.ogg"; Subtitle = "$cf.NPC.ToCommoner.Friendly.1";};
				3 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Friendly.2.ogg"; Subtitle = "$cf.NPC.ToCommoner.Friendly.2";};
				4 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Friendly.3.ogg"; Subtitle = "$cf.NPC.ToCommoner.Friendly.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 26;	// NPC ToCommoner Normal
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Normal.0.ogg"; Subtitle = "$cf.NPC.ToCommoner.Normal.0";};
				2 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Normal.1.ogg"; Subtitle = "$cf.NPC.ToCommoner.Normal.1";};
				3 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Normal.2.ogg"; Subtitle = "$cf.NPC.ToCommoner.Normal.2";};
				4 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Normal.3.ogg"; Subtitle = "$cf.NPC.ToCommoner.Normal.3";};
				5 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Normal.4.ogg"; Subtitle = "$cf.NPC.ToCommoner.Normal.4";};
				6 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Normal.5.ogg"; Subtitle = "$cf.NPC.ToCommoner.Normal.5";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 27;	// NPC ToCommoner Hatred
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Hatred.0.ogg"; Subtitle = "$cf.NPC.ToCommoner.Hatred.0";};
				2 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Hatred.1.ogg"; Subtitle = "$cf.NPC.ToCommoner.Hatred.1";};
				3 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Hatred.2.ogg"; Subtitle = "$cf.NPC.ToCommoner.Hatred.2";};
				4 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Hatred.3.ogg"; Subtitle = "$cf.NPC.ToCommoner.Hatred.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 28;	// NPC ToCitizen Guard
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.NPC.ToCitizen.CityGuard.0.ogg"; Subtitle = "$cf.NPC.ToCitizen.CityGuard.0";};
				2 extends G3SoundDef { Path = "cf.NPC.ToCitizen.CityGuard.1.ogg"; Subtitle = "$cf.NPC.ToCitizen.CityGuard.1";};
				3 extends G3SoundDef { Path = "cf.NPC.ToCitizen.CityGuard.2.ogg"; Subtitle = "$cf.NPC.ToCitizen.CityGuard.2";};
				4 extends G3SoundDef { Path = "cf.NPC.ToCitizen.CityGuard.3.ogg"; Subtitle = "$cf.NPC.ToCitizen.CityGuard.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 29;	// NPC ToCitizen Friendly
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Friendly.0.ogg"; Subtitle = "$cf.NPC.ToCitizen.Friendly.0";};
				2 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Friendly.1.ogg"; Subtitle = "$cf.NPC.ToCitizen.Friendly.1";};
				3 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Friendly.2.ogg"; Subtitle = "$cf.NPC.ToCitizen.Friendly.2";};
				4 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Friendly.3.ogg"; Subtitle = "$cf.NPC.ToCitizen.Friendly.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 30;	// NPC ToCitizen Normal
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Normal.0.ogg"; Subtitle = "$cf.NPC.ToCitizen.Normal.0";};
				2 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Normal.1.ogg"; Subtitle = "$cf.NPC.ToCitizen.Normal.1";};
				3 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Normal.2.ogg"; Subtitle = "$cf.NPC.ToCitizen.Normal.2";};
				4 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Normal.3.ogg"; Subtitle = "$cf.NPC.ToCitizen.Normal.3";};
				5 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Normal.4.ogg"; Subtitle = "$cf.NPC.ToCitizen.Normal.4";};
				6 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Normal.5.ogg"; Subtitle = "$cf.NPC.ToCitizen.Normal.5";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 31;	// NPC ToCitizen Hatred
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Hatred.0.ogg"; Subtitle = "$cf.NPC.ToCitizen.Hatred.0";};
				2 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Hatred.1.ogg"; Subtitle = "$cf.NPC.ToCitizen.Hatred.1";};
				3 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Hatred.2.ogg"; Subtitle = "$cf.NPC.ToCitizen.Hatred.2";};
				4 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Hatred.3.ogg"; Subtitle = "$cf.NPC.ToCitizen.Hatred.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 32;	// NPC ToNoble Guard
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.NPC.ToNoble.CityGuard.0.ogg"; Subtitle = "$cf.NPC.ToNoble.CityGuard.0";};
				2 extends G3SoundDef { Path = "cf.NPC.ToNoble.CityGuard.1.ogg"; Subtitle = "$cf.NPC.ToNoble.CityGuard.1";};
				3 extends G3SoundDef { Path = "cf.NPC.ToNoble.CityGuard.2.ogg"; Subtitle = "$cf.NPC.ToNoble.CityGuard.2";};
				4 extends G3SoundDef { Path = "cf.NPC.ToNoble.CityGuard.3.ogg"; Subtitle = "$cf.NPC.ToNoble.CityGuard.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 33;	// NPC ToNoble Friendly
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.NPC.ToNoble.Friendly.0.ogg"; Subtitle = "$cf.NPC.ToNoble.Friendly.0";};
				2 extends G3SoundDef { Path = "cf.NPC.ToNoble.Friendly.1.ogg"; Subtitle = "$cf.NPC.ToNoble.Friendly.1";};
				3 extends G3SoundDef { Path = "cf.NPC.ToNoble.Friendly.2.ogg"; Subtitle = "$cf.NPC.ToNoble.Friendly.2";};
				4 extends G3SoundDef { Path = "cf.NPC.ToNoble.Friendly.3.ogg"; Subtitle = "$cf.NPC.ToNoble.Friendly.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 34;	// NPC ToNoble Normal
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.NPC.ToNoble.Normal.0.ogg"; Subtitle = "$cf.NPC.ToNoble.Normal.0";};
				2 extends G3SoundDef { Path = "cf.NPC.ToNoble.Normal.1.ogg"; Subtitle = "$cf.NPC.ToNoble.Normal.1";};
				3 extends G3SoundDef { Path = "cf.NPC.ToNoble.Normal.2.ogg"; Subtitle = "$cf.NPC.ToNoble.Normal.2";};
				4 extends G3SoundDef { Path = "cf.NPC.ToNoble.Normal.3.ogg"; Subtitle = "$cf.NPC.ToNoble.Normal.3";};
				5 extends G3SoundDef { Path = "cf.NPC.ToNoble.Normal.4.ogg"; Subtitle = "$cf.NPC.ToNoble.Normal.4";};
				6 extends G3SoundDef { Path = "cf.NPC.ToNoble.Normal.5.ogg"; Subtitle = "$cf.NPC.ToNoble.Normal.5";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 35;	// NPC ToNoble Hatred
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.NPC.ToNoble.Hatred.0.ogg"; Subtitle = "$cf.NPC.ToNoble.Hatred.0";};
				2 extends G3SoundDef { Path = "cf.NPC.ToNoble.Hatred.1.ogg"; Subtitle = "$cf.NPC.ToNoble.Hatred.1";};
				3 extends G3SoundDef { Path = "cf.NPC.ToNoble.Hatred.2.ogg"; Subtitle = "$cf.NPC.ToNoble.Hatred.2";};
				4 extends G3SoundDef { Path = "cf.NPC.ToNoble.Hatred.3.ogg"; Subtitle = "$cf.NPC.ToNoble.Hatred.3";};
			};
		};

// Confirm

		G3SoundObject
		{
			SoundID = 36;	// CONFIRM - Own Adult Normal
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.Avatar.Confirm.0.ogg"; Subtitle = "$cf.Avatar.Confirm.0"; Weight = 12;};
				2 extends G3SoundDef { Path = "cf.Avatar.Confirm.1.ogg"; Subtitle = "$cf.Avatar.Confirm.1"; Weight = 12;};
				3 extends G3SoundDef { Path = "cf.Avatar.Confirm.2.ogg"; Subtitle = "$cf.Avatar.Confirm.2"; Weight = 12;};
				4 extends G3SoundDef { Path = "cf.Avatar.Confirm.3.ogg"; Subtitle = "$cf.Avatar.Confirm.3"; Weight = 12;};
				5 extends G3SoundDef { Path = "cf.Avatar.Confirm.4.ogg"; Subtitle = "$cf.Avatar.Confirm.4"; Weight = 12;};
				6 extends G3SoundDef { Path = "cf.Avatar.Confirm.5.ogg"; Subtitle = "$cf.Avatar.Confirm.5"; Weight = 12;};
				7 extends G3SoundDef { Path = "cf.Avatar.Confirm.6.ogg"; Subtitle = "$cf.Avatar.Confirm.6"; Weight = 12;};
				8 extends G3SoundDef { Path = "cf.Avatar.Confirm.7.ogg"; Subtitle = "$cf.Avatar.Confirm.7"; Weight = 12;};
				9 extends G3SoundDef { Path = "cf.Avatar.Confirm.EE.0.ogg"; Subtitle = "$cf.Avatar.Confirm.EE.0"; Weight = 1;};
				10 extends G3SoundDef { Path = "cf.Avatar.Confirm.EE.1.ogg"; Subtitle = "$cf.Avatar.Confirm.EE.1"; Weight = 1;};
				11 extends G3SoundDef { Path = "cf.Avatar.Confirm.EE.2.ogg"; Subtitle = "$cf.Avatar.Confirm.EE.2"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 37;	// CONFIRM - Own Employee Transport
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OTrans.Confirm.0.ogg"; Subtitle = "$cf.OTrans.Confirm.0"; Weight = 12;};
				2 extends G3SoundDef { Path = "cf.OTrans.Confirm.1.ogg"; Subtitle = "$cf.OTrans.Confirm.1"; Weight = 12;};
				3 extends G3SoundDef { Path = "cf.OTrans.Confirm.2.ogg"; Subtitle = "$cf.OTrans.Confirm.2"; Weight = 12;};
				4 extends G3SoundDef { Path = "cf.OTrans.Confirm.3.ogg"; Subtitle = "$cf.OTrans.Confirm.3"; Weight = 12;};
				5 extends G3SoundDef { Path = "cf.OTrans.Confirm.4.ogg"; Subtitle = "$cf.OTrans.Confirm.4"; Weight = 12;};
				6 extends G3SoundDef { Path = "cf.OTrans.Confirm.5.ogg"; Subtitle = "$cf.OTrans.Confirm.5"; Weight = 12;};
				7 extends G3SoundDef { Path = "cf.OTrans.Confirm.6.ogg"; Subtitle = "$cf.OTrans.Confirm.6"; Weight = 12;};
				8 extends G3SoundDef { Path = "cf.OTrans.Confirm.7.ogg"; Subtitle = "$cf.OTrans.Confirm.7"; Weight = 12;};
				9 extends G3SoundDef { Path = "cf.OTrans.Confirm.EE.0.ogg"; Subtitle = "$cf.OTrans.Confirm.EE.0"; Weight = 1;};
				10 extends G3SoundDef { Path = "cf.OTrans.Confirm.EE.1.ogg"; Subtitle = "$cf.OTrans.Confirm.EE.1"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 38;	// CONFIRM - Own Employee Cart
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OTrans.Cart.Confirm.0.ogg"; Subtitle = "$cf.OTrans.Cart.Confirm.0";};
				2 extends G3SoundDef { Path = "cf.OTrans.Cart.Confirm.1.ogg"; Subtitle = "$cf.OTrans.Cart.Confirm.1";};
				3 extends G3SoundDef { Path = "cf.OTrans.Cart.Confirm.2.ogg"; Subtitle = "$cf.OTrans.Cart.Confirm.2";};
				4 extends G3SoundDef { Path = "cf.OTrans.Cart.Confirm.3.ogg"; Subtitle = "$cf.OTrans.Cart.Confirm.3";};
				5 extends G3SoundDef { Path = "cf.OTrans.Cart.Confirm.4.ogg"; Subtitle = "$cf.OTrans.Cart.Confirm.4";};
				6 extends G3SoundDef { Path = "cf.OTrans.Cart.Confirm.5.ogg"; Subtitle = "$cf.OTrans.Cart.Confirm.5";};
				7 extends G3SoundDef { Path = "cf.OTrans.Cart.Confirm.6.ogg"; Subtitle = "$cf.OTrans.Cart.Confirm.6";};
				8 extends G3SoundDef { Path = "cf.OTrans.Cart.Confirm.7.ogg"; Subtitle = "$cf.OTrans.Cart.Confirm.7";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 39;	// CONFIRM - Own Employee Ship
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OTrans.Ship.Confirm.0.ogg"; Subtitle = "$cf.OTrans.Ship.Confirm.0";};
				2 extends G3SoundDef { Path = "cf.OTrans.Ship.Confirm.1.ogg"; Subtitle = "$cf.OTrans.Ship.Confirm.1";};
				3 extends G3SoundDef { Path = "cf.OTrans.Ship.Confirm.2.ogg"; Subtitle = "$cf.OTrans.Ship.Confirm.2";};
				4 extends G3SoundDef { Path = "cf.OTrans.Ship.Confirm.3.ogg"; Subtitle = "$cf.OTrans.Ship.Confirm.3";};
			};
		};
		
		G3SoundObject
		{
			SoundID = 40;	// CONFIRM - Own Employee Normal
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OEmpl.Confirm.0.ogg"; Subtitle = "$cf.OEmpl.Confirm.0"; Weight = 8;};
				2 extends G3SoundDef { Path = "cf.OEmpl.Confirm.1.ogg"; Subtitle = "$cf.OEmpl.Confirm.1"; Weight = 8;};
				3 extends G3SoundDef { Path = "cf.OEmpl.Confirm.2.ogg"; Subtitle = "$cf.OEmpl.Confirm.2"; Weight = 8;};
				4 extends G3SoundDef { Path = "cf.OEmpl.Confirm.3.ogg"; Subtitle = "$cf.OEmpl.Confirm.3"; Weight = 8;};
				5 extends G3SoundDef { Path = "cf.OEmpl.Confirm.4.ogg"; Subtitle = "$cf.OEmpl.Confirm.4"; Weight = 8;};
				6 extends G3SoundDef { Path = "cf.OEmpl.Confirm.5.ogg"; Subtitle = "$cf.OEmpl.Confirm.5"; Weight = 8;};
				7 extends G3SoundDef { Path = "cf.OEmpl.Confirm.EE.0.ogg"; Subtitle = "$cf.OEmpl.Confirm.EE.0"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 41;	// CONFIRM - Own Employee Culinary
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OEmpl.Culi.Confirm.0.ogg"; Subtitle = "$cf.OEmpl.Culi.Confirm.0"; Weight = 8;};
				2 extends G3SoundDef { Path = "cf.OEmpl.Culi.Confirm.1.ogg"; Subtitle = "$cf.OEmpl.Culi.Confirm.1"; Weight = 8;};
				3 extends G3SoundDef { Path = "cf.OEmpl.Culi.Confirm.2.ogg"; Subtitle = "$cf.OEmpl.Culi.Confirm.2"; Weight = 8;};
				4 extends G3SoundDef { Path = "cf.OEmpl.Culi.Confirm.3.ogg"; Subtitle = "$cf.OEmpl.Culi.Confirm.3"; Weight = 8;};
				5 extends G3SoundDef { Path = "cf.OEmpl.Culi.Confirm.4.ogg"; Subtitle = "$cf.OEmpl.Culi.Confirm.4"; Weight = 8;};
				6 extends G3SoundDef { Path = "cf.OEmpl.Culi.Confirm.5.ogg"; Subtitle = "$cf.OEmpl.Culi.Confirm.5"; Weight = 8;};
				7 extends G3SoundDef { Path = "cf.OEmpl.Culi.Confirm.EE.0.ogg"; Subtitle = "$cf.OEmpl.Culi.Confirm.EE.0"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 42;	// CONFIRM - Own Employee Handcraft
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OEmpl.Hand.Confirm.0.ogg"; Subtitle = "$cf.OEmpl.Hand.Confirm.0"; Weight = 8;};
				2 extends G3SoundDef { Path = "cf.OEmpl.Hand.Confirm.1.ogg"; Subtitle = "$cf.OEmpl.Hand.Confirm.1"; Weight = 8;};
				3 extends G3SoundDef { Path = "cf.OEmpl.Hand.Confirm.2.ogg"; Subtitle = "$cf.OEmpl.Hand.Confirm.2"; Weight = 8;};
				4 extends G3SoundDef { Path = "cf.OEmpl.Hand.Confirm.3.ogg"; Subtitle = "$cf.OEmpl.Hand.Confirm.3"; Weight = 8;};
				5 extends G3SoundDef { Path = "cf.OEmpl.Hand.Confirm.4.ogg"; Subtitle = "$cf.OEmpl.Hand.Confirm.4"; Weight = 8;};
				6 extends G3SoundDef { Path = "cf.OEmpl.Hand.Confirm.5.ogg"; Subtitle = "$cf.OEmpl.Hand.Confirm.5"; Weight = 8;};
				7 extends G3SoundDef { Path = "cf.OEmpl.Hand.Confirm.EE.0.ogg"; Subtitle = "$cf.OEmpl.Hand.Confirm.EE.0"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 43;	// CONFIRM - Own Employee Herbalism
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OEmpl.Herb.Confirm.0.ogg"; Subtitle = "$cf.OEmpl.Herb.Confirm.0"; Weight = 8;};
				2 extends G3SoundDef { Path = "cf.OEmpl.Herb.Confirm.1.ogg"; Subtitle = "$cf.OEmpl.Herb.Confirm.1"; Weight = 8;};
				3 extends G3SoundDef { Path = "cf.OEmpl.Herb.Confirm.2.ogg"; Subtitle = "$cf.OEmpl.Herb.Confirm.2"; Weight = 8;};
				4 extends G3SoundDef { Path = "cf.OEmpl.Herb.Confirm.3.ogg"; Subtitle = "$cf.OEmpl.Herb.Confirm.3"; Weight = 8;};
				5 extends G3SoundDef { Path = "cf.OEmpl.Herb.Confirm.4.ogg"; Subtitle = "$cf.OEmpl.Herb.Confirm.4"; Weight = 8;};
				6 extends G3SoundDef { Path = "cf.OEmpl.Herb.Confirm.5.ogg"; Subtitle = "$cf.OEmpl.Herb.Confirm.5"; Weight = 8;};
				7 extends G3SoundDef { Path = "cf.OEmpl.Herb.Confirm.EE.0.ogg"; Subtitle = "$cf.OEmpl.Herb.Confirm.EE.0"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 44;	// CONFIRM - Own Employee Henchmen
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OEmpl.HM.Confirm.0.ogg"; Subtitle = "$cf.OEmpl.HM.Confirm.0"; Weight = 8;};
				2 extends G3SoundDef { Path = "cf.OEmpl.HM.Confirm.1.ogg"; Subtitle = "$cf.OEmpl.HM.Confirm.1"; Weight = 8;};
				3 extends G3SoundDef { Path = "cf.OEmpl.HM.Confirm.2.ogg"; Subtitle = "$cf.OEmpl.HM.Confirm.2"; Weight = 8;};
				4 extends G3SoundDef { Path = "cf.OEmpl.HM.Confirm.3.ogg"; Subtitle = "$cf.OEmpl.HM.Confirm.3"; Weight = 8;};
				5 extends G3SoundDef { Path = "cf.OEmpl.HM.Confirm.4.ogg"; Subtitle = "$cf.OEmpl.HM.Confirm.4"; Weight = 8;};
				6 extends G3SoundDef { Path = "cf.OEmpl.HM.Confirm.5.ogg"; Subtitle = "$cf.OEmpl.HM.Confirm.5"; Weight = 8;};
				7 extends G3SoundDef { Path = "cf.OEmpl.HM.Confirm.EE.0.ogg"; Subtitle = "$cf.OEmpl.HM.Confirm.EE.0"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 45;	// CONFIRM - Own Employee Rogue
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.OEmpl.Rogue.Confirm.0.ogg"; Subtitle = "$cf.OEmpl.Rogue.Confirm.0"; Weight = 8;};
				2 extends G3SoundDef { Path = "cf.OEmpl.Rogue.Confirm.1.ogg"; Subtitle = "$cf.OEmpl.Rogue.Confirm.1"; Weight = 8;};
				3 extends G3SoundDef { Path = "cf.OEmpl.Rogue.Confirm.2.ogg"; Subtitle = "$cf.OEmpl.Rogue.Confirm.2"; Weight = 8;};
				4 extends G3SoundDef { Path = "cf.OEmpl.Rogue.Confirm.3.ogg"; Subtitle = "$cf.OEmpl.Rogue.Confirm.3"; Weight = 8;};
				5 extends G3SoundDef { Path = "cf.OEmpl.Rogue.Confirm.4.ogg"; Subtitle = "$cf.OEmpl.Rogue.Confirm.4"; Weight = 8;};
				6 extends G3SoundDef { Path = "cf.OEmpl.Rogue.Confirm.5.ogg"; Subtitle = "$cf.OEmpl.Rogue.Confirm.5"; Weight = 8;};
				7 extends G3SoundDef { Path = "cf.OEmpl.Rogue.Confirm.EE.0.ogg"; Subtitle = "$cf.OEmpl.Rogue.Confirm.EE.0"; Weight = 1;};
			};
		};
		
		G3SoundObject
		{
			SoundID = 46;	// CONFIRM - Own Child
			Category = 5; // ESoundVoices
			Sounds = array
			{
				1 extends G3SoundDef { Path = "cf.Child.Confirm.0.ogg"; Subtitle = "$cf.Child.Confirm.0";};
				2 extends G3SoundDef { Path = "cf.Child.Confirm.1.ogg"; Subtitle = "$cf.Child.Confirm.1";};
			};
		};

// ATTACK

		
G3SoundObject
{
	SoundID = 47;	// ATTACK CONFIRM - Own Adult
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cf.Attack.Confirm.0.ogg"; Subtitle = "$cf.Attack.Confirm.0";};
		2 extends G3SoundDef { Path = "cf.Attack.Confirm.1.ogg"; Subtitle = "$cf.Attack.Confirm.1";};
		3 extends G3SoundDef { Path = "cf.Attack.Confirm.2.ogg"; Subtitle = "$cf.Attack.Confirm.2";};
		4 extends G3SoundDef { Path = "cf.Attack.Confirm.3.ogg"; Subtitle = "$cf.Attack.Confirm.3";};
		5 extends G3SoundDef { Path = "cf.Attack.Confirm.4.ogg"; Subtitle = "$cf.Attack.Confirm.4";};
		6 extends G3SoundDef { Path = "cf.Attack.Confirm.5.ogg"; Subtitle = "$cf.Attack.Confirm.5";};
	};
};

// ACTIONS

G3SoundObject
{
	SoundID = 48;	// ACTION - COMMEND
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.Commend.0.narration.ogg"; Subtitle = "$int.Commend.0.narration";};
		2 extends G3SoundDef { Path = "int.Commend.1.narration.ogg"; Subtitle = "$int.Commend.1.narration";};
		3 extends G3SoundDef { Path = "int.Commend.2.narration.ogg"; Subtitle = "$int.Commend.2.narration";};
		4 extends G3SoundDef { Path = "int.Commend.3.narration.ogg"; Subtitle = "$int.Commend.3.narration";};
		5 extends G3SoundDef { Path = "int.Commend.4.narration.ogg"; Subtitle = "$int.Commend.4.narration";};
		6 extends G3SoundDef { Path = "int.Commend.5.narration.ogg"; Subtitle = "$int.Commend.5.narration";};
		7 extends G3SoundDef { Path = "int.Commend.6.narration.ogg"; Subtitle = "$int.Commend.6.narration";};
		8 extends G3SoundDef { Path = "int.Commend.7.narration.ogg"; Subtitle = "$int.Commend.7.narration";};
	};
};

G3SoundObject
{
	SoundID = 49;	// ACTION - COMPLIMENT
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Reputation.BlessedYou.ogg"; Subtitle = "$Cutscenes.Reputation.BlessedYou";};
		2 extends G3SoundDef { Path = "Cutscenes.Reputation.EveryDay.ogg"; Subtitle = "$Cutscenes.Reputation.EveryDay";};
		3 extends G3SoundDef { Path = "Cutscenes.Reputation.Inspiration.ogg"; Subtitle = "$Cutscenes.Reputation.Inspiration";};
		4 extends G3SoundDef { Path = "int.Compliment.0.ogg"; Subtitle = "$int.Compliment.0";};
		5 extends G3SoundDef { Path = "int.Compliment.1.ogg"; Subtitle = "$int.Compliment.1";};
		6 extends G3SoundDef { Path = "int.Compliment.2.ogg"; Subtitle = "$int.Compliment.2";};
		7 extends G3SoundDef { Path = "int.Compliment.3.ogg"; Subtitle = "$int.Compliment.3";};
	};
};

G3SoundObject
{
	SoundID = 50;	// ACTION - MARRIAGE PROPOSAL
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.CleaningMyHouse.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.CleaningMyHouse";}; // f: $Cutscenes.ComplimentSpouse.Family
		2 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.GoOnLiving.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.GoOnLiving";}; // f: $Cutscenes.ComplimentSpouse.GoodHusband
		3 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.Hungry.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.Hungry";}; // f: $Cutscenes.ComplimentSpouse.FreeOfDisease
		4 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.KindOfWoman.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.KindOfWoman";}; // f: $Cutscenes.ComplimentSpouse.KindOfMan
		5 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.MyLife.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.MyLife";}; // f: $Cutscenes.ComplimentSpouse.GoodSir
	};
};

G3SoundObject
{
	SoundID = 51;	// ACTION - TALK DIRTY
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1200;
	Volume = 0.5;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.RadiantBeauty.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.RadiantBeauty";}; // f: $Cutscenes.ComplimentSpouse.SoStrong
		2 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.Stars.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.Stars";}; // f: $Cutscenes.ComplimentSpouse.TalkToALady
	};
};

G3SoundObject
{
	SoundID = 52;	// ACTION - DENOUNCE REACTION AUDIENCE
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.Denounce.Audience.0.ogg"; Subtitle = "$int.Denounce.Audience.0";};
		2 extends G3SoundDef { Path = "int.Denounce.Audience.1.ogg"; Subtitle = "$int.Denounce.Audience.1";};
		3 extends G3SoundDef { Path = "int.Denounce.Audience.2.ogg"; Subtitle = "$int.Denounce.Audience.2";};
		4 extends G3SoundDef { Path = "int.Denounce.Audience.3.ogg"; Subtitle = "$int.Denounce.Audience.3";};
		5 extends G3SoundDef { Path = "int.Denounce.Audience.4.ogg"; Subtitle = "$int.Denounce.Audience.4";};
		6 extends G3SoundDef { Path = "int.Denounce.Audience.5.ogg"; Subtitle = "$int.Denounce.Audience.5";};
		7 extends G3SoundDef { Path = "int.Denounce.Audience.6.ogg"; Subtitle = "$int.Denounce.Audience.6";};
		8 extends G3SoundDef { Path = "int.Denounce.Audience.7.ogg"; Subtitle = "$int.Denounce.Audience.7";};
	};
};

G3SoundObject
{
	SoundID = 53;	// ACTION - DENOUNCE REACTION VICTIM
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.Denounce.Victim.0.ogg"; Subtitle = "$int.Denounce.Victim.0";};
		2 extends G3SoundDef { Path = "int.Denounce.Victim.1.ogg"; Subtitle = "$int.Denounce.Victim.1";};
		3 extends G3SoundDef { Path = "int.Denounce.Victim.2.ogg"; Subtitle = "$int.Denounce.Victim.2";};
		4 extends G3SoundDef { Path = "int.Denounce.Victim.3.ogg"; Subtitle = "$int.Denounce.Victim.3";};
		5 extends G3SoundDef { Path = "int.Denounce.Victim.4.ogg"; Subtitle = "$int.Denounce.Victim.4";};
		6 extends G3SoundDef { Path = "int.Denounce.Victim.5.ogg"; Subtitle = "$int.Denounce.Victim.5";};
		7 extends G3SoundDef { Path = "int.Denounce.Victim.6.ogg"; Subtitle = "$int.Denounce.Victim.6";};
		8 extends G3SoundDef { Path = "int.Denounce.Victim.7.ogg"; Subtitle = "$int.Denounce.Victim.7";};
	};
};

G3SoundObject
{
	SoundID = 54;	// ACTION - Give Gift
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.Gift01.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.Gift01";};
		2 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.Gift02.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.Gift02";};
		3 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.Gift03.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.Gift03";};
		4 extends G3SoundDef { Path = "int.GiveGift.0.ogg"; Subtitle = "$int.GiveGift.0";};
		5 extends G3SoundDef { Path = "int.GiveGift.1.ogg"; Subtitle = "$int.GiveGift.1";};
		6 extends G3SoundDef { Path = "int.GiveGift.2.ogg"; Subtitle = "$int.GiveGift.2";};
		7 extends G3SoundDef { Path = "int.GiveGift.3.ogg"; Subtitle = "$int.GiveGift.3";};
	};
};

G3SoundObject
{
	SoundID = 55;	// ACTION - Insult
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Reputation.Brothel.ogg"; Subtitle = "$Cutscenes.Reputation.Brothel";};
		2 extends G3SoundDef { Path = "Cutscenes.Reputation.Clothes.ogg"; Subtitle = "$Cutscenes.Reputation.Clothes";};
		3 extends G3SoundDef { Path = "Cutscenes.Reputation.Nephew.ogg"; Subtitle = "$Cutscenes.Reputation.Nephew";};
		4 extends G3SoundDef { Path = "Cutscenes.Reputation.NoseLikeThat.ogg"; Subtitle = "$Cutscenes.Reputation.NoseLikeThat";};
		5 extends G3SoundDef { Path = "Cutscenes.Reputation.Orphans.ogg"; Subtitle = "$Cutscenes.Reputation.Orphans";};
		6 extends G3SoundDef { Path = "Cutscenes.Reputation.Renovating.ogg"; Subtitle = "$Cutscenes.Reputation.Renovating";};
		7 extends G3SoundDef { Path = "Cutscenes.Reputation.VillageIdiot.ogg"; Subtitle = "$Cutscenes.Reputation.VillageIdiot";};
		8 extends G3SoundDef { Path = "Cutscenes.Reputation.Wow.ogg"; Subtitle = "$Cutscenes.Reputation.Wow";};
		9 extends G3SoundDef { Path = "Cutscenes.Reputation.YouHouse.ogg"; Subtitle = "$Cutscenes.Reputation.YouHouse";};
		10 extends G3SoundDef { Path = "Cutscenes.Reputation.YourFamily.ogg"; Subtitle = "$Cutscenes.Reputation.YourFamily";};
		11 extends G3SoundDef { Path = "int.Insult.0.ogg"; Subtitle = "$int.Insult.0";};
		12 extends G3SoundDef { Path = "int.Insult.1.ogg"; Subtitle = "$int.Insult.1";};
		13 extends G3SoundDef { Path = "int.Insult.2.ogg"; Subtitle = "$int.Insult.2";};
		14 extends G3SoundDef { Path = "int.Insult.3.ogg"; Subtitle = "$int.Insult.3";};
	};
};

G3SoundObject
{
	SoundID = 56;	// ACTION - Insult triggers duel friendly reaction
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "friendly/int.Insult.Success.Friendly.0.ogg"; Subtitle = "$int.Insult.Success.Friendly.0";};
		2 extends G3SoundDef { Path = "friendly/int.Insult.Success.Friendly.1.ogg"; Subtitle = "$int.Insult.Success.Friendly.1";};
		3 extends G3SoundDef { Path = "friendly/int.Insult.Success.Friendly.2.ogg"; Subtitle = "$int.Insult.Success.Friendly.2";};
		4 extends G3SoundDef { Path = "friendly/int.Insult.Success.Friendly.3.ogg"; Subtitle = "$int.Insult.Success.Friendly.3";};
	};
};

G3SoundObject
{
	SoundID = 57;	// ACTION - Insult triggers duel hostile reaction
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "hostile/int.Insult.Success.Hatred.0.ogg"; Subtitle = "$int.Insult.Success.Hatred.0";};
		2 extends G3SoundDef { Path = "hostile/int.Insult.Success.Hatred.1.ogg"; Subtitle = "$int.Insult.Success.Hatred.1";};
		3 extends G3SoundDef { Path = "hostile/int.Insult.Success.Hatred.2.ogg"; Subtitle = "$int.Insult.Success.Hatred.2";};
		4 extends G3SoundDef { Path = "hostile/int.Insult.Success.Hatred.3.ogg"; Subtitle = "$int.Insult.Success.Hatred.3";};
	};
};

G3SoundObject
{
	SoundID = 58;	// ACTION - Insult triggers duel normal reaction
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.Insult.Success.Normal.0.ogg"; Subtitle = "$int.Insult.Success.Normal.0";};
		2 extends G3SoundDef { Path = "int.Insult.Success.Normal.1.ogg"; Subtitle = "$int.Insult.Success.Normal.1";};
		3 extends G3SoundDef { Path = "int.Insult.Success.Normal.2.ogg"; Subtitle = "$int.Insult.Success.Normal.2";};
		4 extends G3SoundDef { Path = "int.Insult.Success.Normal.3.ogg"; Subtitle = "$int.Insult.Success.Normal.3";};
	};
};

G3SoundObject
{
	SoundID = 59;	// ACTION - Insult fails -> Friendly reaction
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "friendly/int.Insult.Duel.Friendly.0.ogg"; Subtitle = "$int.Insult.Duel.Friendly.0";};
		2 extends G3SoundDef { Path = "friendly/int.Insult.Duel.Friendly.1.ogg"; Subtitle = "$int.Insult.Duel.Friendly.1";};
		3 extends G3SoundDef { Path = "friendly/int.Insult.Duel.Friendly.2.ogg"; Subtitle = "$int.Insult.Duel.Friendly.2";};
		4 extends G3SoundDef { Path = "friendly/int.Insult.Duel.Friendly.3.ogg"; Subtitle = "$int.Insult.Duel.Friendly.3";};
	};
};

G3SoundObject
{
	SoundID = 60;	// ACTION - Insult fails -> Hostile reaction
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "hostile/int.Insult.Duel.Hatred.0.ogg"; Subtitle = "$int.Insult.Duel.Hatred.0";};
		2 extends G3SoundDef { Path = "hostile/int.Insult.Duel.Hatred.1.ogg"; Subtitle = "$int.Insult.Duel.Hatred.1";};
		3 extends G3SoundDef { Path = "hostile/int.Insult.Duel.Hatred.2.ogg"; Subtitle = "$int.Insult.Duel.Hatred.2";};
		4 extends G3SoundDef { Path = "hostile/int.Insult.Duel.Hatred.3.ogg"; Subtitle = "$int.Insult.Duel.Hatred.3";};
	};
};

G3SoundObject
{
	SoundID = 61;	// ACTION - Insult fails -> normal reaction
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.Insult.Duel.Normal.0.ogg"; Subtitle = "$int.Insult.Duel.Normal.0";};
		2 extends G3SoundDef { Path = "int.Insult.Duel.Normal.1.ogg"; Subtitle = "$int.Insult.Duel.Normal.1";};
		3 extends G3SoundDef { Path = "int.Insult.Duel.Normal.2.ogg"; Subtitle = "$int.Insult.Duel.Normal.2";};
		4 extends G3SoundDef { Path = "int.Insult.Duel.Normal.3.ogg"; Subtitle = "$int.Insult.Duel.Normal.3";};
	};
};

G3SoundObject
{
	SoundID = 62;	// ACTION - Positive action failed - Friendly reaction
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "friendly/int.Positive.Failure.Friendly.0.ogg"; Subtitle = "$int.Positive.Failure.Friendly.0";};
		2 extends G3SoundDef { Path = "friendly/int.Positive.Failure.Friendly.1.ogg"; Subtitle = "$int.Positive.Failure.Friendly.1";};
		3 extends G3SoundDef { Path = "friendly/int.Positive.Failure.Friendly.2.ogg"; Subtitle = "$int.Positive.Failure.Friendly.2";};
		4 extends G3SoundDef { Path = "friendly/int.Positive.Failure.Friendly.3.ogg"; Subtitle = "$int.Positive.Failure.Friendly.3";};
	};
};

G3SoundObject
{
	SoundID = 63;	// ACTION - Positive action failed - Hostile reaction
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "hostile/int.Positive.Failure.Hatred.0.ogg"; Subtitle = "$int.Positive.Failure.Hatred.0";};
		2 extends G3SoundDef { Path = "hostile/int.Positive.Failure.Hatred.1.ogg"; Subtitle = "$int.Positive.Failure.Hatred.1";};
		3 extends G3SoundDef { Path = "hostile/int.Positive.Failure.Hatred.2.ogg"; Subtitle = "$int.Positive.Failure.Hatred.2";};
		4 extends G3SoundDef { Path = "hostile/int.Positive.Failure.Hatred.3.ogg"; Subtitle = "$int.Positive.Failure.Hatred.3";};
	};
};

G3SoundObject
{
	SoundID = 64;	// ACTION - Positive action failed - Normal reaction
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.Positive.Failure.Normal.0.ogg"; Subtitle = "$int.Positive.Failure.Normal.0";};
		2 extends G3SoundDef { Path = "int.Positive.Failure.Normal.1.ogg"; Subtitle = "$int.Positive.Failure.Normal.1";};
		3 extends G3SoundDef { Path = "int.Positive.Failure.Normal.2.ogg"; Subtitle = "$int.Positive.Failure.Normal.2";};
		4 extends G3SoundDef { Path = "int.Positive.Failure.Normal.3.ogg"; Subtitle = "$int.Positive.Failure.Normal.3";};
	};
};

G3SoundObject
{
	SoundID = 65;	// ACTION - Positive action successful - Friendly reaction
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "friendly/int.Positive.Success.Friendly.0.ogg"; Subtitle = "$int.Positive.Success.Friendly.0";};
		2 extends G3SoundDef { Path = "friendly/int.Positive.Success.Friendly.1.ogg"; Subtitle = "$int.Positive.Success.Friendly.1";};
		3 extends G3SoundDef { Path = "friendly/int.Positive.Success.Friendly.2.ogg"; Subtitle = "$int.Positive.Success.Friendly.2";};
		4 extends G3SoundDef { Path = "friendly/int.Positive.Success.Friendly.3.ogg"; Subtitle = "$int.Positive.Success.Friendly.3";};
	};
};

G3SoundObject
{
	SoundID = 66;	// ACTION - Positive action successful - Hostile reaction
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "hostile/int.Positive.Success.Hatred.0.ogg"; Subtitle = "$int.Positive.Success.Hatred.0";};
		2 extends G3SoundDef { Path = "hostile/int.Positive.Success.Hatred.1.ogg"; Subtitle = "$int.Positive.Success.Hatred.1";};
		3 extends G3SoundDef { Path = "hostile/int.Positive.Success.Hatred.2.ogg"; Subtitle = "$int.Positive.Success.Hatred.2";};
		4 extends G3SoundDef { Path = "hostile/int.Positive.Success.Hatred.3.ogg"; Subtitle = "$int.Positive.Success.Hatred.3";};
	};
};

G3SoundObject
{
	SoundID = 67;	// ACTION - Positive action successful - Normal reaction
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.Positive.Success.Normal.0.ogg"; Subtitle = "$int.Positive.Success.Normal.0";};
		2 extends G3SoundDef { Path = "int.Positive.Success.Normal.1.ogg"; Subtitle = "$int.Positive.Success.Normal.1";};
		3 extends G3SoundDef { Path = "int.Positive.Success.Normal.2.ogg"; Subtitle = "$int.Positive.Success.Normal.2";};
		4 extends G3SoundDef { Path = "int.Positive.Success.Normal.3.ogg"; Subtitle = "$int.Positive.Success.Normal.3";};
	};
};

G3SoundObject
{
	SoundID = 68;	// ACTION - Praise
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.Praise.0.narration.ogg"; Subtitle = "$int.Praise.0.narration";};
		2 extends G3SoundDef { Path = "int.Praise.1.narration.ogg"; Subtitle = "$int.Praise.1.narration";};
		3 extends G3SoundDef { Path = "int.Praise.2.narration.ogg"; Subtitle = "$int.Praise.2.narration";};
		4 extends G3SoundDef { Path = "int.Praise.3.narration.ogg"; Subtitle = "$int.Praise.3.narration";};
		5 extends G3SoundDef { Path = "int.Praise.4.narration.ogg"; Subtitle = "$int.Praise.4.narration";};
		6 extends G3SoundDef { Path = "int.Praise.5.narration.ogg"; Subtitle = "$int.Praise.5.narration";};
		7 extends G3SoundDef { Path = "int.Praise.6.narration.ogg"; Subtitle = "$int.Praise.6.narration";};
		8 extends G3SoundDef { Path = "int.Praise.7.narration.ogg"; Subtitle = "$int.Praise.7.narration";};
	};
};

G3SoundObject
{
	SoundID = 69;	// ACTION - Praise Audience REACTION
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.Praise.Audience.0.ogg"; Subtitle = "$int.Praise.Audience.0";};
		2 extends G3SoundDef { Path = "int.Praise.Audience.1.ogg"; Subtitle = "$int.Praise.Audience.1";};
		3 extends G3SoundDef { Path = "int.Praise.Audience.2.ogg"; Subtitle = "$int.Praise.Audience.2";};
		4 extends G3SoundDef { Path = "int.Praise.Audience.3.ogg"; Subtitle = "$int.Praise.Audience.3";};
		5 extends G3SoundDef { Path = "int.Praise.Audience.4.ogg"; Subtitle = "$int.Praise.Audience.4";};
		6 extends G3SoundDef { Path = "int.Praise.Audience.5.ogg"; Subtitle = "$int.Praise.Audience.5";};
		7 extends G3SoundDef { Path = "int.Praise.Audience.6.ogg"; Subtitle = "$int.Praise.Audience.6";};
		8 extends G3SoundDef { Path = "int.Praise.Audience.7.ogg"; Subtitle = "$int.Praise.Audience.7";};
	};
};

G3SoundObject
{
	SoundID = 70;	// ACTION - Praise Victim REACTION
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.Praise.Victim.0.ogg"; Subtitle = "$int.Praise.Victim.0";};
		2 extends G3SoundDef { Path = "int.Praise.Victim.1.ogg"; Subtitle = "$int.Praise.Victim.1";};
		3 extends G3SoundDef { Path = "int.Praise.Victim.2.ogg"; Subtitle = "$int.Praise.Victim.2";};
		4 extends G3SoundDef { Path = "int.Praise.Victim.3.ogg"; Subtitle = "$int.Praise.Victim.3";};
		5 extends G3SoundDef { Path = "int.Praise.Victim.4.ogg"; Subtitle = "$int.Praise.Victim.4";};
		6 extends G3SoundDef { Path = "int.Praise.Victim.5.ogg"; Subtitle = "$int.Praise.Victim.5";};
		7 extends G3SoundDef { Path = "int.Praise.Victim.6.ogg"; Subtitle = "$int.Praise.Victim.6";};
		8 extends G3SoundDef { Path = "int.Praise.Victim.7.ogg"; Subtitle = "$int.Praise.Victim.7";};
	};
};

G3SoundObject
{
	SoundID = 71;	// ACTION - Smear
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.Smear.0.narration.ogg"; Subtitle = "$int.Smear.0.narration";};
		2 extends G3SoundDef { Path = "int.Smear.1.narration.ogg"; Subtitle = "$int.Smear.1.narration";};
		3 extends G3SoundDef { Path = "int.Smear.2.narration.ogg"; Subtitle = "$int.Smear.2.narration";};
		4 extends G3SoundDef { Path = "int.Smear.3.narration.ogg"; Subtitle = "$int.Smear.3.narration";};
		5 extends G3SoundDef { Path = "int.Smear.4.narration.ogg"; Subtitle = "$int.Smear.4.narration";};
		6 extends G3SoundDef { Path = "int.Smear.5.narration.ogg"; Subtitle = "$int.Smear.5.narration";};
		7 extends G3SoundDef { Path = "int.Smear.6.narration.ogg"; Subtitle = "$int.Smear.6.narration";};
		8 extends G3SoundDef { Path = "int.Smear.7.narration.ogg"; Subtitle = "$int.Smear.7.narration";};
	};
};

G3SoundObject
{
	SoundID = 72;	// Audience Revolt
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Frequency = 0.1;
	Sounds = array
	{
		//1 extends G3SoundDef { Path = "revolt.1.ogg"; Subtitle = "$revolt.1";};
		//2 extends G3SoundDef { Path = "revolt.10.ogg"; Subtitle = "$revolt.10";};
		//3 extends G3SoundDef { Path = "revolt.2.ogg"; Subtitle = "$revolt.2";};
		1 extends G3SoundDef { Path = "revolt.3.ogg"; Subtitle = "$revolt.3";};
		//5 extends G3SoundDef { Path = "revolt.4.ogg"; Subtitle = "$revolt.4";};
		2 extends G3SoundDef { Path = "revolt.5.ogg"; Subtitle = "$revolt.5";};
		//7 extends G3SoundDef { Path = "revolt.6.ogg"; Subtitle = "$revolt.6";};
		3 extends G3SoundDef { Path = "revolt.7.ogg"; Subtitle = "$revolt.7";};
		//9 extends G3SoundDef { Path = "revolt.8.ogg"; Subtitle = "$revolt.8";};
		//4 extends G3SoundDef { Path = "revolt.9.ogg"; Subtitle = "$revolt.9";};
	};
};

G3SoundObject
{
	SoundID = 73;	// Ambience Nightwatch 1
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cityambient.Nightwatchman0.ogg"; Subtitle = "$cityambient.Nightwatchman0";};
	};
};

G3SoundObject
{
	SoundID = 74;	// Ambience Nightwatch 1
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cityambient.Nightwatchman1.ogg"; Subtitle = "$cityambient.Nightwatchman1";};
	};
};

G3SoundObject
{
	SoundID = 75;	// Ambience Nightwatch 1
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cityambient.Nightwatchman2.ogg"; Subtitle = "$cityambient.Nightwatchman2";};
	};
};

G3SoundObject
{
	SoundID = 76;	// Ambience Nightwatch 1
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cityambient.Nightwatchman3.ogg"; Subtitle = "$cityambient.Nightwatchman3";};
	};
};

G3SoundObject
{
	SoundID = 77;	// Ambience Towncrier
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cityambient.Towncrier0.ogg"; Subtitle = "$cityambient.Towncrier0";};
		2 extends G3SoundDef { Path = "cityambient.Towncrier1.ogg"; Subtitle = "$cityambient.Towncrier1";};
		3 extends G3SoundDef { Path = "cityambient.Towncrier2.ogg"; Subtitle = "$cityambient.Towncrier2";};
		4 extends G3SoundDef { Path = "cityambient.Towncrier3.ogg"; Subtitle = "$cityambient.Towncrier3";};
	};
};

//Cutscenes

G3SoundObject
{
	SoundID = 78;	// Church Buy Orphan
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.BuyOrphan.Children.ogg"; Subtitle = "$Cutscenes.BuyOrphan.Children";};
	};
};

G3SoundObject
{
	SoundID = 79;	// Church Buy Pardon
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Church.action.chooseSin.ogg"; Subtitle = "$Church.action.chooseSin";};
		2 extends G3SoundDef { Path = "Church.action.pay.Narration.ogg"; Subtitle = "$Church.action.pay.Narration";};
		3 extends G3SoundDef { Path = "Church.buyPardon.Narration.ogg"; Subtitle = "$Church.buyPardon.Narration";};
		4 extends G3SoundDef { Path = "Church.offering.Narration.ogg"; Subtitle = "$Church.offering.Narration";};
		5 extends G3SoundDef { Path = "Cutscenes.BuyPardon.BuyPardon.ogg"; Subtitle = "$Cutscenes.BuyPardon.BuyPardon";};
	};
};

G3SoundObject
{
	SoundID = 80;	// Church Intro
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Church.welcome.ogg"; Subtitle = "$Church.welcome";};
	};
};

G3SoundObject
{
	SoundID = 81;	// Election Intro
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Election.Introduction.ogg"; Subtitle = "$Cutscenes.Election.Introduction";};
	};
};

G3SoundObject
{
	SoundID = 82;	// No Election needed
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Election.Since.ogg"; Subtitle = "$Cutscenes.Election.Since";};
	};
};

G3SoundObject
{
	SoundID = 83;	// Election needed
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Election.Consideration.ogg"; Subtitle = "$Cutscenes.Election.Consideration";};
	};
};

G3SoundObject
{
	SoundID = 84;	// Execution Audience Victim hated
	Category = 5; // ESoundVoices
	Frequency = 0.1;
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Execution.bad1.ogg"; Subtitle = "$Cutscenes.Execution.bad1";};
		2 extends G3SoundDef { Path = "revolt.3.ogg"; Subtitle = "$revolt.3";};
		3 extends G3SoundDef { Path = "Cutscenes.Execution.bad2.ogg"; Subtitle = "$Cutscenes.Execution.bad2";};
		4 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Boohooo.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Boohooo";};
	};
};

G3SoundObject
{
	SoundID = 85;	// Execution Audience Victim was liked
	Category = 5; // ESoundVoices
	Frequency = 0.1;
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Execution.Good01.ogg"; Subtitle = "$Cutscenes.Execution.Good01";};
		2 extends G3SoundDef { Path = "Cutscenes.Execution.Good02.ogg"; Subtitle = "$Cutscenes.Execution.Good02";};
		3 extends G3SoundDef { Path = "Cutscenes.Execution.Good03.ogg"; Subtitle = "$Cutscenes.Execution.Good03";};
	};
};

G3SoundObject
{
	SoundID = 86;	// Execution Intro
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Execution.Start.ogg"; Subtitle = "$Cutscenes.Execution.Start";};
	};
};

G3SoundObject
{
	SoundID = 87;	// Medicus Character Damaged
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Medicus.Cost.ogg"; Subtitle = "$Cutscenes.Medicus.Cost";};
		2 extends G3SoundDef { Path = "Cutscenes.Medicus.Enemies.ogg"; Subtitle = "$Cutscenes.Medicus.Enemies";};
		3 extends G3SoundDef { Path = "Cutscenes.Medicus.Needs.ogg"; Subtitle = "$Cutscenes.Medicus.Needs";};
		4 extends G3SoundDef { Path = "Cutscenes.Medicus.Offend.ogg"; Subtitle = "$Cutscenes.Medicus.Offend";};
		5 extends G3SoundDef { Path = "Cutscenes.Medicus.OhMy.ogg"; Subtitle = "$Cutscenes.Medicus.OhMy";};
		6 extends G3SoundDef { Path = "Cutscenes.Medicus.OhRight.ogg"; Subtitle = "$Cutscenes.Medicus.OhRight";};
	};
};

G3SoundObject
{
	SoundID = 88;	// Medicus Character No Damage
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Medicus.Ish.ogg"; Subtitle = "$Cutscenes.Medicus.Ish";};
		2 extends G3SoundDef { Path = "Cutscenes.Medicus.Wasting.ogg"; Subtitle = "$Cutscenes.Medicus.Wasting";};
	};
};

G3SoundObject
{
	SoundID = 89;	// Tavern Intro - Innkeeper talking
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Around.ogg"; Subtitle = "$Cutscenes.TavernTalk.Around";};
		2 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Stranger.ogg"; Subtitle = "$Cutscenes.TavernTalk.Stranger";};
		3 extends G3SoundDef { Path = "Cutscenes.TavernTalk.TakeASeat.ogg"; Subtitle = "$Cutscenes.TavernTalk.TakeASeat";};
		4 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Welcome.ogg"; Subtitle = "$Cutscenes.TavernTalk.Welcome";};
	};
};

G3SoundObject
{
	SoundID = 90;	// Tavern Intro - Player talking
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.TavernTalk.AroundHere.ogg"; Subtitle = "$Cutscenes.TavernTalk.AroundHere";};
		2 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Drink.ogg"; Subtitle = "$Cutscenes.TavernTalk.Drink";};
		3 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Innkeeper.ogg"; Subtitle = "$Cutscenes.TavernTalk.Innkeeper";};
		4 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Phew.ogg"; Subtitle = "$Cutscenes.TavernTalk.Phew";};
	};
};

G3SoundObject
{
	SoundID = 91;	// Tavern Intro - people talking
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Girl.ogg"; Subtitle = "$Cutscenes.TavernTalk.Girl";};
		2 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Guy.ogg"; Subtitle = "$Cutscenes.TavernTalk.Guy";};
		3 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Pretzels.ogg"; Subtitle = "$Cutscenes.TavernTalk.Pretzels";};
		4 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Thirsty.ogg"; Subtitle = "$Cutscenes.TavernTalk.Thirsty";};
		5 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Tired.ogg"; Subtitle = "$Cutscenes.TavernTalk.Tired";};
		6 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Weather.ogg"; Subtitle = "$Cutscenes.TavernTalk.Weather";};
	};
};

G3SoundObject
{
	SoundID = 92;	// Court - Accused defending himself
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Trial.Believe.ogg"; Subtitle = "$Cutscenes.Trial.Believe";};
		2 extends G3SoundDef { Path = "Cutscenes.Trial.People.ogg"; Subtitle = "$Cutscenes.Trial.People";};
		3 extends G3SoundDef { Path = "Cutscenes.Trial.Ridiculous.ogg"; Subtitle = "$Cutscenes.Trial.Ridiculous";};
		4 extends G3SoundDef { Path = "Cutscenes.Trial.Upstanding.ogg"; Subtitle = "$Cutscenes.Trial.Upstanding";};
	};
};

G3SoundObject
{
	SoundID = 93;	// Court - Accused reacts on judgment
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Trial.Imbeciles.ogg"; Subtitle = "$Cutscenes.Trial.Imbeciles";};
		2 extends G3SoundDef { Path = "Cutscenes.Trial.Incompetence.ogg"; Subtitle = "$Cutscenes.Trial.Incompetence";};
		3 extends G3SoundDef { Path = "Cutscenes.Trial.Rogue.ogg"; Subtitle = "$Cutscenes.Trial.Rogue";};
		4 extends G3SoundDef { Path = "Cutscenes.Trial.Travesty.ogg"; Subtitle = "$Cutscenes.Trial.Travesty";};
	};
};

G3SoundObject
{
	SoundID = 94;	// Court - Trial intro
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Trial.Order.ogg"; Subtitle = "$Cutscenes.Trial.Order";};
	};
};

G3SoundObject
{
	SoundID = 95;	// Court - Guilty
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Trial.Easy.ogg"; Subtitle = "$Cutscenes.Trial.Easy";};
		2 extends G3SoundDef { Path = "Cutscenes.Trial.Flimsy.ogg"; Subtitle = "$Cutscenes.Trial.Flimsy";};
		3 extends G3SoundDef { Path = "Cutscenes.Trial.Guilty.ogg"; Subtitle = "$Cutscenes.Trial.Guilty";};
	};
};

G3SoundObject
{
	SoundID = 96;	// Court - Not Guilty
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Trial.God.ogg"; Subtitle = "$Cutscenes.Trial.God";};
		2 extends G3SoundDef { Path = "Cutscenes.Trial.Happy.ogg"; Subtitle = "$Cutscenes.Trial.Happy";};
		3 extends G3SoundDef { Path = "Cutscenes.Trial.Unfortunately.ogg"; Subtitle = "$Cutscenes.Trial.Unfortunately";};
	};
};

G3SoundObject
{
	SoundID = 97;	// Court - Court Ready For Judgment
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Trial.Judgement.ogg"; Subtitle = "$Cutscenes.Trial.Judgement";};
	};
};

G3SoundObject
{
	SoundID = 98;	// Wedding - Audience Reaction
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Aaaahh.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Aaaahh";};
		//2 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Boohooo.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Boohooo";};
		//3 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Boooo.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Boooo";};
		2 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Hooray.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Hooray";};
		3 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Noooo.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Noooo";};
		4 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Oooohhh.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Oooohhh";};
	};
};

G3SoundObject
{
	SoundID = 99;	// Wedding - Priest
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.FrontofGod.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.FrontofGod";};
		2 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Honored.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Honored";};
		3 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.MyPleasure.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.MyPleasure";};
	};
};

G3SoundObject
{
	SoundID = 100; //Action is not possible on allied 
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.AskAllianceAction.Request.narrator.ogg"; Subtitle = "$action.AskAllianceAction.Request.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 101; // Feud has been declared on Player
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.AskFeud.Victim.narrator.ogg"; Subtitle = "$action.AskFeud.Victim.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 102; //A dynasty requests to end a feud with the Player
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.BreakFeudAction.Request.narrator.ogg"; Subtitle = "$action.BreakFeudAction.Request.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 103; // A request to end a feud has been rejected
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.BreakFeudAction.SecretSociety.Denied.narrator.ogg"; Subtitle = "$action.BreakFeudAction.SecretSociety.Denied.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 104; // A request to end a feud with your guild has been received
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.BreakFeudAction.SecretSociety.Request.narrator.ogg"; Subtitle = "$action.BreakFeudAction.SecretSociety.Request.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 105; // A feud between 2 societies has been ended
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.BreakFeudAction.SecretSociety.Success.narrator.ogg"; Subtitle = "$action.BreakFeudAction.SecretSociety.Success.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 106; // Player has been commended
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.Commended.narrator.ogg"; Subtitle = "$action.Commended.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 107; // A compliment towards the player failed
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.ComplimentSomeone.FailureTarget.narrator.ogg"; Subtitle = "$action.ComplimentSomeone.FailureTarget.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 108; // A compliment towards the player was a success
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.ComplimentSomeone.SuccessTarget.narrator.ogg"; Subtitle = "$action.ComplimentSomeone.SuccessTarget.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 109; // Opponents try to conquer a building of the player
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.ConquerBuilding.StartTarget.narrator.ogg"; Subtitle = "$action.ConquerBuilding.StartTarget.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 110; // Opponent tries to conquer building from an ally
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.ConquerBuilding.StartTargetAllies.narrator.ogg"; Subtitle = "$action.ConquerBuilding.StartTargetAllies.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 111; // Player has successfully conquered a building
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.ConquerBuilding.SuccessSource.narrator.ogg"; Subtitle = "$action.ConquerBuilding.SuccessSource.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 112; // A building has been conqured from the player
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.ConquerBuilding.SuccessTarget.narrator.ogg"; Subtitle = "$action.ConquerBuilding.SuccessTarget.narrator";};
	}; 
};


G3SoundObject
{
	SoundID = 113; // Player has been denounced
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.Denounced.narrator.ogg"; Subtitle = "$action.Denounced.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 114; // Building has been demolished
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.DestroyBuildingPoliticalSuccesTitle.ogg"; Subtitle = "$action.DestroyBuildingPoliticalSuccesTitle";};
	}; 
};

G3SoundObject
{
	SoundID = 115; // A proposal has been made to destroy a building of the player
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.DestroyBuildingPoliticalWarningTitle.ogg"; Subtitle = "$action.DestroyBuildingPoliticalWarningTitle";};
	}; 
};

G3SoundObject
{
	SoundID = 116; // The player received a pouch of coins
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.GiveMoney.Target.Success.narrator.ogg"; Subtitle = "$action.GiveMoney.Target.Success.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 117; // An employee has been kidnapped
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.Hostage.Victim.Employee.narrator.ogg"; Subtitle = "$action.Hostage.Victim.Employee.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 118; // A family member has been kidnapped
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.Hostage.Victim.Kin.narrator.ogg"; Subtitle = "$action.Hostage.Victim.Kin.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 119; // Leader was taken hostage
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.Hostage.Victim.Leader.narrator.ogg"; Subtitle = "$action.Hostage.Victim.Leader.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 120; // Distance travel failed and character died
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.Longshore.Fail.Narration.ogg"; Subtitle = "$action.Longshore.Fail.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 121; // Distance travel worked out fine
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.Longshore.Success.Narration.ogg"; Subtitle = "$action.Longshore.Success.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 122; // Overseas travel did not work out
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.Longshore2.Fail.Narration.ogg"; Subtitle = "$action.Longshore2.Fail.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 123; //Overseas travel worked out fine
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.Longshore2.Success.Narration.ogg"; Subtitle = "$action.Longshore2.Success.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 124; // Leader was caught pickpocketing
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.PickPocketFailureLeader.narrator.ogg"; Subtitle = "$action.PickPocketFailureLeader.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 125; // Player dynasty was smeared
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.Smeared.narrator.ogg"; Subtitle = "$action.Smeared.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 126; // Player joined guild
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.SocietyInviteMemberAction.Members.narrator.ogg"; Subtitle = "$action.SocietyInviteMemberAction.Members.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 127; // Somebody joined the player's guild
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.SocietyKickMember.Player.narrator.ogg"; Subtitle = "$action.SocietyKickMember.Player.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 128; // The player is invited by a guild
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.StartLiaisonActionFail.narrator.ogg"; Subtitle = "$action.StartLiaisonActionFail.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 129; // Player is kicked from the guild
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.StartLiaisonActionSuccess.narrator.ogg"; Subtitle = "$action.StartLiaisonActionSuccess.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 130; // Break in player building
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.StealHouseVictim.narrator.ogg"; Subtitle = "$action.StealHouseVictim.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 131; // Love letter by the player was accepted
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.WriteLoveLetter.AcceptHead.ogg"; Subtitle = "$action.WriteLoveLetter.AcceptHead";};
	}; 
};

G3SoundObject
{
	SoundID = 132; // Love letter by the player has been refused
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.WriteLoveLetter.RefuseHead.ogg"; Subtitle = "$action.WriteLoveLetter.RefuseHead";};
	}; 
};

G3SoundObject
{
	SoundID = 133; // Player refused a love letter
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.WriteLoveLetter.RequestHead.ogg"; Subtitle = "$action.WriteLoveLetter.RequestHead";};
	}; 
};

G3SoundObject
{
	SoundID = 134; // The city council is making an announcement
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "announcement.council.narration.ogg"; Subtitle = "$announcement.council.narration";};
	}; 
};

G3SoundObject
{
	SoundID = 135; // A fight has been lost
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "combat.end.loser.ogg"; Subtitle = "$combat.end.loser";};
	}; 
};

G3SoundObject
{
	SoundID = 136; // A fight has been won
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "combat.end.winner.ogg"; Subtitle = "$combat.end.winner";};
	}; 
};

G3SoundObject
{
	SoundID = 137; // The player lost
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "EndGameWindow.GameOverTitle.ogg"; Subtitle = "$EndGameWindow.GameOverTitel";};
	}; 
};

G3SoundObject
{
	SoundID = 138; // The player won
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "EndGameWindow.YouWinTitle.ogg"; Subtitle = "$EndGameWindow.YouWinTitle";};
	}; 
};

G3SoundObject
{
	SoundID = 139; // Event - The city is burning
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Event.GreatFire.narrator.ogg"; Subtitle = "$Event.GreatFire.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 140; // Event - Bad Harvest
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Event.Harvest.Bad.narrator.ogg"; Subtitle = "$Event.Harvest.Bad.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 141; // Event - Good Harvest
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Event.Harvest.Good.narrator.ogg"; Subtitle = "$Event.Harvest.Good.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 142; // Event - Plague
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Event.Plague.Infected.narrator.ogg"; Subtitle = "$Event.Plague.Infected.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 143; // Event - Plague started
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Event.Plague.Started.narrator.ogg"; Subtitle = "$Event.Plague.Started.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 144; // Event - War started
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Event.WarStarted.narrator.ogg"; Subtitle = "$Event.WarStarted.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 145; // Player was insulted
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "fb.Compliment.Failure.Target.narrator.ogg"; Subtitle = "$fb.Compliment.Failure.Target.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 146; // Player got a compliment
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "fb.Compliment.Success.Target.narrator.ogg"; Subtitle = "$fb.Compliment.Success.Target.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 147; // Enemy reacts on an insult by triggering a duel
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "fb.Insult.Duel.Headline.ogg"; Subtitle = "$fb.Insult.Duel.Headline";};
	}; 
};

G3SoundObject
{
	SoundID = 148; // The player gained reputation
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "fb.Reputation.Gain.Headline.ogg"; Subtitle = "$fb.Reputation.Gain.Headline";};
	}; 
};

G3SoundObject
{
	SoundID = 149; // The player lost reputation
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "fb.Reputation.Loss.Headline.ogg"; Subtitle = "$fb.Reputation.Loss.Headline";};
	}; 
};

G3SoundObject
{
	SoundID = 150; // Player is insulted
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "fb.Reputation.Negative.Headline.ogg"; Subtitle = "$fb.Reputation.Negative.Headline";};
	}; 
};

G3SoundObject
{
	SoundID = 151; // player got praised or complimented
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "fb.Reputation.Positive.Headline.ogg"; Subtitle = "$fb.Reputation.Positive.Headline";};
	}; 
};

G3SoundObject
{
	SoundID = 152; // female Liaison died
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.concubineDead.female.narrator.ogg"; Subtitle = "$gui.concubineDead.female.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 153; // male liaison died
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.concubineDead.narrator.ogg"; Subtitle = "$gui.concubineDead.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 154; // female Liaison will end relationship
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.concubineInheritance.female.narrator.ogg"; Subtitle = "$gui.concubineInheritance.female.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 155; // male Liaison will end relationship
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.concubineInheritance.narrator.ogg"; Subtitle = "$gui.concubineInheritance.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 156; // Female liaison is leaving
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.concubineLostInterest.female.narrator.ogg"; Subtitle = "$gui.concubineLostInterest.female.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 157; // male Liaison is leaving
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.concubineLostInterest.narrator.ogg"; Subtitle = "$gui.concubineLostInterest.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 158; // Trade request received
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.IncomingMessage.Trade.ogg"; Subtitle = "$gui.IncomingMessage.Trade";};
	}; 
};

G3SoundObject
{
	SoundID = 159; // Books are audited
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.PoliticalPower.TargetAudit.Narration.ogg"; Subtitle = "$gui.PoliticalPower.TargetAudit.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 160; // Bad news about the player will be announced
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.PoliticalPower.TargetCityRecordBad.Narration.ogg"; Subtitle = "$gui.PoliticalPower.TargetCityRecordBad.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 161; // Good news about the player will be announced
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.PoliticalPower.TargetCityRecordGood.Narration.ogg"; Subtitle = "$gui.PoliticalPower.TargetCityRecordGood.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 162; // Player banished
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.PoliticalPower.TargetHeretic.Narration.ogg"; Subtitle = "$gui.PoliticalPower.TargetHeretic.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 163; // Player will need to stay longer in prison
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.PoliticalPower.TargetPrisonBad.Narration.ogg"; Subtitle = "$gui.PoliticalPower.TargetPrisonBad.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 164; // Player will be released earlier from prison
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.PoliticalPower.TargetPrisonGood.Narration.ogg"; Subtitle = "$gui.PoliticalPower.TargetPrisonGood.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 165; // Boy was born
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.birth.boy.ogg"; Subtitle = "$message.birth.boy";};
	}; 
};

G3SoundObject
{
	SoundID = 166; // Girl was born
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.birth.girl.ogg"; Subtitle = "$message.birth.girl";};
	}; 
};

G3SoundObject
{
	SoundID = 167; // A building is burning
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.building.burning.head.ogg"; Subtitle = "$message.building.burning.head";};
	}; 
};

G3SoundObject
{
	SoundID = 168; // City is growing
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.citygrowth.title.ogg"; Subtitle = "$message.citygrowth.title";};
	}; 
};

G3SoundObject
{
	SoundID = 169; // Employee died
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.EmployeeDead.Header.ogg"; Subtitle = "$message.EmployeeDead.Header";};
	}; 
};

G3SoundObject
{
	SoundID = 170; // Employee is drunk
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.EmployeeInebriated.Header.ogg"; Subtitle = "$message.EmployeeInebriated.Header";};
	}; 
};

G3SoundObject
{
	SoundID = 171; // Employee leveled up
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.EmployeeLevel.Header.ogg"; Subtitle = "$message.EmployeeLevel.Header";};
	}; 
};

G3SoundObject
{
	SoundID = 172; // Employee poisoned
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.EmployeePoisoned.Header.ogg"; Subtitle = "$message.EmployeePoisoned.Header";};
	}; 
};

G3SoundObject
{
	SoundID = 173; // Production stopped
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.EmployeesCantWork.Header.ogg"; Subtitle = "$message.EmployeesCantWork.Header";};
	}; 
};

G3SoundObject
{
	SoundID = 174; // Production stopped because out of storage
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.EmployeesCantWork.NoStorageSpace.Header.ogg"; Subtitle = "$message.EmployeesCantWork.NoStorageSpace.Header";};
	}; 
};

G3SoundObject
{
	SoundID = 175; // Employee is sick
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.EmployeeSick.Header.ogg"; Subtitle = "$message.EmployeeSick.Header";};
	}; 
};

G3SoundObject
{
	SoundID = 176; // Employee is wounded
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.EmployeeWounded.Header.ogg"; Subtitle = "$message.EmployeeWounded.Header";};
	}; 
};

G3SoundObject
{
	SoundID = 177; // Family member died
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.FamilyMemberDied.Header.ogg"; Subtitle = "$message.FamilyMemberDied.Header";};
	}; 
};

G3SoundObject
{
	SoundID = 178; // Family member drunk
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.FamilyMemberInebriated.Header.ogg"; Subtitle = "$message.FamilyMemberInebriated.Header";};
	}; 
};

G3SoundObject
{
	SoundID = 179; // Family member poisoned
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.FamilyMemberPoisoned.Header.ogg"; Subtitle = "$message.FamilyMemberPoisoned.Header";};
	}; 
};

G3SoundObject
{
	SoundID = 180; // Family member sick
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.FamilyMemberSick.Header.ogg"; Subtitle = "$message.FamilyMemberSick.Header";};
	}; 
};

G3SoundObject
{
	SoundID = 181; // Family member is wounded
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.FamilyMemberWounded.Header.ogg"; Subtitle = "$message.FamilyMemberWounded.Header";};
	}; 
};

G3SoundObject
{
	SoundID = 182; // Feud declared on player
	Category = 5; // ESoundVoices
	Sounds = array
	{	
		1 extends G3SoundDef { Path = "message.FamilyStartedAFeud.Narration.ogg"; Subtitle = "$message.FamilyStartedAFeud.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 183; // Leader of another dynasty died
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.OtherLeader.Dead.Narration.ogg"; Subtitle = "$message.OtherLeader.Dead.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 184; // Leader of another dynasty executed
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.OtherLeader.Execution.Narration.ogg"; Subtitle = "$message.OtherLeader.Execution.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 185; // Main residence lost
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.prevention.NoHouse.narration.ogg"; Subtitle = "$message.prevention.NoHouse.narration";};
	}; 
};

G3SoundObject
{
	SoundID = 186; // Player is under attack
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "quickmessage.AvatarAttacked.Narration.ogg"; Subtitle = "$quickmessage.AvatarAttacked.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 187; // A family member is under attack
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "quickmessage.FamilyAttacked.Narration.ogg"; Subtitle = "$quickmessage.FamilyAttacked.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 188; // Player's residence is under attack
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "quickmessage.ResidenceAttacked.Narration.ogg"; Subtitle = "$quickmessage.ResidenceAttacked.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 189; // A building of the player is attacked 
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "quickmessage.BuildingAttacked.Narration.ogg"; Subtitle = "$quickmessage.BuildingAttacked.Narration";};
	}; 
};

G3SoundObject
{
	SoundID = 190; // Building finished
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "quickmessage.buildingfinished.narration.ogg"; Subtitle = "$quickmessage.buildingfinished.narration";};
	}; 
};

G3SoundObject
{
	SoundID = 191; // Building has been upgraded
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "quickmessage.buildinglevelup.narration.ogg"; Subtitle = "$quickmessage.buildinglevelup.narration";};
	}; 
};

G3SoundObject
{
	SoundID = 192; // Event - Drought
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "quickmessage.drought.ogg"; Subtitle = "$quickmessage.drought";};
	}; 
};

G3SoundObject
{
	SoundID = 193; // Weather - Ice
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "quickmessage.iciness.ogg"; Subtitle = "$quickmessage.iciness";};
	}; 
};

G3SoundObject
{
	SoundID = 194; // Weather - Raining
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "quickmessage.rainfall.ogg"; Subtitle = "$quickmessage.rainfall";};
	}; 
};

G3SoundObject
{
	SoundID = 195; // Weather - Snowing
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "quickmessage.snowstorm.ogg"; Subtitle = "$quickmessage.snowstorm";};
	}; 
};

G3SoundObject
{
	SoundID = 196; // Weather - Thunder
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "quickmessage.thunder.ogg"; Subtitle = "$quickmessage.thunder";};
	}; 
};

G3SoundObject
{
	SoundID = 197; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.negative.narration.1.ogg"; Subtitle = "$randomEvents.negative.narration.1";};
	}; 
};

G3SoundObject
{
	SoundID = 198; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.negative.narration.2.ogg"; Subtitle = "$randomEvents.negative.narration.2";};
	}; 
};

G3SoundObject
{
	SoundID = 199; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.negative.narration.3.ogg"; Subtitle = "$randomEvents.negative.narration.3";};
	}; 
};

G3SoundObject
{
	SoundID = 200; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.negative.narration.4.ogg"; Subtitle = "$randomEvents.negative.narration.4";};
	}; 
};

G3SoundObject
{
	SoundID = 201; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.negative.narration.5.ogg"; Subtitle = "$randomEvents.negative.narration.5";};
	}; 
};

G3SoundObject
{
	SoundID = 202; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.neutral.narration.1.ogg"; Subtitle = "$randomEvents.neutral.narration.1";};
	}; 
};

G3SoundObject
{
	SoundID = 203; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.neutral.narration.2.ogg"; Subtitle = "$randomEvents.neutral.narration.2";};
	}; 
};

G3SoundObject
{
	SoundID = 204; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.neutral.narration.3.ogg"; Subtitle = "$randomEvents.neutral.narration.3";};
	}; 
};

G3SoundObject
{
	SoundID = 205; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.neutral.narration.4.ogg"; Subtitle = "$randomEvents.neutral.narration.4";};
	}; 
};

G3SoundObject
{
	SoundID = 206; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.neutral.narration.5.ogg"; Subtitle = "$randomEvents.neutral.narration.5";};
	}; 
};

G3SoundObject
{
	SoundID = 207; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.positive.narration.1.ogg"; Subtitle = "$randomEvents.positive.narration.1";};
	}; 
};

G3SoundObject
{
	SoundID = 208; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.positive.narration.2.ogg"; Subtitle = "$randomEvents.positive.narration.2";};
	}; 
};

G3SoundObject
{
	SoundID = 209; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.positive.narration.3.ogg"; Subtitle = "$randomEvents.positive.narration.3";};
	}; 
};

G3SoundObject
{
	SoundID = 210; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.positive.narration.4.ogg"; Subtitle = "$randomEvents.positive.narration.4";};
	}; 
};

G3SoundObject
{
	SoundID = 211; // Public Event
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "randomEvents.positive.narration.5.ogg"; Subtitle = "$randomEvents.positive.narration.5";};
	}; 
};

G3SoundObject
{
	SoundID = 212; // Tutorial completed
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "ui.tutorial.goodjob.ogg"; Subtitle = "$ui.tutorial.goodjob";};
	}; 
};

G3SoundObject
{
	SoundID = 213; // Building of player sabotaged
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.SabotageBuilding.Target.Success.narrator.ogg"; Subtitle = "$action.SabotageBuilding.Target.Success.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 214; // Sabotage attempt on player's building failed
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.SabotageBuilding.Target.Failure.narrator.ogg"; Subtitle = "$action.SabotageBuilding.Target.Failure.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 215; // Player received a gift
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.GiveGift.Target.Success.narrator.ogg"; Subtitle = "$action.GiveGift.Target.Success.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 216; // Ghostly fog has been applied to the player
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.ApplyGhostlyFog.SuccessTarget.Headline.ogg"; Subtitle = "$action.ApplyGhostlyFog.SuccessTarget.Headline";};
	}; 
};

G3SoundObject
{
	SoundID = 217; // Player has been poisoned
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.PoisonCharacter.Target.Success.narrator.ogg"; Subtitle = "$action.PoisonCharacter.Target.Success.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 218; // Poison attempt on player failed
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.PoisonCharacter.Target.Failure.narrator.ogg"; Subtitle = "$action.PoisonCharacter.Target.Failure.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 219; // Character paralysed
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.ApplyParalysisPoison.SuccessTarget.Headline.ogg"; Subtitle = "$action.ApplyParalysisPoison.SuccessTarget.Headline";};
	}; 
};

G3SoundObject
{
	SoundID = 220; // Action cannot be done on allies
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.ALLIANCE.narrator.ogg"; Subtitle = "$action.ALLIANCE.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 221; // Player invited by guild
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.SocietyInviteMemberAction.Request.narrator.ogg"; Subtitle = "$action.SocietyInviteMemberAction.Request.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 222; // Player joined guil
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.SocietyInviteMemberAction.Accept.narrator.ogg"; Subtitle = "$action.SocietyInviteMemberAction.Accept.narrator";};
	}; 
};

G3SoundObject
{
	SoundID = 223; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "mapStart.narration.difficulty.easy.ogg"; Subtitle = "$mapStart.narration.difficulty.easy";};
	}; 
};

G3SoundObject
{
	SoundID = 224; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "mapStart.narration.difficulty.hard.ogg"; Subtitle = "$mapStart.narration.difficulty.hard";};
	}; 
};

G3SoundObject
{
	SoundID = 225; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "mapStart.narration.difficulty.impossible.ogg"; Subtitle = "$mapStart.narration.difficulty.impossible";};
	}; 
};

G3SoundObject
{
	SoundID = 226; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "mapStart.narration.difficulty.normal.ogg"; Subtitle = "$mapStart.narration.difficulty.normal";};
	}; 
};

G3SoundObject
{
	SoundID = 227; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "mapStart.narration.dynasty.ogg"; Subtitle = "$mapStart.narration.dynasty";};
	}; 
};

G3SoundObject
{
	SoundID = 228; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "mapStart.narration.gamemode.career.ogg"; Subtitle = "$mapStart.narration.gamemode.career";};
	}; 
};

G3SoundObject
{
	SoundID = 229; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "mapStart.narration.gamemode.poorfellow.ogg"; Subtitle = "$mapStart.narration.gamemode.poorfellow";};
	}; 
};

G3SoundObject
{
	SoundID = 230; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "mapStart.narration.gamemode.scenariodependent.ogg"; Subtitle = "$mapStart.narration.gamemode.scenariodependent";};
	}; 
};

G3SoundObject
{
	SoundID = 231; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "mapStart.narration.story.sandbox.ogg"; Subtitle = "$mapStart.narration.story.sandbox";};
	}; 
};

G3SoundObject
{
	SoundID = 232; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "mapStart.narration.welcome.ogg"; Subtitle = "$mapStart.narration.welcome";};
	}; 
};

G3SoundObject
{
	SoundID = 233; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "ui.StoryQuest.Narration0.ogg"; Subtitle = "$ui.StoryQuest.Narration0";};
	}; 
};

G3SoundObject
{
	SoundID = 234; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "ui.StoryQuest.Narration1.ogg"; Subtitle = "$ui.StoryQuest.Narration1";};
	}; 
};

G3SoundObject
{
	SoundID = 235; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "ui.StoryQuest.Narration2.ogg"; Subtitle = "$ui.StoryQuest.Narration2";};
	}; 
};

G3SoundObject
{
	SoundID = 236; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "ui.StoryQuest.Narration3.ogg"; Subtitle = "$ui.StoryQuest.Narration3";};
	}; 
};

G3SoundObject
{
	SoundID = 237; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "ui.StoryQuest.Narration4.ogg"; Subtitle = "$ui.StoryQuest.Narration4";};
	}; 
};

G3SoundObject
{
	SoundID = 238; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "ui.StoryQuest.Narration5.ogg"; Subtitle = "$ui.StoryQuest.Narration5";};
	}; 
};

G3SoundObject
{
	SoundID = 239; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "ui.StoryQuest.Narration6.ogg"; Subtitle = "$ui.StoryQuest.Narration6";};
	}; 
};

G3SoundObject
{
	SoundID = 241; // Map start narration
	Category = 5; // ESoundVoices
	Priority = 10;
	Volume = 1.2;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "ui.StoryQuest.Narration7.ogg"; Subtitle = "$ui.StoryQuest.Narration7";};
	}; 
};

G3SoundObject
{
	SoundID = 240; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.Nobility1.ogg"; Subtitle = "$gui.Nobility1";};
		2 extends G3SoundDef { Path = "gui.Nobility2.ogg"; Subtitle = "$gui.Nobility2";};
		3 extends G3SoundDef { Path = "gui.Nobility3.ogg"; Subtitle = "$gui.Nobility3";};
	}; 
};

G3SoundObject
{
	SoundID = 243; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.1.ogg"; Subtitle = "$nobility.1";};
	}; 
};

G3SoundObject
{
	SoundID = 244; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.2.ogg"; Subtitle = "$nobility.2";};
	}; 
};

G3SoundObject
{
	SoundID = 245; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.3.ogg"; Subtitle = "$nobility.3";};
	}; 
};


G3SoundObject
{
	SoundID = 246; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.4.ogg"; Subtitle = "$nobility.4";};
	}; 
};

G3SoundObject
{
	SoundID = 247; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.5.ogg"; Subtitle = "$nobility.5";};
	}; 
};

G3SoundObject
{
	SoundID = 248; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.6.ogg"; Subtitle = "$nobility.6";};
	}; 
};

G3SoundObject
{
	SoundID = 249; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.7.ogg"; Subtitle = "$nobility.7";};
	}; 
};

G3SoundObject
{
	SoundID = 250; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.8.ogg"; Subtitle = "$nobility.8";};
	}; 
};

G3SoundObject
{
	SoundID = 251; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.9.ogg"; Subtitle = "$nobility.9";};
	}; 
};

G3SoundObject
{
	SoundID = 252; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.10.ogg"; Subtitle = "$nobility.10";};
	}; 
};

G3SoundObject
{
	SoundID = 253; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.11.ogg"; Subtitle = "$nobility.11";};
	}; 
};

G3SoundObject
{
	SoundID = 254; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.12.ogg"; Subtitle = "$nobility.12";};
	}; 
};


G3SoundObject
{
	SoundID = 255; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.13.ogg"; Subtitle = "$nobility.13";};
	}; 
};


G3SoundObject
{
	SoundID = 256; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.14.ogg"; Subtitle = "$nobility.14";};
	}; 
};

G3SoundObject
{
	SoundID = 257; // Nobility title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.15.ogg"; Subtitle = "$nobility.15";};
	}; 
};

G3SoundObject
{
	SoundID = 258; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.1.female.ogg"; Subtitle = "$nobility.1.female";};
	}; 
};

G3SoundObject
{
	SoundID = 259; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.2.female.ogg"; Subtitle = "$nobility.2.female";};
	}; 
};

G3SoundObject
{
	SoundID = 260; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.3.female.ogg"; Subtitle = "$nobility.3.female";};
	}; 
};

G3SoundObject
{
	SoundID = 261; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.4.female.ogg"; Subtitle = "$nobility.4.female";};
	}; 
};

G3SoundObject
{
	SoundID = 262; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.5.female.ogg"; Subtitle = "$nobility.5.female";};
	}; 
};

G3SoundObject
{
	SoundID = 263; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.6.female.ogg"; Subtitle = "$nobility.6.female";};
	}; 
};

G3SoundObject
{
	SoundID = 264; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.7.female.ogg"; Subtitle = "$nobility.7.female";};
	}; 
};

G3SoundObject
{
	SoundID = 265; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.8.female.ogg"; Subtitle = "$nobility.8.female";};
	}; 
};

G3SoundObject
{
	SoundID = 266; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.9.female.ogg"; Subtitle = "$nobility.9.female";};
	}; 
};

G3SoundObject
{
	SoundID = 267; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.10.female.ogg"; Subtitle = "$nobility.10.female";};
	}; 
};

G3SoundObject
{
	SoundID = 268; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.11.female.ogg"; Subtitle = "$nobility.11.female";};
	}; 
};

G3SoundObject
{
	SoundID = 269; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.12.female.ogg"; Subtitle = "$nobility.12.female";};
	}; 
};


G3SoundObject
{
	SoundID = 270; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.13.female.ogg"; Subtitle = "$nobility.13.female";};
	}; 
};

G3SoundObject
{
	SoundID = 271; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.14.female.ogg"; Subtitle = "$nobility.14.female";};
	}; 
};

G3SoundObject
{
	SoundID = 272; // Nobility title female
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "nobility.15.female.ogg"; Subtitle = "$nobility.15.female";};
	}; 
};

G3SoundObject
{
	SoundID = 273; // Nobility title purchased
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.Nobility1.purchase.ogg"; Subtitle = "$gui.Nobility1.purchase";};
	}; 
};

G3SoundObject
{
	SoundID = 274; // Nobility title purchased
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.Nobility2.purchase.ogg"; Subtitle = "$gui.Nobility2.purchase";};
	}; 
};

G3SoundObject
{
	SoundID = 275; // Nobility title purchased
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "gui.Nobility3.purchase.ogg"; Subtitle = "$gui.Nobility3.purchase";};
	}; 
};

// death sounds

G3SoundObject
{
	SoundID = 276; // Death sound of adults
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "death_short_0.ogg"; Subtitle = "";};
		2 extends G3SoundDef { Path = "death_short_1.ogg"; Subtitle = "";};
		3 extends G3SoundDef { Path = "death_short_2.ogg"; Subtitle = "";};
	}; 
};

G3SoundObject
{
	SoundID = 277;	// Audience Public Entertainment and Fights - target loved
	Category = 5; // ESoundVoices
	Frequency = 0.1;
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		
		1 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Aaaahh.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Aaaahh";};
		2 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Hooray.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Hooray";};
		3 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Oooohhh.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Oooohhh";};
	};
};

G3SoundObject
{
	SoundID = 278;	// Audience Begging - Target loved
	Category = 5; // ESoundVoices
	Frequency = 0.1;
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{		
		1 extends G3SoundDef { Path = "int.Denounce.Audience.5.ogg"; Subtitle = "$int.Denounce.Audience.5";};
		2 extends G3SoundDef { Path = "int.Denounce.Audience.6.ogg"; Subtitle = "$int.Denounce.Audience.6";};
		3 extends G3SoundDef { Path = "int.Denounce.Audience.7.ogg"; Subtitle = "$int.Denounce.Audience.7";};
	};
};

G3SoundObject
{
	SoundID = 279;	//Action Ask Favor
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{		
		1 extends G3SoundDef { Path = "Cutscenes.Reputation.YourFamily.ogg"; Subtitle = "$Cutscenes.Reputation.YourFamily";};
	};
};



G3SoundObject
{
	SoundID = 280;	// ACTION - neutral compliments (can be used for bribe, etc)
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Reputation.BlessedYou.ogg"; Subtitle = "$Cutscenes.Reputation.BlessedYou";};
		2 extends G3SoundDef { Path = "Cutscenes.Reputation.EveryDay.ogg"; Subtitle = "$Cutscenes.Reputation.EveryDay";};
		3 extends G3SoundDef { Path = "Cutscenes.Reputation.Inspiration.ogg"; Subtitle = "$Cutscenes.Reputation.Inspiration";};
		4 extends G3SoundDef { Path = "int.Compliment.0.ogg"; Subtitle = "$int.Compliment.0";};
		5 extends G3SoundDef { Path = "int.Compliment.1.ogg"; Subtitle = "$int.Compliment.1";};
		6 extends G3SoundDef { Path = "int.Compliment.3.ogg"; Subtitle = "$int.Compliment.3";};
		7 extends G3SoundDef { Path = "Cutscenes.Reputation.YourFamily.ogg"; Subtitle = "$Cutscenes.Reputation.YourFamily";};
	};
};

G3SoundObject
{
	SoundID = 281;	// Audience Public Entertainment and Fights- Target hated
	Category = 5; // ESoundVoices
	Frequency = 0.1;
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		
		1 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Boohooo.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Boohooo";};
		2 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Boooo.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Boooo";};
		3 extends G3SoundDef { Path = "Cutscenes.Wedding.Wedding.Noooo.ogg"; Subtitle = "$Cutscenes.Wedding.Wedding.Noooo";};
	};
};

G3SoundObject
{
	SoundID = 282;	// Audience Begging - Target hated
	Category = 5; // ESoundVoices
	Frequency = 0.1;
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{		
		1 extends G3SoundDef { Path = "int.Denounce.Audience.5.ogg"; Subtitle = "$int.Denounce.Audience.5";};
		2 extends G3SoundDef { Path = "int.Denounce.Audience.6.ogg"; Subtitle = "$int.Denounce.Audience.6";};
		3 extends G3SoundDef { Path = "int.Denounce.Audience.7.ogg"; Subtitle = "$int.Denounce.Audience.7";};
	};
};

G3SoundObject
{
	SoundID = 283;	// Audience Boasting - target loved
	Category = 5; // ESoundVoices
	Frequency = 0.1;
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{		
		1 extends G3SoundDef { Path = "int.Praise.Audience.0.ogg"; Subtitle = "$int.Praise.Audience.0";};
		2 extends G3SoundDef { Path = "int.Praise.Audience.1.ogg"; Subtitle = "$int.Praise.Audience.1";};
		3 extends G3SoundDef { Path = "int.Praise.Audience.2.ogg"; Subtitle = "$int.Praise.Audience.2";};
		4 extends G3SoundDef { Path = "int.Praise.Audience.3.ogg"; Subtitle = "$int.Praise.Audience.3";};
		5 extends G3SoundDef { Path = "int.Praise.Audience.4.ogg"; Subtitle = "$int.Praise.Audience.4";};
		6 extends G3SoundDef { Path = "int.Praise.Audience.5.ogg"; Subtitle = "$int.Praise.Audience.5";};
		7 extends G3SoundDef { Path = "int.Praise.Audience.6.ogg"; Subtitle = "$int.Praise.Audience.6";};
	};
};

G3SoundObject
{
	SoundID = 284;	// Audience Boasting - target hated
	Category = 5; // ESoundVoices
	Frequency = 0.1;
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{		
		1 extends G3SoundDef { Path = "int.Denounce.Audience.3.ogg"; Subtitle = "$int.Denounce.Audience.3";};
		2 extends G3SoundDef { Path = "int.Denounce.Audience.7.ogg"; Subtitle = "$int.Denounce.Audience.7";};
	};
};

G3SoundObject
{
	SoundID = 285;	// ACTION - DENOUNCE
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.Denounce.0.narration.ogg"; Subtitle = "$int.Denounce.0.narration";};
		2 extends G3SoundDef { Path = "int.Denounce.1.narration.ogg"; Subtitle = "$int.Denounce.1.narration";};
		3 extends G3SoundDef { Path = "int.Denounce.2.narration.ogg"; Subtitle = "$int.Denounce.2.narration";};
		4 extends G3SoundDef { Path = "int.Denounce.3.narration.ogg"; Subtitle = "$int.Denounce.3.narration";};
		5 extends G3SoundDef { Path = "int.Denounce.4.narration.ogg"; Subtitle = "$int.Denounce.4.narration";};
		6 extends G3SoundDef { Path = "int.Denounce.5.narration.ogg"; Subtitle = "$int.Denounce.5.narration";};
		7 extends G3SoundDef { Path = "int.Denounce.6.narration.ogg"; Subtitle = "$int.Denounce.6.narration";};
		8 extends G3SoundDef { Path = "int.Denounce.7.narration.ogg"; Subtitle = "$int.Denounce.7.narration";};
	};
};

G3SoundObject
{
	SoundID = 286;	// Get Hit sound
	Category = 5; // ESoundVoices
	FalloffStart = 5;
	FalloffEnd = 1900;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "hurt_01.ogg"; Subtitle = "";};
		2 extends G3SoundDef { Path = "hurt_02.ogg"; Subtitle = "";};
		3 extends G3SoundDef { Path = "hurt_03.ogg"; Subtitle = "";};
		4 extends G3SoundDef { Path = "hurt_04.ogg"; Subtitle = "";};
		5 extends G3SoundDef { Path = "hurt_05.ogg"; Subtitle = "";};
	};
};

// Narrator
G3SoundObject
{
	SoundID = 300; // Nobility title purchased
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "action.Praised.Narrator.ogg"; Subtitle = "$action.Praised.Narrator";};
	}; 
};

// Reactions
G3SoundObject
{
	SoundID = 310;
 	Category = 5; // ESoundVoices
	Sounds = array 
	{ 
		1 extends G3SoundDef { Path = "int.Insult.Success.Friendly.0.ogg"; Subtitle = "$int.Insult.Success.Friendly.0";};
	}; 
};
G3SoundObject
{
	SoundID = 311;
 	Category = 5; // ESoundVoices
	Sounds = array 
	{
		1 extends G3SoundDef { Path = "int.Insult.Success.Friendly.3.ogg"; Subtitle = "$int.Insult.Success.Friendly.3";};
	};
};
G3SoundObject
{
	SoundID = 312;
 	Category = 5; // ESoundVoices
	Sounds = array 
	{
		1 extends G3SoundDef { Path = "int.Insult.Success.Normal.2.ogg"; Subtitle = "$int.Insult.Success.Normal.2";}; 
	}; 
};
G3SoundObject
{
	SoundID = 313;
 	Category = 5; // ESoundVoices
	Sounds = array 
	{
		1 extends G3SoundDef { Path = "int.Insult.Success.Normal.3.ogg"; Subtitle = "$int.Insult.Success.Normal.3";};
	};
};
G3SoundObject
{
	SoundID = 314;
 	Category = 5; // ESoundVoices
	Sounds = array 
	{
		1 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Normal.1.ogg"; Subtitle = "$cf.NPC.ToCitizen.Normal.1";}; 
	}; 
};
G3SoundObject
{
	SoundID = 315;
	Category = 5; // ESoundVoices
	Sounds = array 
	{
		1 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Normal.2.ogg"; Subtitle = "$cf.NPC.ToCitizen.Normal.2";};
	};
};
G3SoundObject
{
	SoundID = 316;
 	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Friendly.0.ogg"; Subtitle = "$cf.NPC.ToCommoner.Friendly.0";}; 
	};
};
G3SoundObject
{
	SoundID = 317;
 	Category = 5; // ESoundVoices
	Sounds = array 
	{ 
		1 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Friendly.1.ogg"; Subtitle = "$cf.NPC.ToCommoner.Friendly.1";}; 
	}; 
};
G3SoundObject
{
	SoundID = 318;
 	Category = 5; // ESoundVoices
	Sounds = array
	{ 
		1 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Hatred.3.ogg"; Subtitle = "$cf.NPC.ToCitizen.Hatred.3";}; 
	};
};
G3SoundObject
{
	SoundID = 319;
 	Category = 5; // ESoundVoices
	Sounds = array 
	{
		1 extends G3SoundDef { Path = "cf.NPC.ToCommoner.CityGuard.1.ogg"; Subtitle = "$cf.NPC.ToCommoner.CityGuard.1";}; 
	}; 
};
G3SoundObject
{
	SoundID = 320;
 	Category = 5; // ESoundVoices
	Sounds = array 
	{
		1 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Hatred.3.ogg"; Subtitle = "$cf.NPC.ToCommoner.Hatred.3";};
	}; 
};

// Inn revellers
G3SoundObject
{
	SoundID = 340;
	Category = 5; // ESoundVoices
	Frequency = 0.44;
	FalloffStart = 5;
	FalloffEnd = 1200;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Around.ogg"; Subtitle = "$Cutscenes.TavernTalk.Around";};
		2 extends G3SoundDef { Path = "Cutscenes.TavernTalk.AroundHere.ogg"; Subtitle = "$Cutscenes.TavernTalk.AroundHere";};
		3 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Drink.ogg"; Subtitle = "$Cutscenes.TavernTalk.Drink";};
		4 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Girl.ogg"; Subtitle = "$Cutscenes.TavernTalk.Girl";};
		5 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Guy.ogg"; Subtitle = "$Cutscenes.TavernTalk.Guy";};
		6 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Innkeeper.ogg"; Subtitle = "$Cutscenes.TavernTalk.Innkeeper";};
		7 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Phew.ogg"; Subtitle = "$Cutscenes.TavernTalk.Phew";};
		8 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Stranger.ogg"; Subtitle = "$Cutscenes.TavernTalk.Stranger";};
		9 extends G3SoundDef { Path = "Cutscenes.TavernTalk.TakeASeat.ogg"; Subtitle = "$Cutscenes.TavernTalk.TakeASeat";};
		10 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Thirsty.ogg"; Subtitle = "$Cutscenes.TavernTalk.Thirsty";};
		11 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Tired.ogg"; Subtitle = "$Cutscenes.TavernTalk.Tired";};
		12 extends G3SoundDef { Path = "Cutscenes.TavernTalk.Weather.ogg"; Subtitle = "$Cutscenes.TavernTalk.Weather";};
	};
};

// InnDiceGame
G3SoundObject
{
	SoundID = 341;
	Category = 5; // ESoundVoices
	Frequency = 0.66;
	FalloffStart = 5;
	FalloffEnd = 1200;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.DiceGame.Money.ogg"; Subtitle = "$Cutscenes.DiceGame.Money";};
		2 extends G3SoundDef { Path = "Cutscenes.DiceGame.Blasted.ogg"; Subtitle = "$Cutscenes.DiceGame.Blasted";};
		3 extends G3SoundDef { Path = "Cutscenes.DiceGame.Might.ogg"; Subtitle = "$Cutscenes.DiceGame.Might";};
		4 extends G3SoundDef { Path = "Cutscenes.DiceGame.Shame.ogg"; Subtitle = "$Cutscenes.DiceGame.Shame";};
		5 extends G3SoundDef { Path = "Cutscenes.DiceGame.SoClose.ogg"; Subtitle = "$Cutscenes.DiceGame.SoClose";};
	};
};

// Healing Service
G3SoundObject
{
	SoundID = 342;
	Category = 5; // ESoundVoices
	Frequency = 0.20;
	FalloffStart = 5;
	FalloffEnd = 1200;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Medicus.Cost.ogg"; Subtitle = "$Cutscenes.Medicus.Cost";};
		2 extends G3SoundDef { Path = "Cutscenes.Medicus.Enemies.ogg"; Subtitle = "$Cutscenes.Medicus.Enemies";};
		3 extends G3SoundDef { Path = "Cutscenes.Medicus.Ish.ogg"; Subtitle = "$Cutscenes.Medicus.Ish";};
		4 extends G3SoundDef { Path = "Cutscenes.Medicus.Offend.ogg"; Subtitle = "$Cutscenes.Medicus.Offend";};
		5 extends G3SoundDef { Path = "Cutscenes.Medicus.OhMy.ogg"; Subtitle = "$Cutscenes.Medicus.OhMy";};
		6 extends G3SoundDef { Path = "Cutscenes.Medicus.OhRight.ogg"; Subtitle = "$Cutscenes.Medicus.OhRight";};
	};
};

// TakeBathHome
G3SoundObject
{
	SoundID = 343; // lalala while in the tub
	Category = 5; // ESoundVoices
	Volume = 0.4;
	FalloffStart = 5;
	FalloffEnd = 1200;
	Frequency = 0.25;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Normal.5.ogg"; Subtitle = "";};
		2 extends G3SoundDef { Path = "cf.NPC.ToCommoner.Normal.4.ogg"; Subtitle = "";};
	}; 
};

// Church Wedding
G3SoundObject
{
	SoundID = 344;
	Category = 5; // ESoundVoices
	Volume = 1.0;
	FalloffStart = 400;
	FalloffEnd = 1800;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.scene.wedding.Priest.Intro.Narration.ogg"; Subtitle = "$d.scene.wedding.Priest.Intro";};
	};
};
G3SoundObject
{
	SoundID = 345;
	Category = 5; // ESoundVoices
	Volume = 1.0;
	FalloffStart = 400;
	FalloffEnd = 1800;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.scene.wedding.Priest.toHusband.Narration.ogg"; Subtitle = "$d.scene.wedding.Priest.toHusband";};
	};
};
G3SoundObject
{
	SoundID = 346;
	Category = 5; // ESoundVoices
	Volume = 1.0;
	FalloffStart = 400;
	FalloffEnd = 1800;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.scene.wedding.Player.Answer.ogg"; Subtitle = "d.scene.wedding.Player.Answer";};
	};
};
G3SoundObject
{
	SoundID = 347;
	Category = 5; // ESoundVoices
	Volume = 1.0;
	FalloffStart = 400;
	FalloffEnd = 1800;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.scene.wedding.Priest.toWife.Narration.ogg"; Subtitle = "$d.scene.wedding.Priest.toWife";};
	};
};
G3SoundObject
{
	SoundID = 348;
	Category = 5; // ESoundVoices
	Volume = 1.0;
	FalloffStart = 400;
	FalloffEnd = 1800;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.scene.wedding.Priest.Finale.Narration.ogg"; Subtitle = "$d.scene.wedding.Priest.Finale";};
	};
};
G3SoundObject
{
	SoundID = 349;
	Category = 5; // ESoundVoices
	Volume = 1.0;
	FalloffStart = 400;
	FalloffEnd = 1800;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.act.TalkToPriest.PositiveFeedback.ogg"; Subtitle = "$d.act.TalkToPriest.PositiveFeedback";};
	};
};

// fiance is happy when player declares a church wedding will happen
G3SoundObject
{
	SoundID = 350;
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cf.NPC.ToNoble.Friendly.0.ogg"; Subtitle = "$cf.NPC.ToNoble.Friendly.0";};
	};
};

// Master of the Arsenal (MoA)
G3SoundObject
{
	SoundID = 351;	// welcome
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.MoA.welcome.ogg"; Subtitle = "$avr.MoA.welcome";};
	};
};

// Jailor dialogue - Welcome
G3SoundObject
{
	SoundID = 352;	// What do you want?
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cf.FAvatar.Enemy.0.ogg"; Subtitle = "$cf.FAvatar.Enemy.0";};
	};
};

// Jailor dialogue - Kid speaking
G3SoundObject
{
	SoundID = 353;	// When I grow up I want to be an executioner.
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cf.Child.EE.0.ogg"; Subtitle = "$cf.Child.EE.0";};
	};
};

// Jailor dialogue - answer
G3SoundObject
{
	SoundID = 354;	// Good
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cf.OEmpl.HM.Confirm.3.ogg"; Subtitle = "$cf.OEmpl.HM.Confirm.3";};
	};
};

// Prisoner comments
G3SoundObject
{
	SoundID = 355;
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cf.Avatar.Groggy.0.ogg"; Subtitle = "$cf.Avatar.Groggy.0";};
		2 extends G3SoundDef { Path = "cf.Avatar.Groggy.1.ogg"; Subtitle = "$cf.Avatar.Groggy.1";};
		3 extends G3SoundDef { Path = "cf.OEmpl.Culi.1.ogg"; Subtitle = "$cf.OEmpl.Culi.1";};
		4 extends G3SoundDef { Path = "cf.OEmpl.Culi.2.ogg"; Subtitle = "$cf.OEmpl.Culi.2";};
		5 extends G3SoundDef { Path = "cf.OTrans.0.ogg"; Subtitle = "$cf.OTrans.0";};
		6 extends G3SoundDef { Path = "Cutscenes.Trial.Travesty.ogg"; Subtitle = "$Cutscenes.Trial.Travesty";};
		7 extends G3SoundDef { Path = "Cutscenes.Trial.Imbeciles.ogg"; Subtitle = "$Cutscenes.Trial.Imbeciles";};
		8 extends G3SoundDef { Path = "Cutscenes.Trial.God.ogg"; Subtitle = "$Cutscenes.Trial.God";};
		9 extends G3SoundDef { Path = "Cutscenes.Trial.Rogue.ogg"; Subtitle = "$Cutscenes.Trial.Rogue";};
		10 extends G3SoundDef { Path = "avr.arsenal.Prisoner.Comment.1.ogg"; Subtitle = "$avr.arsenal.Prisoner.Comment.1";};
		11 extends G3SoundDef { Path = "avr.arsenal.Prisoner.Comment.2.ogg"; Subtitle = "$avr.arsenal.Prisoner.Comment.2";};
		12 extends G3SoundDef { Path = "avr.arsenal.Prisoner.Comment.3.ogg"; Subtitle = "$avr.arsenal.Prisoner.Comment.3";};
	};
};

// Jailor reacts on prisoner comments
G3SoundObject
{
	SoundID = 356;
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Execution.bad3.ogg"; Subtitle = "$Cutscenes.Execution.bad3";};
		2 extends G3SoundDef { Path = "int.Insult.Duel.Normal.3.ogg"; Subtitle = "$int.Insult.Duel.Normal.3";};
		3 extends G3SoundDef { Path = "int.Positive.Failure.Hatred.1.ogg"; Subtitle = "$int.Positive.Failure.Hatred.1";};
		4 extends G3SoundDef { Path = "avr.arsenal.Jailer.Comment.1.ogg"; Subtitle = "$avr.arsenal.Jailer.Comment.1";};
		5 extends G3SoundDef { Path = "avr.arsenal.Jailer.Comment.2.ogg"; Subtitle = "$avr.arsenal.Jailer.Comment.2";};
		6 extends G3SoundDef { Path = "avr.arsenal.Jailer.Comment.3.ogg"; Subtitle = "$avr.arsenal.Jailer.Comment.3";};
	};
};

// NPC speaks: character does not have enough money or influence points or something else blocks him/her from initiating an action via dialogue
G3SoundObject
{
	SoundID = 357;
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cf.FEmpl.Allied.0.ogg"; Subtitle = "$cf.FEmpl.Allied.0";}; // Please excuse me…
	};
};

// NPC speaks: character initiates an action via dialogue
G3SoundObject
{
	SoundID = 358;
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cf.OEmpl.Confirm.3.ogg"; Subtitle = "$cf.OEmpl.Confirm.3";}; // so be it
	};
};

G3SoundObject
{
	SoundID = 359;	// Court - Hear the defendent
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "Cutscenes.Trial.TheCourt.ogg"; Subtitle = "$Cutscenes.Trial.TheCourt";};
	};
};

// new voice takes
G3SoundObject
{
	SoundID = 370; // Narrator: a family member returns home
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.arsenal.event.allguilds.character.returns.title2.ogg"; Subtitle = "$n.arsenal.event.allguilds.character.returns.title2";};
	};
};

G3SoundObject
{
	SoundID = 371; // Narrator: a worker returns home
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.arsenal.event.allguilds.worker.returns.title.ogg"; Subtitle = "$n.arsenal.event.allguilds.worker.returns.title";};
	};
};

G3SoundObject
{
	SoundID = 372; // Narrator: a war is imminent
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.arsenal.event.war.title.ogg"; Subtitle = "$n.arsenal.event.war.title";};
	};
};

G3SoundObject
{
	SoundID = 373; // Narrator: a war is won
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.arsenal.event.war.won.title.ogg"; Subtitle = "$n.arsenal.event.war.won.title";};
	};
};

G3SoundObject
{
	SoundID = 374; // Narrator: a war is lost
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.arsenal.event.war.defeat.title.ogg"; Subtitle = "$n.arsenal.event.war.defeat.title";};
	};
};

G3SoundObject
{
	SoundID = 375; // Narrator: a war ends with a truce
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.arsenal.event.war.truce.title.ogg"; Subtitle = "$n.arsenal.event.war.truce.title";};
	};
};

G3SoundObject
{
	SoundID = 376; // Narrator: MerchantsGuild event
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.arsenal.event.MerchantsGuild.title.ogg"; Subtitle = "$n.arsenal.event.MerchantsGuild.title";};
	};
};

G3SoundObject
{
	SoundID = 377; // Narrator: Freemasons event
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.arsenal.event.Freemasons.title.ogg"; Subtitle = "$n.arsenal.event.Freemasons.title";};
	};
};

G3SoundObject
{
	SoundID = 378; // Narrator: Alchimists event
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.arsenal.event.Alchimists.title.ogg"; Subtitle = "$n.arsenal.event.Alchimists.title";};
	};
};

G3SoundObject
{
	SoundID = 379; // Narrator: CraftmensGuild event
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.arsenal.event.CraftmensGuild.title.ogg"; Subtitle = "$n.arsenal.event.CraftmensGuild.title";};
	};
};

G3SoundObject
{
	SoundID = 380; // Narrator: ThievesGuild event
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.arsenal.event.ThievesGuild.title.ogg"; Subtitle = "$n.arsenal.event.ThievesGuild.title";};
	};
};


G3SoundObject
{
	SoundID = 381; // MoA
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.arsenal.event.general.notpossible.ogg"; Subtitle = "$avr.arsenal.event.general.notpossible";};
	};
};

G3SoundObject
{
	SoundID = 382; // MoA
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.arsenal.event.general.LeaderPregnant.ogg"; Subtitle = "$avr.arsenal.event.general.LeaderPregnant";};
	};
};

G3SoundObject
{
	SoundID = 383; // Player to MoA
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.arsenal.event.war.Player.option.ogg"; Subtitle = "$avr.arsenal.event.war.Player.option";};
	};
};

G3SoundObject
{
	SoundID = 384; // MoA to Player
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.arsenal.event.war.NPC.answer.war.ogg"; Subtitle = "$avr.arsenal.event.war.NPC.answer.war";};
	};
};

G3SoundObject
{
	SoundID = 385; // MoA to Player
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.arsenal.event.war.NPC.answer.positive.ogg"; Subtitle = "$avr.arsenal.event.war.NPC.answer.positive";};
	};
};

G3SoundObject
{
	SoundID = 386; // MoA to Player
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.arsenal.event.general.NPC.rating.bad.ogg"; Subtitle = "$d.arsenal.event.general.NPC.rating.bad";};
	};
};

G3SoundObject
{
	SoundID = 387; // MoA to Player
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.arsenal.event.general.NPC.rating.average.ogg"; Subtitle = "$d.arsenal.event.general.NPC.rating.average";};
	};
};

G3SoundObject
{
	SoundID = 388; // MoA to Player
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.arsenal.event.general.NPC.rating.good.ogg"; Subtitle = "$d.arsenal.event.general.NPC.rating.good";};
	};
};


G3SoundObject
{
	SoundID = 389; // Player to MoA
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.arsenal.event.MerchantsGuild.Player.option.ogg"; Subtitle = "$d.arsenal.event.MerchantsGuild.Player.option";};
	};
};
G3SoundObject
{
	SoundID = 390; // MoA to Player
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.arsenal.event.MerchantsGuild.NPC.answer.ogg"; Subtitle = "$d.arsenal.event.MerchantsGuild.NPC.answer";};
	};
};

G3SoundObject
{
	SoundID = 391; // MoA to Player
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.arsenal.event.guilds.NPC.answer.positive.ogg"; Subtitle = "$avr.arsenal.event.guilds.NPC.answer.positive";};
	};
};

G3SoundObject
{
	SoundID = 392; // Player to MoA
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.arsenal.event.Freemasons.Player.option.ogg"; Subtitle = "$d.arsenal.event.Freemasons.Player.option";};
	};
};
G3SoundObject
{
	SoundID = 393; // MoA to Player
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.arsenal.event.Freemasons.NPC.answer.ogg"; Subtitle = "$d.arsenal.event.Freemasons.NPC.answer";};
	};
};

G3SoundObject
{
	SoundID = 394; // Player to MoA
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.arsenal.event.Alchimists.Player.option.ogg"; Subtitle = "$d.arsenal.event.Alchimists.Player.option";};
	};
};
G3SoundObject
{
	SoundID = 395; // MoA to Player
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.arsenal.event.Alchimists.NPC.answer.ogg"; Subtitle = "$d.arsenal.event.Alchimists.NPC.answer";};
	};
};

G3SoundObject
{
	SoundID = 396; // Player to MoA
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.arsenal.event.CraftmensGuild.Player.option.ogg"; Subtitle = "$d.arsenal.event.CraftmensGuild.Player.option";};
	};
};
G3SoundObject
{
	SoundID = 397; // MoA to Player
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.arsenal.event.CraftmensGuild.NPC.answer.ogg"; Subtitle = "$d.arsenal.event.CraftmensGuild.NPC.answer";};
	};
};

G3SoundObject
{
	SoundID = 398; // Player to MoA
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.arsenal.event.ThievesGuild.Player.option.ogg"; Subtitle = "$d.arsenal.event.ThievesGuild.Player.option";};
	};
};
G3SoundObject
{
	SoundID = 399; // MoA to Player
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "d.arsenal.event.ThievesGuild.NPC.answer.ogg"; Subtitle = "$d.arsenal.event.ThievesGuild.NPC.answer";};
	};
};

G3SoundObject
{
	SoundID = 400; // Player to MoA - ReleasePrisoner
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.ReleasePrisoner.Player.option.ogg"; Subtitle = "$avr.ReleasePrisoner.Player.option";};
	};
};

G3SoundObject
{
	SoundID = 401; // MoA to Player - ReleasePrisoner
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.ReleasePrisoner.NPC.answer.ogg"; Subtitle = "$avr.ReleasePrisoner.NPC.answer";};
	};
};

G3SoundObject
{
	SoundID = 402; // InstantWedding Opening - male to female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.InstantWedding.opening.male.ogg"; Subtitle = "$avr.InstantWedding.opening.male";};
	};
};
G3SoundObject
{
	SoundID = 403; // InstantWedding Opening - female to male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.InstantWedding.opening.female.ogg"; Subtitle = "$avr.InstantWedding.opening.female";};
	};
};
G3SoundObject
{
	SoundID = 404; // InstantWedding - unholy wedding, are you sure?
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.InstantWedding.UnholyMarriage.both.ogg"; Subtitle = "$avr.InstantWedding.UnholyMarriage.both";};
	};
};
G3SoundObject
{
	SoundID = 405; // YES
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.General.Yes.both.ogg"; Subtitle = "$avr.General.Yes.both";};
	};
};
G3SoundObject
{
	SoundID = 406; // NO
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.General.No.both.ogg"; Subtitle = "$avr.General.No.both";};
	};
};

G3SoundObject
{
	SoundID = 409; // proposeMarriage - male to female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.proposeMarriage.opening.1.male.ogg"; Subtitle = "$avr.proposeMarriage.opening.1.male"; Weight = 45;};
		2 extends G3SoundDef { Path = "avr.proposeMarriage.opening.2.male.ogg"; Subtitle = "$avr.proposeMarriage.opening.2.male"; Weight = 45;};
		3 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.CleaningMyHouse.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.CleaningMyHouse"; Weight = 2;};
		4 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.GoOnLiving.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.GoOnLiving"; Weight = 2;};
		5 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.Hungry.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.Hungry"; Weight = 2;};
		6 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.KindOfWoman.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.KindOfWoman"; Weight = 2;};
		7 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.MyLife.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.MyLife"; Weight = 2;};
	};
};
G3SoundObject
{
	SoundID = 410; // proposeMarriage - female to male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.proposeMarriage.opening.1.female.ogg"; Subtitle = "$avr.proposeMarriage.opening.1.female"; Weight = 45;};
		2 extends G3SoundDef { Path = "avr.proposeMarriage.opening.2.female.ogg"; Subtitle = "$avr.proposeMarriage.opening.2.female"; Weight = 45;};
		3 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.Family.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.Family"; Weight = 2;};
		4 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.GoodHusband.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.GoodHusband"; Weight = 2;};
		5 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.FreeOfDisease.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.FreeOfDisease"; Weight = 2;};
		6 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.KindOfMan.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.KindOfMan"; Weight = 2;};
		7 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.GoodSir.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.GoodSir"; Weight = 2;};
	};
};
G3SoundObject
{
	SoundID = 411; // ChurchWedding Opening - male to female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.ChurchWedding.opening.male.ogg"; Subtitle = "$avr.ChurchWedding.opening.male";};
	};
};
G3SoundObject
{
	SoundID = 412; // ChurchWedding Opening - female to male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.ChurchWedding.opening.female.ogg"; Subtitle = "$avr.ChurchWedding.opening.female";};
	};
};
G3SoundObject
{
	SoundID = 413; // proposeMarriage - yes
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.proposeMarriage.answer.success.both.ogg"; Subtitle = "$avr.proposeMarriage.answer.success.both";};
	};
};
G3SoundObject
{
	SoundID = 414; // proposeMarriage - no
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.proposeMarriage.answer.failure.both.ogg"; Subtitle = "$avr.proposeMarriage.answer.failure.both";};
	};
};

G3SoundObject
{
	SoundID = 415; // InstantWedding - agreed, female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.InstantWedding.answer.success.female.ogg"; Subtitle = "$avr.InstantWedding.answer.success.female";};
	};
};
G3SoundObject
{
	SoundID = 416; // InstantWedding - agreed, male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.InstantWedding.answer.success.male.ogg"; Subtitle = "$avr.InstantWedding.answer.success.male";};
	};
};
G3SoundObject
{
	SoundID = 417; // ChurchWedding - agreed, female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.ChurchWedding.answer.success.female.ogg"; Subtitle = "$avr.ChurchWedding.answer.success.female";};
	};
};
G3SoundObject
{
	SoundID = 418; // ChurchWedding - agreed, male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.ChurchWedding.answer.success.male.ogg"; Subtitle = "$avr.ChurchWedding.answer.success.male";};
	};
};
G3SoundObject
{
	SoundID = 419; // Marriage - vow male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.InstantWedding.vow.male.ogg"; Subtitle = "$avr.InstantWedding.vow.male";};
	};
};
G3SoundObject
{
	SoundID = 420; // Marriage - vow female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.InstantWedding.vow.female.ogg"; Subtitle = "$avr.InstantWedding.vow.female";};
	};
};
G3SoundObject
{
	SoundID = 421; // I want to adopt an orphan
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.TalkToPriest.BuyOrphan.ogg"; Subtitle = "$avr.TalkToPriest.BuyOrphan";};
	};
};
G3SoundObject
{
	SoundID = 422; // no adoption possible - too many children
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.TalkToPriest.tooMuchChildren.ogg"; Subtitle = "$avr.TalkToPriest.tooMuchChildren";};
	};
};
G3SoundObject
{
	SoundID = 423; // dialogue action not possible
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Receptionist.NPC.Answer.Negative.ogg"; Subtitle = "$avr.Receptionist.NPC.Answer.Negative";};
	};
};
G3SoundObject
{
	SoundID = 424; // Cannot Get Married
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.TalkToPriest.CannotGetMarried.ogg"; Subtitle = "$avr.TalkToPriest.CannotGetMarried";};
	};
};
G3SoundObject
{
	SoundID = 425; // Are you sure you want to continue?
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.TalkToPriest.UnholyMarriage.ogg"; Subtitle = "$avr.TalkToPriest.UnholyMarriage";};
	};
};
G3SoundObject
{
	SoundID = 426; // notification: A wedding is taking place!
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "notification.ChurchWedding.title.ogg"; Subtitle = "$notification.ChurchWedding.title";};
	};
};
G3SoundObject
{
	SoundID = 427; // notification: A family member has levelled up!
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "notification.FamilyMemberLevelUp.ogg"; Subtitle = "$notification.FamilyMemberLevelUp";};
	};
};
G3SoundObject
{
	SoundID = 428; // notification: A family member has been released from the jail!
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.character.releasedfromjail.title.ogg"; Subtitle = "$n.character.releasedfromjail.title";};
	};
};
G3SoundObject
{
	SoundID = 429; // notification: Someone is expecting a baby!
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "pregnancy.NotificationSuccess.Headline.ogg"; Subtitle = "$pregnancy.NotificationSuccess.Headline";};
	};
};
G3SoundObject
{
	SoundID = 430; // notification: Your candidature was successful!
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.politics.OfficeWin.Title.ogg"; Subtitle = "$message.politics.OfficeWin.Title";};
	};
};
G3SoundObject
{
	SoundID = 431; // notification: Your candidature has been rejected!
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.politics.OfficeRejected.Title.ogg"; Subtitle = "$message.politics.OfficeRejected.Title";};
	};
};
G3SoundObject
{
	SoundID = 432; // notification: Your trade proposal is perfect!
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "notification.DynastyTradeAccepted.ogg"; Subtitle = "$notification.DynastyTradeAccepted";};
	};
};
G3SoundObject
{
	SoundID = 433; // notification: Your trade proposal was not accepted!
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "notification.DynastyTradeRejected.ogg"; Subtitle = "$notification.DynastyTradeRejected";};
	};
};

// town receptionist
G3SoundObject
{
	SoundID = 434; // the Town Receptionist greets the player
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Receptionist.welcome.ogg"; Subtitle = "$avr.Receptionist.welcome";};
	};
};
G3SoundObject
{
	SoundID = 435; // the player speaks to the townhall receptionist
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Receptionist.Player.option.Title.ogg"; Subtitle = "$avr.Receptionist.Player.option.Title";};
	};
};
G3SoundObject
{
	SoundID = 436; // the player speaks to the townhall receptionist
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Receptionist.Player.option.Office.ogg"; Subtitle = "$avr.Receptionist.Player.option.Office";};
	};
};
G3SoundObject
{
	SoundID = 437; // the player speaks to the townhall receptionist
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Receptionist.Player.option.OfficeMeeting.ogg"; Subtitle = "$avr.Receptionist.Player.option.OfficeMeeting";};
	};
};
G3SoundObject
{
	SoundID = 438; // the player speaks to the townhall receptionist
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Receptionist.Player.option.Lawsuit.ogg"; Subtitle = "$avr.Receptionist.Player.option.Lawsuit";};
	};
};
G3SoundObject
{
	SoundID = 439; // the townhall receptionist answers the player
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Receptionist.NPC.Answer.Positive.ogg"; Subtitle = "$avr.Receptionist.NPC.Answer.Positive";};
	};
};

G3SoundObject
{
	SoundID = 440; // BribeOfficeHolder Opening
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.bribe.opening.both.ogg"; Subtitle = "$avr.bribe.opening.both";};
	};
};
G3SoundObject
{
	SoundID = 441; // BribeOfficeHolder critical success
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.bribe.answer.success.critical.both.ogg"; Subtitle = "$avr.bribe.answer.success.critical.both";};
	};
};
G3SoundObject
{
	SoundID = 442; // BribeOfficeHolder success
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.bribe.answer.success.normal.both.ogg"; Subtitle = "$avr.bribe.answer.success.normal.both";};
	};
};
G3SoundObject
{
	SoundID = 443; // BribeOfficeHolder failure
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.bribe.answer.failure.normal.both.ogg"; Subtitle = "$avr.bribe.answer.failure.normal.both";};
	};
};
G3SoundObject
{
	SoundID = 444; // BribeOfficeHolder critical failure
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.bribe.answer.failure.critical.both.ogg"; Subtitle = "$avr.bribe.answer.failure.critical.both";};
	};
};

G3SoundObject
{
	SoundID = 445; // GoCampaigning Opening
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.goCamp.opening.both.ogg"; Subtitle = "$avr.goCamp.opening.both";};
	};
};
G3SoundObject
{
	SoundID = 446; // GoCampaigning success
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.goCamp.answer.success.both.ogg"; Subtitle = "$avr.goCamp.answer.success.both";};
	};
};
G3SoundObject
{
	SoundID = 447; // GoCampaigning failure
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.goCamp.answer.failure.both.ogg"; Subtitle = "$avr.goCamp.answer.failure.both";};
	};
};

G3SoundObject
{
	SoundID = 448; // PublicShaming Opening
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.PuplicShaming.opening.both.ogg"; Subtitle = "$avr.PuplicShaming.opening.both";};
	};
};
G3SoundObject
{
	SoundID = 449; // PublicShaming critical success & success
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.PuplicShaming.answer.success.both.ogg"; Subtitle = "$avr.PuplicShaming.answer.success.both";};
	};
};
G3SoundObject
{
	SoundID = 450; // PublicShaming failure & critical failure
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.Denounce.Victim.0.ogg"; Subtitle = "$int.Denounce.Victim.0";};
	};
};

G3SoundObject
{
	SoundID = 451; // PublicPraise Opening
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.PublicPraise.opening.both.ogg"; Subtitle = "$avr.PublicPraise.opening.both";};
	};
};
G3SoundObject
{
	SoundID = 452; // PublicPraise critical success & success
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.PublicPraise.answer.success.both.ogg"; Subtitle = "$avr.PublicPraise.answer.success.both";};
	};
};
G3SoundObject
{
	SoundID = 453; // PublicPraise failure & critical failure
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.PublicPraise.answer.failure.both.ogg"; Subtitle = "$avr.PublicPraise.answer.failure.both";};
	};
};

// trial scene
G3SoundObject
{
	SoundID = 454; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.Intro.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.Intro";};
	};
};
G3SoundObject
{
	SoundID = 455; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.LetAccuserSpeak.toMale.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.LetAccuserSpeak.toMale";};
	};
};
G3SoundObject
{
	SoundID = 456; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.LetAccuserSpeak.toFemale.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.LetAccuserSpeak.toFemale";};
	};
};
G3SoundObject
{
	SoundID = 457; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.AccuserNotPresent.MaleAccused.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.AccuserNotPresent.MaleAccused";};
	};
};
G3SoundObject
{
	SoundID = 458; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.AccuserNotPresent.FemaleAccused.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.AccuserNotPresent.FemaleAccused";};
	};
};
G3SoundObject
{
	SoundID = 459; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.General.Closed.ogg"; Subtitle = "$avr.Cutscene.General.Closed";};
	};
};
G3SoundObject
{
	SoundID = 460; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Accuser.Intro.ogg"; Subtitle = "$avr.Cutscene.Trial.Accuser.Intro";};
	};
};
G3SoundObject
{
	SoundID = 461; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Accuser.Expectation.Mild.ogg"; Subtitle = "$avr.Cutscene.Trial.Accuser.Expectation.Mild";};
	};
};
G3SoundObject
{
	SoundID = 462; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Accuser.Expectation.Fair.ogg"; Subtitle = "$avr.Cutscene.Trial.Accuser.Expectation.Fair";};
	};
};
G3SoundObject
{
	SoundID = 463; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Accuser.Expectation.Hard.ogg"; Subtitle = "$avr.Cutscene.Trial.Accuser.Expectation.Hard";};
	};
};
G3SoundObject
{
	SoundID = 464; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.LetAccusedSpeak.toMale.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.LetAccusedSpeak.toMale";};
	};
};
G3SoundObject
{
	SoundID = 465; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.LetAccusedSpeak.toFemale.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.LetAccusedSpeak.toFemale";};
	};
};

G3SoundObject
{
	SoundID = 466; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.AskAccused.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.AskAccused";};
	};
};
G3SoundObject
{
	SoundID = 467; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Player.Option.NotGuilty.ogg"; Subtitle = "$avr.Cutscene.Trial.Player.Option.NotGuilty";};
	};
};
G3SoundObject
{
	SoundID = 468; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Player.Option.Guilty.ogg"; Subtitle = "$avr.Cutscene.Trial.Player.Option.Guilty";};
	};
};
G3SoundObject
{
	SoundID = 469; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.AccusedNotPresent.MaleAccused.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.AccusedNotPresent.MaleAccused";};
	};
};
G3SoundObject
{
	SoundID = 470; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.AccusedNotPresent.FemaleAccused.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.AccusedNotPresent.FemaleAccused";};
	};
};
G3SoundObject
{
	SoundID = 471; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.Judgement.Guilty.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.Judgement.Guilty";};
	};
};
G3SoundObject
{
	SoundID = 472; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.Judgement.NotGuilty.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.Judgement.NotGuilty";};
	};
};
G3SoundObject
{
	SoundID = 473; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.Judgement.Intro.toMale.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.Judgement.Intro.toMale";};
	};
};
G3SoundObject
{
	SoundID = 474; // 
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.Trial.Judge.Judgement.Intro.toFemale.ogg"; Subtitle = "$avr.Cutscene.Trial.Judge.Judgement.Intro.toFemale";};
	};
};

G3SoundObject
{
	SoundID = 475; // LureIntoRumDen opening
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.LureIntoRumDen.opening.both.ogg"; Subtitle = "$avr.LureIntoRumDen.opening.both";};
	};
};
G3SoundObject
{
	SoundID = 476; // LureIntoRumDen success
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.LureIntoRumDen.answer.success.both.ogg"; Subtitle = "$avr.LureIntoRumDen.answer.success.both";};
	};
};
G3SoundObject
{
	SoundID = 477; // LureIntoRumDen failure
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.LureIntoRumDen.answer.failure.both.ogg"; Subtitle = "$avr.LureIntoRumDen.answer.failure.both";};
	};
};

G3SoundObject
{
	SoundID = 478; // StartRomance opening intelligence male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.embRom.opening.intelligence.male.ogg"; Subtitle = "$avr.embRom.opening.intelligence.male"; Weight = 8;};
		2 extends G3SoundDef { Path = "Cutscenes.Reputation.Inspiration.ogg"; Subtitle = "$Cutscenes.Reputation.Inspiration"; Weight = 2;};
		3 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.MyLife.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.MyLife"; Weight = 2;};
	};
};
G3SoundObject
{
	SoundID = 479; // StartRomance opening intelligence female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.embRom.opening.intelligence.female.ogg"; Subtitle = "$avr.embRom.opening.intelligence.female"; Weight = 8;};
		2 extends G3SoundDef { Path = "Cutscenes.Reputation.Inspiration.ogg"; Subtitle = "$Cutscenes.Reputation.Inspiration"; Weight = 2;};
		3 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.GoodSir.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.GoodSir"; Weight = 2;};

	};
};
G3SoundObject
{
	SoundID = 480; // StartRomance opening charisma male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.embRom.opening.charisma.male.ogg"; Subtitle = "$avr.embRom.opening.charisma.male"; Weight = 8;};
		2 extends G3SoundDef { Path = "Cutscenes.Reputation.BlessedYou.ogg"; Subtitle = "$Cutscenes.Reputation.BlessedYou"; Weight = 2;};
		3 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.RadiantBeauty.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.RadiantBeauty"; Weight = 2;};
	};
};
G3SoundObject
{
	SoundID = 481; // StartRomance opening charisma female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.embRom.opening.charisma.female.ogg"; Subtitle = "$avr.embRom.opening.charisma.female"; Weight = 8;};
		2 extends G3SoundDef { Path = "Cutscenes.Reputation.BlessedYou.ogg"; Subtitle = "$Cutscenes.Reputation.BlessedYou"; Weight = 2;};
		3 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.SoStrong.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.SoStrong"; Weight = 2;};
	};
};
G3SoundObject
{
	SoundID = 482; // StartRomance opening perception male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.embRom.opening.perception.male.ogg"; Subtitle = "$avr.embRom.opening.perception.male"; Weight = 8;};
		2 extends G3SoundDef { Path = "Cutscenes.Reputation.EveryDay.ogg"; Subtitle = "$Cutscenes.Reputation.EveryDay"; Weight = 2;};
		3 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.GoOnLiving.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.GoOnLiving"; Weight = 2;};
	};
};
G3SoundObject
{
	SoundID = 483; // StartRomance opening perception female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.embRom.opening.perception.female.ogg"; Subtitle = "$avr.embRom.opening.perception.female"; Weight = 8;};
		2 extends G3SoundDef { Path = "Cutscenes.Reputation.EveryDay.ogg"; Subtitle = "$Cutscenes.Reputation.EveryDay"; Weight = 2;};
		3 extends G3SoundDef { Path = "Cutscenes.ComplimentSpouse.FreeOfDisease.ogg"; Subtitle = "$Cutscenes.ComplimentSpouse.FreeOfDisease"; Weight = 2;};
	};
};
G3SoundObject
{
	SoundID = 484; // StartRomance critical success
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.embRom.answer.success.critical.both.ogg"; Subtitle = "$avr.embRom.answer.success.critical.both";};
	};
};
G3SoundObject
{
	SoundID = 485; // StartRomance success
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.embRom.answer.success.normal.both.ogg"; Subtitle = "$avr.embRom.answer.success.normal.both";};
	};
};
G3SoundObject
{
	SoundID = 486; // StartRomance failure
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.embRom.answer.failure.normal.both.ogg"; Subtitle = "$avr.embRom.answer.failure.normal.both";};
	};
};
G3SoundObject
{
	SoundID = 487; // StartRomance critical failure
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.embRom.answer.failure.critical.both.ogg"; Subtitle = "$avr.embRom.answer.failure.critical.both";};
	};
};

G3SoundObject
{
	SoundID = 488; // StartLiaison intelligence male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.startLia.opening.intelligence.male.ogg"; Subtitle = "$avr.startLia.opening.intelligence.male";};
	};
};
G3SoundObject
{
	SoundID = 489; // StartLiaison charisma male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.startLia.opening.charisma.male.ogg"; Subtitle = "$avr.startLia.opening.charisma.male";};
	};
};
G3SoundObject
{
	SoundID = 490; // StartLiaison perception male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.startLia.opening.perception.male.ogg"; Subtitle = "$avr.startLia.opening.perception.male";};
	};
};
G3SoundObject
{
	SoundID = 491; // StartLiaison intelligence female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.startLia.opening.intelligence.female.ogg"; Subtitle = "$avr.startLia.opening.intelligence.female";};
	};
};
G3SoundObject
{
	SoundID = 492; // StartLiaison charisma female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.startLia.opening.charisma.female.ogg"; Subtitle = "$avr.startLia.opening.charisma.female";};
	};
};
G3SoundObject
{
	SoundID = 493; // StartLiaison perception female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.startLia.opening.perception.female.ogg"; Subtitle = "$avr.startLia.opening.perception.female";};
	};
};

G3SoundObject
{
	SoundID = 494; // CourtingSomeone perception male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.court.opening.perception.male.ogg"; Subtitle = "$avr.court.opening.perception.male"; Weight = 6;};
		2 extends G3SoundDef { Path = "cf.Liaison.Med.2.ogg"; Subtitle = "$cf.Liaison.Med.2"; Weight = 2;};
		3 extends G3SoundDef { Path = "int.Compliment.2.ogg"; Subtitle = "$int.Compliment.2"; Weight = 2;};
		4 extends G3SoundDef { Path = "Cutscenes.Reputation.YourFamily.ogg"; Subtitle = "$Cutscenes.Reputation.YourFamily"; Weight = 1;};
	};
};
G3SoundObject
{
	SoundID = 495; // CourtingSomeone intelligence male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.court.opening.intelligence.male.ogg"; Subtitle = "$avr.court.opening.intelligence.male"; Weight = 6;};
		2 extends G3SoundDef { Path = "int.Compliment.3.ogg"; Subtitle = "$int.Compliment.3"; Weight = 2;};
		3 extends G3SoundDef { Path = "int.Compliment.1.ogg"; Subtitle = "$int.Compliment.1"; Weight = 2;};
		4 extends G3SoundDef { Path = "Cutscenes.Reputation.YourFamily.ogg"; Subtitle = "$Cutscenes.Reputation.YourFamily"; Weight = 1;};
	};
};
G3SoundObject
{
	SoundID = 496; // CourtingSomeone charisma male
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.court.opening.charisma.male.ogg"; Subtitle = "$avr.court.opening.charisma.male"; Weight = 6;};
		2 extends G3SoundDef { Path = "int.Positive.Success.Friendly.0.ogg"; Subtitle = "$int.Positive.Success.Friendly.0"; Weight = 2;};
		3 extends G3SoundDef { Path = "int.Compliment.0.ogg"; Subtitle = "$int.Compliment.0"; Weight = 2;};
		4 extends G3SoundDef { Path = "Cutscenes.Reputation.YourFamily.ogg"; Subtitle = "$Cutscenes.Reputation.YourFamily"; Weight = 1;};
	};
};
G3SoundObject
{
	SoundID = 497; // CourtingSomeone perception female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.court.opening.perception.female.ogg"; Subtitle = "$avr.court.opening.perception.female"; Weight = 6;};
		2 extends G3SoundDef { Path = "cf.Liaison.Med.2.ogg"; Subtitle = "$cf.Liaison.Med.2"; Weight = 2;};
		3 extends G3SoundDef { Path = "int.Compliment.2.ogg"; Subtitle = "$int.Compliment.2"; Weight = 2;};
		4 extends G3SoundDef { Path = "Cutscenes.Reputation.YourFamily.ogg"; Subtitle = "$Cutscenes.Reputation.YourFamily"; Weight = 1;};
	};
};
G3SoundObject
{
	SoundID = 498; // CourtingSomeone intelligence female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.court.opening.intelligence.female.ogg"; Subtitle = "$avr.court.opening.intelligence.female"; Weight = 6;};
		2 extends G3SoundDef { Path = "int.Compliment.3.ogg"; Subtitle = "$int.Compliment.3"; Weight = 2;};
		3 extends G3SoundDef { Path = "int.Compliment.1.ogg"; Subtitle = "$int.Compliment.1"; Weight = 2;};
		4 extends G3SoundDef { Path = "Cutscenes.Reputation.YourFamily.ogg"; Subtitle = "$Cutscenes.Reputation.YourFamily"; Weight = 1;};
	};
};
G3SoundObject
{
	SoundID = 499; // CourtingSomeone charisma female
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.court.opening.charisma.female.ogg"; Subtitle = "$avr.court.opening.charisma.female"; Weight = 6;};
		2 extends G3SoundDef { Path = "int.Positive.Success.Friendly.0.ogg"; Subtitle = "$int.Positive.Success.Friendly.0"; Weight = 2;};
		3 extends G3SoundDef { Path = "int.Compliment.0.ogg"; Subtitle = "$int.Compliment.0"; Weight = 2;};
		4 extends G3SoundDef { Path = "Cutscenes.Reputation.YourFamily.ogg"; Subtitle = "$Cutscenes.Reputation.YourFamily"; Weight = 1;};
	};
};
G3SoundObject
{
	SoundID = 500; // CourtingSomeone success both
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.court.answer.success.both.ogg"; Subtitle = "$avr.court.answer.success.both";};
	};
};
G3SoundObject
{
	SoundID = 501; // CourtingSomeone failure both
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.court.answer.failure.both.ogg"; Subtitle = "$avr.court.answer.failure.both";};
	};
};

G3SoundObject
{
	SoundID = 502; // ManipulateLiaison opening 1 both
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.manipLia.opening.1.both.ogg"; Subtitle = "$avr.manipLia.opening.1.both";};
	};
};
G3SoundObject
{
	SoundID = 503; // ManipulateLiaison opening 2 both
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.manipLia.opening.2.both.ogg"; Subtitle = "$avr.manipLia.opening.2.both";};
	};
};
G3SoundObject
{
	SoundID = 504; // ManipulateLiaison success 1 both
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.manipLia.answer.1.success.both.ogg"; Subtitle = "$avr.manipLia.answer.1.success.both";};
	};
};
G3SoundObject
{
	SoundID = 505; // ManipulateLiaison failure 1 both
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.manipLia.answer.1.failure.both.ogg"; Subtitle = "$avr.manipLia.answer.1.failure.both";};
	};
};
G3SoundObject
{
	SoundID = 506; // ManipulateLiaison success 2 both
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.manipLia.answer.2.success.both.ogg"; Subtitle = "$avr.manipLia.answer.2.success.both";};
	};
};
G3SoundObject
{
	SoundID = 507; // ManipulateLiaison failure 2 both
	Category = 5;  // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.manipLia.answer.2.failure.both.ogg"; Subtitle = "$avr.manipLia.answer.2.failure.both";};
	};
};

G3SoundObject
{
	SoundID = 508; // Praise opnening both
	Category = 5;  // ESoundVoices
	Volume = 1.3;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Praise.opening.both.ogg"; Subtitle = "$avr.Praise.opening.both";};
	};
};
G3SoundObject
{
	SoundID = 509; // Denounce opening both
	Category = 5;  // ESoundVoices
	Volume = 1.3;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Denounce.opening.both.ogg"; Subtitle = "$avr.Denounce.opening.both";};
	};
};

G3SoundObject
{
	SoundID = 510; // DuelInsult success
	Category = 5;  // ESoundVoices
	Volume = 1.3;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.DuelInsult.answer.success.both.ogg"; Subtitle = "$avr.DuelInsult.answer.success.both";};
	};
};
G3SoundObject
{
	SoundID = 511; // DuelInsult failure
	Category = 5;  // ESoundVoices
	Volume = 1.3;
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.DuelInsult.answer.failure.both.ogg"; Subtitle = "$avr.DuelInsult.answer.failure.both";};
	};
};

G3SoundObject
{
	SoundID = 512;	// UseStatelyDispatch opening
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "int.GiveGift.3.ogg"; Subtitle = "$int.GiveGift.3";};
	};
};

G3SoundObject
{
	SoundID = 513;	// UseStatelyDispatch failure
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "cf.NPC.ToCitizen.Hatred.3.ogg"; Subtitle = "$cf.NPC.ToCitizen.Hatred.3";};
	};
};

G3SoundObject
{
	SoundID = 514;	// AwardKeyToCity opening
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.AwardKeyToCity.opening.both.ogg"; Subtitle = "$avr.AwardKeyToCity.opening.both";};
	};
};
G3SoundObject
{
	SoundID = 515;	// AwardKeyToCity success
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.AwardKeyToCity.answer.success.both.ogg"; Subtitle = "$avr.AwardKeyToCity.answer.success.both";};
	};
};
G3SoundObject
{
	SoundID = 516;	// AwardKeyToCity failure
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.AwardKeyToCity.answer.failure.both.ogg"; Subtitle = "$avr.AwardKeyToCity.answer.failure.both";};
	};
};

G3SoundObject
{
	SoundID = 517;	// MarkAsOutlaw opening
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.MarkAsOutlaw.opening.both.ogg"; Subtitle = "$avr.MarkAsOutlaw.opening.both";};
	};
};
G3SoundObject
{
	SoundID = 518;	// MarkAsOutlaw success
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.MarkAsOutlaw.answer.success.both.ogg"; Subtitle = "$avr.MarkAsOutlaw.answer.success.both";};
	};
};
G3SoundObject
{
	SoundID = 519;	// MarkAsOutlaw failure
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.MarkAsOutlaw.answer.failure.both.ogg"; Subtitle = "$avr.MarkAsOutlaw.answer.failure.both";};
	};
};

G3SoundObject
{
	SoundID = 520;	// OfficeMeeting Intro
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.OfficeMeeting.Intro.ogg"; Subtitle = "$avr.Cutscene.OfficeMeeting.Intro";};
	};
};
G3SoundObject
{
	SoundID = 521;	// OfficeMeeting FirstItem
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.OfficeMeeting.FirstItem.ogg"; Subtitle = "$avr.Cutscene.OfficeMeeting.FirstItem";};
	};
};
G3SoundObject
{
	SoundID = 522;	// OfficeMeeting NextItem
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.OfficeMeeting.NextItem.ogg"; Subtitle = "$avr.Cutscene.OfficeMeeting.NextItem";};
	};
};
G3SoundObject
{
	SoundID = 523;	// OfficeMeeting InFavor
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.OfficeMeeting.InFavor.ogg"; Subtitle = "$avr.Cutscene.OfficeMeeting.InFavor";};
	};
};
G3SoundObject
{
	SoundID = 524;	// OfficeMeeting Against
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.OfficeMeeting.Against.ogg"; Subtitle = "$avr.Cutscene.OfficeMeeting.Against";};
	};
};
G3SoundObject
{
	SoundID = 525;	// OfficeMeeting Decision
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.Cutscene.OfficeMeeting.Decision.ogg"; Subtitle = "$avr.Cutscene.OfficeMeeting.Decision";};
	};
};

G3SoundObject
{
	SoundID = 526;	// MakeCatholic Opening
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.mCatholic.opening.both.ogg"; Subtitle = "$avr.mCatholic.opening.both";};
	};
};
G3SoundObject
{
	SoundID = 527;	// MakeSecular Opening
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.mSecular.opening.both.ogg"; Subtitle = "$avr.mSecular.opening.both";};
	};
};
G3SoundObject
{
	SoundID = 528;	// MakeProtestant Opening
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.mProtestant.opening.both.ogg"; Subtitle = "$avr.mProtestant.opening.both";};
	};
};
G3SoundObject
{
	SoundID = 529;	// MakeXXX answer success
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.ChangeReligion.answer.success.both.ogg"; Subtitle = "$avr.ChangeReligion.answer.success.both";};
	};
};
G3SoundObject
{
	SoundID = 530;	// MakeXXX answer failure
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "avr.ChangeReligion.answer.failure.both.ogg"; Subtitle = "$avr.ChangeReligion.answer.failure.both";};
	};
};

G3SoundObject
{
	SoundID = 531; //$n.politics.lawsuit.started.title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.politics.lawsuit.started.title.ogg"; Subtitle = "$n.politics.lawsuit.started.title";};
	}; 
};
G3SoundObject
{
	SoundID = 532; //$n.politics.penaltyforfailuretoappear.title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.politics.penaltyforfailuretoappear.title.ogg"; Subtitle = "$n.politics.penaltyforfailuretoappear.title";};
	}; 
};
G3SoundObject
{
	SoundID = 533; //$n.politics.scene.trial.canceled.title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.politics.scene.trial.canceled.title.ogg"; Subtitle = "$n.politics.scene.trial.canceled.title";};
	}; 
};
G3SoundObject
{
	SoundID = 534; //$n.politics.scene.meeting.canceled.title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.politics.scene.meeting.canceled.title.ogg"; Subtitle = "$n.politics.scene.meeting.canceled.title";};
	}; 
};
G3SoundObject
{
	SoundID = 535; //$n.execution.starts.title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.execution.starts.title.ogg"; Subtitle = "$n.execution.starts.title";};
	};
};
G3SoundObject
{
	SoundID = 536; //$n.scene.trial.guilty.title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.scene.trial.guilty.title.ogg"; Subtitle = "$n.scene.trial.guilty.title";};
	}; 
};
G3SoundObject
{
	SoundID = 537; //$n.scene.trial.notguilty.title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.scene.trial.notguilty.title.ogg"; Subtitle = "$n.scene.trial.notguilty.title";};
	}; 
};
G3SoundObject
{
	SoundID = 538; //$n.politics.bribing.title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.politics.bribing.title.ogg"; Subtitle = "$n.politics.bribing.title";};
	}; 
};
G3SoundObject
{
	SoundID = 539; //$n.politics.scene.trial.starts.title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.politics.scene.trial.starts.title.ogg"; Subtitle = "$n.politics.scene.trial.starts.title";};
	}; 
};
G3SoundObject
{
	SoundID = 540; //$n.politics.scene.meeting.starts.title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "n.politics.scene.meeting.starts.title.ogg"; Subtitle = "$n.politics.scene.meeting.starts.title";};
	}; 
};
G3SoundObject
{
	SoundID = 541; //$message.politics.OfficeRejected.Title
	Category = 5; // ESoundVoices
	Sounds = array
	{
		1 extends G3SoundDef { Path = "message.politics.OfficeRejected.Title.ogg"; Subtitle = "$message.politics.OfficeRejected.Title";};
	}; 
};
