//Option 3 (STAT, replace STAT with the main stat used) formulas
Replacements = map
{    
	"SourceScoreFormula" = "SOURCESCOREFORMULA FOR OPTION 3";	
	"TargetScoreFormula" = "TARGETSCOREFORMULA FOR OPTION 3";
	"CritFactor" = "CRITICAL FACTOR FOR OPTION 3"; // (1 - CriticalFactor)
};	
DisplayChance = "EvaluateActionScore.SourceScoreFormula.TargetScoreFormula"; // DON'T CHANGE
OptionSubtext = array { "LIST", "OF", "LOCA", "KEYS" };