//Option 2 (STAT, replace STAT with the main stat used) formulas
Replacements = map
{    
	"SourceScoreFormula" = "SOURCESCOREFORMULA FOR OPTION 2";	
	"TargetScoreFormula" = "TARGETSCOREFORMULA FOR OPTION 2";
	"CritFactor" = "CRITICAL FACTOR FOR OPTION 2"; // (1 - CriticalFactor)
};	
DisplayChance = "EvaluateActionScore.SourceScoreFormula.TargetScoreFormula"; // DON'T CHANGE
OptionSubtext = array { "LIST", "OF", "LOCA", "KEYS" };