//Option 1 (STAT, replace STAT with the main stat used) formulas
Replacements = map
{    
	"SourceScoreFormula" = "SOURCESCOREFORMULA FOR OPTION 1";	
	"TargetScoreFormula" = "TARGETSCOREFORMULA FOR OPTION 1";
	"CritFactor" = "CRITICAL FACTOR FOR OPTION 1"; // (1 - CriticalFactor)
};	
DisplayChance = "EvaluateActionScore.SourceScoreFormula.TargetScoreFormula"; // DON'T CHANGE
OptionSubtext = array { "LIST", "OF", "LOCA", "KEYS" };