ResultObject
{
	Id = "FarmingProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Farmer", "Farming" };
		}
	};
},

ResultObject
{
	Id = "InkeeperProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Innkeeper", "Cooking" };
		}
	};
},

ResultObject
{
	Id = "ApothecaryProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Apothecary", "Healing" };
		}
	};
},

ResultObject
{
	Id = "MedicusProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Medicus", "Healing" };
		}
	};
},

ResultObject
{
	Id = "GravediggerProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Gravedigger", "Working" };
		}
	};
},

ResultObject
{
	Id = "ScholarProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Scholar", "Healing" };
		}
	};
},

ResultObject
{
	Id = "AlchemistProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Alchemist", "Cooking" };
		}
	};
},

ResultObject
{
	Id = "BarberProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Barber", "Haircutting" };
		}
	};
},

ResultObject
{
	Id = "BlacksmithProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Blacksmith", "Smithing" };
		}
	};
},

ResultObject
{
	Id = "TailorProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Tailor", "Tailoring" };
		}
	};
},

ResultObject
{
	Id = "MasonProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Mason", "Stonecutting" };
		}
	};
},

ResultObject
{
	Id = "OrchadistProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Orchadist", "Farming" };
		}
	};
},

ResultObject
{
	Id = "BakerProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Baker", "Baking" };
		}
	};
},

ResultObject
{
	Id = "ButcherProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Butcher", "Butchering" };
		}
	};
},

ResultObject
{
	Id = "FishingProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Fisher", "Fishing" };
		}
	};
},

ResultObject
{
	Id = "MillerProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Miller", "Milling" };
		}
	};
},


ResultObject
{
	Id = "HerbalistProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Herbalist" };
		}
	};
},

ResultObject
{
	Id = "ArtisanProfession";
	Results = array
	{
			@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Artisan", "Smithing" };
		}
	};
},

ResultObject
{
	Id = "MasonProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Mason", "Masonery" };
		}
	};
},

ResultObject
{
	Id = "TinkerProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Tinker", "Tinkering" };
		}
	};
},

ResultObject
{
	Id = "CarpenterProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "Carpenter", "Sawing" };
		}
	};
},

ResultObject
{
	Id = "StonemasonProfession";
	Results = array
	{
		@base/Unlearned
		TagEffect
		{
			Tags = array{ "Profession", "HandicraftStone", "Stonemason" };
		}
	};
}