ResultObject
{
	Id = "FarmingProfession";
	Results = array
	{
		TagEffect
		{
			Tags = array{ "Profession", "Farmer", "Farming" };
		}
	};
},

ResultObject
{
	Id = "HerbalistProfession";
	Results = array
	{
		TagEffect
		{
			Tags = array{ "Profession", "Herbalist" };
		}
	};
},

ResultObject
{
	Id = "ArtisanProfession";
	Results = array
	{
		TagEffect
		{
			Tags = array{ "Profession", "Artisan", "Smithing" };
		}
	};
},

ResultObject
{
	Id = "MasonProfession";
	Results = array
	{
		TagEffect
		{
			Tags = array{ "Profession", "Mason", "Masonery" };
		}
	};
},

ResultObject
{
	Id = "TinkerProfession";
	Results = array
	{
		TagEffect
		{
			Tags = array{ "Profession", "Tinker", "Tinkering" };
		}
	};
}